version: 2

jobs:
    # Build Cyclus
    build:
        docker:
            - image: cyclus/cyclus:latest
              auth:
                username: $DOCKERHUB_USER
                password: $DOCKERHUB_PASS
        working_directory: ~/cycamore
        steps:
            # Ensure your image has git (required by git to clone via SSH) so that CircleCI can clone your repo
            - run: apt-get -qq update; apt-get -y install git openssh-client
            - checkout
            - run:
                name: Build Cycamore
                command: |
                    python install.py -j 2 --build-type=Release \
                    -DBLAS_LIBRARIES="/opt/conda/lib/libblas.so" \
                    -DLAPACK_LIBRARIES="/opt/conda/lib/liblapack.so"
            - run:
                name: save SHA to a file
                command: echo $CIRCLE_SHA1 > .circle-sha
            - save_cache:
                key: v1-repo-{{ checksum ".circle-sha" }}
                paths:
                  - /root



    # Test
    unit_test:
        docker:
            - image: cyclus/cyclus:latest
              auth:
                username: $DOCKERHUB_USER
                password: $DOCKERHUB_PASS
        working_directory: ~/root
        steps:
            - run:
                name: save SHA to a file
                command: echo $CIRCLE_SHA1 > .circle-sha
            - restore_cache:
                keys:
                  - v1-repo-{{ checksum ".circle-sha" }}
            - run:
                name: Unit Test
                command: /root/.local/bin/cycamore_unit_tests; exit $?
    nosetest:
        docker:
            - image: cyclus/cyclus:latest
              auth:
                username: $DOCKERHUB_USER
                password: $DOCKERHUB_PASS
        working_directory: ~/root
        steps:
            - run:
                name: save SHA to a file
                command: echo $CIRCLE_SHA1 > .circle-sha
            - restore_cache:
                keys:
                  - v1-repo-{{ checksum ".circle-sha" }}
            - run:
                name: Install nosetest
                command: pip install nose
            - run:
                name: Nosetests
                command: nosetests -w ~/cycamore/tests; exit $?

                
    # Update docker container
    deploy: # Cycamore -> Cycamore:latest
        docker:
            - image: circleci/ruby:2.4-node
              auth:
                username: $DOCKERHUB_USER
                password: $DOCKERHUB_PASS
        working_directory: ~/cycamore
        steps:
            - checkout
            - run:
                name: Place the proper Dockerfile
                command: cp docker/master-ci/Dockerfile .
            - setup_remote_docker
            - run:
                name: log into Docker
                command: |
                    docker login -u $DOCKER_USER -p $DOCKER_PASS
            - run:
                name: Build Docker container
                command: docker build --rm=false -t cyclus/cycamore:latest .
            - run:
                name: Push on DockerHub
                command: docker push cyclus/cycamore:latest # push to docker depot

    deploy_stable: # Cycamore:stable
        docker:
            - image: circleci/ruby:2.4-node
              auth:
                username: $DOCKERHUB_USER
                password: $DOCKERHUB_PASS
        working_directory: ~/cycamore
        steps:
            - checkout
            - run:
                name: Place the proper Dockerfile
                command: cp docker/release-ci/Dockerfile .
            - setup_remote_docker
            - run:
                name: Log on DockerHub
                command: |
                  docker login -u $DOCKER_USER -p $DOCKER_PASS
            - run:
                name: Build Docker container
                command: docker build -t cyclus/cycamore:stable .
            - run:
                name: Push on DockerHub
                command: docker push cyclus/cycamore:stable # push to docker depot


    # Debian package generation (on master update)
    deb_generation:
        docker:
            - image: circleci/ruby:2.4-node
              auth:
                username: $DOCKERHUB_USER
                password: $DOCKERHUB_PASS
        working_directory: ~/cycamore
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Tag and Push on DockerHub
                no_output_timeout: "20m"
                command: |
                  docker/deb-ci/build_upload_deb.sh 14
                  docker/deb-ci/build_upload_deb.sh 16


workflows:
    version: 2
    build_and_test:
        jobs:

            # on a pr // all branch
            - build:
                context: Dockerhub
            - unit_test:
                context: Dockerhub
                requires:
                    - build
            - nosetest:
                context: Dockerhub
                requires:
                    - build

            # Merge on Master
            - deploy:
                context: Dockerhub
                filters:
                    branches:
                        only: master
                requires:
                    - unit_test
                    - nosetest


             # The following should now be done on version tag.
            - deploy_stable:
                context: Dockerhub
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /.*/
                requires:
                    - unit_test
                    - nosetest

            - deb_generation:
                context: Dockerhub
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /.*/
                requires:
                    - unit_test
                    - nosetest
