#ifndef CYCAMORE_SRC_VERSION_H_
#define CYCAMORE_SRC_VERSION_H_

#define CYCAMORE_VERSION_MAJOR 1
#define CYCAMORE_VERSION_MINOR 0
#define CYCAMORE_VERSION_MICRO 0

#endif  // CYCAMORE_SRC_VERSION_H_
