CYCAMORE: cycamore::DeployInst Class Reference
cycamore::DeployInst Class Reference
The DeployInst class inherits from the Institution class and is dynamically loaded by the Agent class when requested.
#include <deploy_inst.h>
Public Member Functions
virtual Json::Value annotations ()
virtual void Build (cyclus::Agent *parent)
virtual void Build (cyclus::Agent *parent)
virtual cyclus::Agent * Clone ()
DeployInst (cyclus::Context *ctx)
DeployInst (cyclus::Context *ctx)
virtual void InfileToDb (cyclus::InfileTree *tree, cyclus::DbInit di)
virtual void InitFrom (cyclus::QueryableBackend *b)
virtual void InitFrom (cycamore::DeployInst *m)
virtual std::string schema ()
virtual void Snapshot (cyclus::DbInit di)
virtual ~DeployInst ()
virtual ~DeployInst ()
Protected Attributes
BuildSched build_sched_
a collection of orders to build
Detailed Description
The DeployInst class inherits from the Institution class and is dynamically loaded by the Agent class when requested.
This agent implements a simple institution agent that deploys specific facilities as defined explicitly in the input file.
Definition at line 22 of file build/cycamore/deploy_inst.h.
Constructor & Destructor Documentation
cycamore::DeployInst::DeployInst (cyclus::Context * ctx)
Definition at line 7 of file build/cycamore/deploy_inst.cc.
Referenced by Clone().
cycamore::DeployInst::~DeployInst () [virtual]
Definition at line 9 of file build/cycamore/deploy_inst.cc.
cycamore::DeployInst::DeployInst (cyclus::Context * ctx)
virtual cycamore::DeployInst::~DeployInst () [virtual]
Member Function Documentation
virtual Json::Value cycamore::DeployInst::annotations () [inline, virtual]
Definition at line 45 of file build/cycamore/deploy_inst.h.
virtual void cycamore::DeployInst::Build (cyclus::Agent * parent) [virtual]
void cycamore::DeployInst::Build (cyclus::Agent * parent) [virtual]
Definition at line 82 of file build/cycamore/deploy_inst.cc.
References build_sched_.
cyclus::Agent * cycamore::DeployInst::Clone () [virtual]
Definition at line 10 of file build/cycamore/deploy_inst.cc.
References DeployInst(), and InitFrom().
void cycamore::DeployInst::InfileToDb (cyclus::InfileTree * tree, cyclus::DbInit di) [virtual]
Definition at line 34 of file build/cycamore/deploy_inst.cc.
void cycamore::DeployInst::InitFrom (cyclus::QueryableBackend * b) [virtual]
Definition at line 51 of file build/cycamore/deploy_inst.cc.
References build_sched_.
Referenced by Clone(), and InitFrom().
void cycamore::DeployInst::InitFrom (cycamore::DeployInst * m) [virtual]
Definition at line 61 of file build/cycamore/deploy_inst.cc.
References build_sched_, and InitFrom().
std::string cycamore::DeployInst::schema () [virtual]
Definition at line 17 of file build/cycamore/deploy_inst.cc.
void cycamore::DeployInst::Snapshot (cyclus::DbInit di) [virtual]
Definition at line 66 of file build/cycamore/deploy_inst.cc.
References build_sched_.
Member Data Documentation
BuildSched cycamore::DeployInst::build_sched_ [protected]
a collection of orders to build
Definition at line 70 of file build/cycamore/deploy_inst.h.
Referenced by Build(), InitFrom(), and Snapshot().
The documentation for this class was generated from the following files:
build/cycamore/deploy_inst.h
src/deploy_inst.h
build/cycamore/deploy_inst.cc
src/deploy_inst.cc