CYCAMORE: cycamore::FissConverter Class Reference
cycamore::FissConverter Class Reference
Public Member Functions
virtual double convert (cyclus::Material::Ptr m, cyclus::Arc const *a=NULL, cyclus::ExchangeTranslationContext< cyclus::Material > const *ctx=NULL) const
virtual double convert (cyclus::Material::Ptr m, cyclus::Arc const *a=NULL, cyclus::ExchangeTranslationContext< cyclus::Material > const *ctx=NULL) const
virtual double convert (cyclus::Material::Ptr m, cyclus::Arc const *a=NULL, cyclus::ExchangeTranslationContext< cyclus::Material > const *ctx=NULL) const
FissConverter (Composition::Ptr c_fill, Composition::Ptr c_fiss, Composition::Ptr c_topup, std::string spectrum)
FissConverter (Composition::Ptr c_fill, Composition::Ptr c_fiss, Composition::Ptr c_topup, std::string spectrum)
FissConverter (Composition::Ptr c_fill, Composition::Ptr c_fiss, Composition::Ptr c_topup, std::string spectrum)
virtual ~FissConverter ()
virtual ~FissConverter ()
virtual ~FissConverter ()
Private Attributes
Composition::Ptr c_fill_
Composition::Ptr c_fiss_
Composition::Ptr c_topup_
std::string spec_
double w_fill_
double w_fiss_
double w_topup_
Detailed Description
Definition at line 15 of file _tmp_build/cycamore/fuel_fab.cc.
Constructor & Destructor Documentation
cycamore::FissConverter::FissConverter (Composition::Ptr c_fill, Composition::Ptr c_fiss, Composition::Ptr c_topup, std::string spectrum) inline
Definition at line 17 of file _tmp_build/cycamore/fuel_fab.cc.
References cycamore::CosiWeight(), w_fill_, w_fiss_, and w_topup_.
virtual cycamore::FissConverter::~FissConverter () inline virtual
Definition at line 25 of file _tmp_build/cycamore/fuel_fab.cc.
cycamore::FissConverter::FissConverter (Composition::Ptr c_fill, Composition::Ptr c_fiss, Composition::Ptr c_topup, std::string spectrum) inline
Definition at line 17 of file build/cycamore/fuel_fab.cc.
References cycamore::CosiWeight(), w_fill_, w_fiss_, and w_topup_.
virtual cycamore::FissConverter::~FissConverter () inline virtual
Definition at line 25 of file build/cycamore/fuel_fab.cc.
cycamore::FissConverter::FissConverter (Composition::Ptr c_fill, Composition::Ptr c_fiss, Composition::Ptr c_topup, std::string spectrum) inline
Definition at line 16 of file src/fuel_fab.cc.
References cycamore::CosiWeight(), w_fill_, w_fiss_, and w_topup_.
virtual cycamore::FissConverter::~FissConverter () inline virtual
Definition at line 24 of file src/fuel_fab.cc.
Member Function Documentation
virtual double cycamore::FissConverter::convert (cyclus::Material::Ptr m, cyclus::Arc const * a = NULL, cyclus::ExchangeTranslationContext< cyclus::Material > const * ctx = NULL) const inline virtual
Definition at line 26 of file src/fuel_fab.cc.
References cycamore::AtomToMassFrac(), c_fill_, c_fiss_, c_topup_, cycamore::CosiWeight(), cycamore::HighFrac(), cycamore::LowFrac(), spec_, cycamore::ValidWeights(), w_fill_, w_fiss_, and w_topup_.
virtual double cycamore::FissConverter::convert (cyclus::Material::Ptr m, cyclus::Arc const * a = NULL, cyclus::ExchangeTranslationContext< cyclus::Material > const * ctx = NULL) const inline virtual
Definition at line 27 of file _tmp_build/cycamore/fuel_fab.cc.
References cycamore::AtomToMassFrac(), c_fill_, c_fiss_, c_topup_, cycamore::CosiWeight(), cycamore::HighFrac(), cycamore::LowFrac(), spec_, cycamore::ValidWeights(), w_fill_, w_fiss_, and w_topup_.
virtual double cycamore::FissConverter::convert (cyclus::Material::Ptr m, cyclus::Arc const * a = NULL, cyclus::ExchangeTranslationContext< cyclus::Material > const * ctx = NULL) const inline virtual
Definition at line 27 of file build/cycamore/fuel_fab.cc.
References cycamore::AtomToMassFrac(), c_fill_, c_fiss_, c_topup_, cycamore::CosiWeight(), cycamore::HighFrac(), cycamore::LowFrac(), spec_, cycamore::ValidWeights(), w_fill_, w_fiss_, and w_topup_.
Member Data Documentation
Composition::Ptr cycamore::FissConverter::c_fill_ private
Definition at line 50 of file _tmp_build/cycamore/fuel_fab.cc.
Referenced by convert().
Composition::Ptr cycamore::FissConverter::c_fiss_ private
Definition at line 49 of file _tmp_build/cycamore/fuel_fab.cc.
Referenced by convert().
Composition::Ptr cycamore::FissConverter::c_topup_ private
Definition at line 51 of file _tmp_build/cycamore/fuel_fab.cc.
Referenced by convert().
std::string cycamore::FissConverter::spec_ private
Definition at line 45 of file _tmp_build/cycamore/fuel_fab.cc.
Referenced by convert().
double cycamore::FissConverter::w_fill_ private
Definition at line 48 of file _tmp_build/cycamore/fuel_fab.cc.
Referenced by convert(), and FissConverter().
double cycamore::FissConverter::w_fiss_ private
Definition at line 46 of file _tmp_build/cycamore/fuel_fab.cc.
Referenced by convert(), and FissConverter().
double cycamore::FissConverter::w_topup_ private
Definition at line 47 of file _tmp_build/cycamore/fuel_fab.cc.
Referenced by convert(), and FissConverter().
The documentation for this class was generated from the following file:
_tmp_build/cycamore/fuel_fab.cc