CYCAMORE: cycamore::EnrichmentFacilityTest Class Reference
cycamore::EnrichmentFacilityTest Class Reference
#include <enrichment_facility_tests.h>
Protected Member Functions
void DoAddMat (cyclus::Material::Ptr mat)
void DoAddMat (cyclus::Material::Ptr mat)
cyclus::Material::Ptr DoBid (cyclus::Material::Ptr mat)
cyclus::Material::Ptr DoBid (cyclus::Material::Ptr mat)
cyclus::Material::Ptr DoEnrich (cyclus::Material::Ptr mat, double qty)
cyclus::Material::Ptr DoEnrich (cyclus::Material::Ptr mat, double qty)
cyclus::Material::Ptr DoOffer (cyclus::Material::Ptr mat)
cyclus::Material::Ptr DoOffer (cyclus::Material::Ptr mat)
cyclus::Material::Ptr DoRequest ()
cyclus::Material::Ptr DoRequest ()
boost::shared_ptr
< cyclus::ExchangeContext
< cyclus::Material > > GetContext (int nreqs, int nvalid)
boost::shared_ptr
< cyclus::ExchangeContext
< cyclus::Material > > GetContext (int nreqs, int nvalid)
cyclus::Material::Ptr GetMat (double qty)
cyclus::Material::Ptr GetMat (double qty)
cyclus::Material::Ptr GetReqMat (double qty, double enr)
cyclus::Material::Ptr GetReqMat (double qty, double enr)
void InitParameters ()
void InitParameters ()
virtual void SetUp ()
virtual void SetUp ()
void SetUpSource ()
void SetUpSource ()
virtual void TearDown ()
virtual void TearDown ()
Protected Attributes
double commodity_price
double feed_assay
std::string in_commod
std::string in_recipe
double inv_size
std::string out_commod
cyclus::Composition::Ptr recipe
double reserves
EnrichmentFacility * src_facility
double swu_capacity
double tails_assay
cyclus::TestContext tc_
TestFacility * trader
Detailed Description
Definition at line 18 of file build/cycamore/enrichment_facility_tests.h.
Member Function Documentation
void cycamore::EnrichmentFacilityTest::DoAddMat (cyclus::Material::Ptr mat) [protected]
Definition at line 83 of file build/cycamore/enrichment_facility_tests.cc.
References cycamore::EnrichmentFacility::AddMat_(), and src_facility.
void cycamore::EnrichmentFacilityTest::DoAddMat (cyclus::Material::Ptr mat) [protected]
cyclus::Material::Ptr cycamore::EnrichmentFacilityTest::DoBid (cyclus::Material::Ptr mat) [protected]
cyclus::Material::Ptr cycamore::EnrichmentFacilityTest::DoBid (cyclus::Material::Ptr mat) [protected]
cyclus::Material::Ptr cycamore::EnrichmentFacilityTest::DoEnrich (cyclus::Material::Ptr mat, double qty) [protected]
Definition at line 100 of file build/cycamore/enrichment_facility_tests.cc.
References cycamore::EnrichmentFacility::Enrich_(), and src_facility.
cyclus::Material::Ptr cycamore::EnrichmentFacilityTest::DoEnrich (cyclus::Material::Ptr mat, double qty) [protected]
cyclus::Material::Ptr cycamore::EnrichmentFacilityTest::DoOffer (cyclus::Material::Ptr mat) [protected]
Definition at line 94 of file build/cycamore/enrichment_facility_tests.cc.
References cycamore::EnrichmentFacility::Offer_(), and src_facility.
cyclus::Material::Ptr cycamore::EnrichmentFacilityTest::DoOffer (cyclus::Material::Ptr mat) [protected]
cyclus::Material::Ptr cycamore::EnrichmentFacilityTest::DoRequest () [protected]
Definition at line 88 of file build/cycamore/enrichment_facility_tests.cc.
References cycamore::EnrichmentFacility::Request_(), and src_facility.
cyclus::Material::Ptr cycamore::EnrichmentFacilityTest::DoRequest () [protected]
boost::shared_ptr< cyclus::ExchangeContext< cyclus::Material > > cycamore::EnrichmentFacilityTest::GetContext (int nreqs, int nvalid) [protected]
Parameters:
nreqs the total number of requests
nvalid the number of requests that are valid
Definition at line 407 of file build/cycamore/enrichment_facility_tests.cc.
References GetReqMat(), out_commod, and trader.
boost::shared_ptr< cyclus::ExchangeContext<cyclus::Material> > cycamore::EnrichmentFacilityTest::GetContext (int nreqs, int nvalid) [protected]
Parameters:
nreqs the total number of requests
nvalid the number of requests that are valid
cyclus::Material::Ptr cycamore::EnrichmentFacilityTest::GetMat (double qty) [protected]
cyclus::Material::Ptr cycamore::EnrichmentFacilityTest::GetMat (double qty) [protected]
Definition at line 67 of file build/cycamore/enrichment_facility_tests.cc.
References in_recipe, and tc_.
cyclus::Material::Ptr cycamore::EnrichmentFacilityTest::GetReqMat (double qty, double enr) [protected]
Parameters:
enr the enrichment percent, i.e. for 5 w/o, enr = 0.05
cyclus::Material::Ptr cycamore::EnrichmentFacilityTest::GetReqMat (double qty, double enr) [protected]
Parameters:
enr the enrichment percent, i.e. for 5 w/o, enr = 0.05
Definition at line 73 of file build/cycamore/enrichment_facility_tests.cc.
Referenced by GetContext().
void cycamore::EnrichmentFacilityTest::InitParameters () [protected]
Definition at line 32 of file build/cycamore/enrichment_facility_tests.cc.
References feed_assay, in_commod, in_recipe, inv_size, out_commod, recipe, reserves, swu_capacity, tails_assay, and tc_.
Referenced by SetUp().
void cycamore::EnrichmentFacilityTest::InitParameters () [protected]
virtual void cycamore::EnrichmentFacilityTest::SetUp () [protected, virtual]
void cycamore::EnrichmentFacilityTest::SetUp () [protected, virtual]
Definition at line 17 of file build/cycamore/enrichment_facility_tests.cc.
References InitParameters(), SetUpSource(), src_facility, tc_, and trader.
void cycamore::EnrichmentFacilityTest::SetUpSource () [protected]
Definition at line 55 of file build/cycamore/enrichment_facility_tests.cc.
References feed_assay, cycamore::EnrichmentFacility::FeedAssay(), in_commod, cycamore::EnrichmentFacility::in_commodity(), in_recipe, cycamore::EnrichmentFacility::InitialReserves(), cycamore::EnrichmentFacility::InRecipe(), inv_size, out_commod, cycamore::EnrichmentFacility::out_commodity(), reserves, cycamore::EnrichmentFacility::SetMaxInventorySize(), src_facility, swu_capacity, cycamore::EnrichmentFacility::SwuCapacity(), tails_assay, and cycamore::EnrichmentFacility::TailsAssay().
Referenced by SetUp().
void cycamore::EnrichmentFacilityTest::SetUpSource () [protected]
void cycamore::EnrichmentFacilityTest::TearDown () [protected, virtual]
Definition at line 27 of file build/cycamore/enrichment_facility_tests.cc.
References src_facility.
virtual void cycamore::EnrichmentFacilityTest::TearDown () [protected, virtual]
Member Data Documentation
double cycamore::EnrichmentFacilityTest::commodity_price [protected]
Definition at line 26 of file build/cycamore/enrichment_facility_tests.h.
double cycamore::EnrichmentFacilityTest::feed_assay [protected]
Definition at line 26 of file build/cycamore/enrichment_facility_tests.h.
Referenced by InitParameters(), and SetUpSource().
std::string cycamore::EnrichmentFacilityTest::in_commod [protected]
Definition at line 22 of file build/cycamore/enrichment_facility_tests.h.
Referenced by InitParameters(), and SetUpSource().
std::string cycamore::EnrichmentFacilityTest::in_recipe [protected]
Definition at line 22 of file build/cycamore/enrichment_facility_tests.h.
Referenced by GetMat(), InitParameters(), and SetUpSource().
double cycamore::EnrichmentFacilityTest::inv_size [protected]
Definition at line 26 of file build/cycamore/enrichment_facility_tests.h.
Referenced by InitParameters(), and SetUpSource().
std::string cycamore::EnrichmentFacilityTest::out_commod [protected]
Definition at line 22 of file build/cycamore/enrichment_facility_tests.h.
Referenced by GetContext(), InitParameters(), and SetUpSource().
cyclus::Composition::Ptr cycamore::EnrichmentFacilityTest::recipe [protected]
Definition at line 23 of file build/cycamore/enrichment_facility_tests.h.
Referenced by InitParameters().
double cycamore::EnrichmentFacilityTest::reserves [protected]
Definition at line 28 of file build/cycamore/enrichment_facility_tests.h.
Referenced by InitParameters(), and SetUpSource().
EnrichmentFacility * cycamore::EnrichmentFacilityTest::src_facility [protected]
Definition at line 21 of file build/cycamore/enrichment_facility_tests.h.
Referenced by DoAddMat(), DoEnrich(), DoOffer(), DoRequest(), SetUp(), SetUpSource(), and TearDown().
double cycamore::EnrichmentFacilityTest::swu_capacity [protected]
Definition at line 26 of file build/cycamore/enrichment_facility_tests.h.
Referenced by InitParameters(), and SetUpSource().
double cycamore::EnrichmentFacilityTest::tails_assay [protected]
Definition at line 26 of file build/cycamore/enrichment_facility_tests.h.
Referenced by InitParameters(), and SetUpSource().
cyclus::TestContext cycamore::EnrichmentFacilityTest::tc_ [protected]
Definition at line 20 of file build/cycamore/enrichment_facility_tests.h.
Referenced by GetMat(), InitParameters(), and SetUp().
TestFacility * cycamore::EnrichmentFacilityTest::trader [protected]
Definition at line 24 of file build/cycamore/enrichment_facility_tests.h.
Referenced by GetContext(), and SetUp().
The documentation for this class was generated from the following files:
build/cycamore/enrichment_facility_tests.h
src/enrichment_facility_tests.h
build/cycamore/enrichment_facility_tests.cc
src/enrichment_facility_tests.cc