CYCAMORE: TestProducer Class Reference
TestProducer Class Reference
#include <manager_inst_tests.h>
Public Member Functions
cyclus::Agent * Clone ()
cyclus::Agent * Clone ()
cyclus::Agent * Clone ()
void InitFrom (TestProducer *m)
void InitFrom (TestProducer *m)
void InitFrom (TestProducer *m)
void InitInv (cyclus::Inventories &inv)
void InitInv (cyclus::Inventories &inv)
void InitInv (cyclus::Inventories &inv)
cyclus::Inventories SnapshotInv ()
cyclus::Inventories SnapshotInv ()
cyclus::Inventories SnapshotInv ()
TestProducer (cyclus::Context *ctx)
TestProducer (cyclus::Context *ctx)
TestProducer (cyclus::Context *ctx)
void Tick ()
void Tick ()
void Tick ()
void Tock ()
void Tock ()
void Tock ()
~TestProducer ()
~TestProducer ()
~TestProducer ()
Detailed Description
Definition at line 16 of file _tmp_build/cycamore/manager_inst_tests.h.
Constructor & Destructor Documentation
TestProducer::TestProducer (cyclus::Context * ctx)
Definition at line 4 of file _tmp_build/cycamore/manager_inst_tests.cc.
Referenced by Clone().
TestProducer::~TestProducer ()
Definition at line 7 of file _tmp_build/cycamore/manager_inst_tests.cc.
TestProducer::TestProducer (cyclus::Context * ctx)
TestProducer::~TestProducer ()
TestProducer::TestProducer (cyclus::Context * ctx)
TestProducer::~TestProducer ()
Member Function Documentation
cyclus::Agent* TestProducer::Clone () inline
Definition at line 23 of file _tmp_build/cycamore/manager_inst_tests.h.
References InitFrom(), and TestProducer().
cyclus::Agent* TestProducer::Clone () inline
Definition at line 23 of file build/cycamore/manager_inst_tests.h.
References InitFrom(), and TestProducer().
cyclus::Agent* TestProducer::Clone () inline
Definition at line 23 of file src/manager_inst_tests.h.
References InitFrom(), and TestProducer().
void TestProducer::InitFrom (TestProducer * m) inline
Definition at line 29 of file _tmp_build/cycamore/manager_inst_tests.h.
Referenced by Clone().
void TestProducer::InitFrom (TestProducer * m) inline
Definition at line 29 of file build/cycamore/manager_inst_tests.h.
void TestProducer::InitFrom (TestProducer * m) inline
Definition at line 29 of file src/manager_inst_tests.h.
void TestProducer::InitInv (cyclus::Inventories & inv) inline
Definition at line 33 of file src/manager_inst_tests.h.
void TestProducer::InitInv (cyclus::Inventories & inv) inline
Definition at line 33 of file build/cycamore/manager_inst_tests.h.
void TestProducer::InitInv (cyclus::Inventories & inv) inline
Definition at line 33 of file _tmp_build/cycamore/manager_inst_tests.h.
cyclus::Inventories TestProducer::SnapshotInv () inline
Definition at line 35 of file _tmp_build/cycamore/manager_inst_tests.h.
cyclus::Inventories TestProducer::SnapshotInv () inline
Definition at line 35 of file src/manager_inst_tests.h.
cyclus::Inventories TestProducer::SnapshotInv () inline
Definition at line 35 of file build/cycamore/manager_inst_tests.h.
void TestProducer::Tick () inline
Definition at line 38 of file _tmp_build/cycamore/manager_inst_tests.h.
void TestProducer::Tick () inline
Definition at line 38 of file build/cycamore/manager_inst_tests.h.
void TestProducer::Tick () inline
Definition at line 38 of file src/manager_inst_tests.h.
void TestProducer::Tock () inline
Definition at line 37 of file _tmp_build/cycamore/manager_inst_tests.h.
void TestProducer::Tock () inline
Definition at line 37 of file src/manager_inst_tests.h.
void TestProducer::Tock () inline
Definition at line 37 of file build/cycamore/manager_inst_tests.h.
The documentation for this class was generated from the following files:
_tmp_build/cycamore/manager_inst_tests.h
_tmp_build/cycamore/manager_inst_tests.cc