CYCAMORE: cycamore::EnrichmentFacility Class Reference
cycamore::EnrichmentFacility Class Reference
#include <enrichment_facility.h>
Public Member Functions
virtual void AcceptMatlTrades (const std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > &responses)
The EnrichmentFacility place accepted trade Materials in their Inventory.
virtual void AcceptMatlTrades (const std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > &responses)
The EnrichmentFacility place accepted trade Materials in their Inventory.
virtual Json::Value annotations ()
virtual void Build (cyclus::Agent *parent)
perform module-specific tasks when entering the simulation
virtual void Build (cyclus::Agent *parent)
perform module-specific tasks when entering the simulation
virtual cyclus::Agent * Clone ()
double CurrentSwuCapacity () const
double CurrentSwuCapacity () const
EnrichmentFacility (cyclus::Context *ctx)
Constructor for the EnrichmentFacility class.
EnrichmentFacility (cyclus::Context *ctx)
Constructor for the EnrichmentFacility class.
void FeedAssay (double assay)
double FeedAssay () const
void FeedAssay (double assay)
double FeedAssay () const
virtual std::set
< cyclus::BidPortfolio
< cyclus::Material >::Ptr > GetMatlBids (cyclus::CommodMap< cyclus::Material >::type &commod_requests)
Responds to each request for this facility's commodity.
virtual std::set
< cyclus::BidPortfolio
< cyclus::Material >::Ptr > GetMatlBids (cyclus::CommodMap< cyclus::Material >::type &commod_requests)
Responds to each request for this facility's commodity.
virtual std::set
< cyclus::RequestPortfolio
< cyclus::Material >::Ptr > GetMatlRequests ()
The EnrichmentFacility request Materials of its given commodity.
virtual std::set
< cyclus::RequestPortfolio
< cyclus::Material >::Ptr > GetMatlRequests ()
The EnrichmentFacility request Materials of its given commodity.
virtual void GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > &trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > &responses)
respond to each trade with a material enriched to the appropriate level given this facility's inventory
virtual void GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > &trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > &responses)
respond to each trade with a material enriched to the appropriate level given this facility's inventory
void in_commodity (std::string in_com)
std::string in_commodity () const
void in_commodity (std::string in_com)
std::string in_commodity () const
virtual void InfileToDb (cyclus::InfileTree *tree, cyclus::DbInit di)
virtual void InitFrom (cycamore::EnrichmentFacility *m)
virtual void InitFrom (cyclus::QueryableBackend *b)
void InitialReserves (double qty)
this facility's initial conditions
double InitialReserves () const
void InitialReserves (double qty)
this facility's initial conditions
double InitialReserves () const
virtual void InitInv (cyclus::Inventories &inv)
void InRecipe (std::string in_rec)
std::string InRecipe () const
void InRecipe (std::string in_rec)
std::string InRecipe () const
double InventorySize () const
double InventorySize () const
double MaxInventorySize () const
double MaxInventorySize () const
void out_commodity (std::string out_com)
std::string out_commodity () const
void out_commodity (std::string out_com)
std::string out_commodity () const
virtual std::string schema ()
void SetMaxInventorySize (double size)
void SetMaxInventorySize (double size)
virtual void Snapshot (cyclus::DbInit di)
virtual cyclus::Inventories SnapshotInv ()
virtual std::string str ()
Print information about this agent.
virtual std::string str ()
Print information about this agent.
void SwuCapacity (double capacity)
double SwuCapacity () const
void SwuCapacity (double capacity)
double SwuCapacity () const
const
cyclus::toolkit::ResourceBuff & Tails () const
const
cyclus::toolkit::ResourceBuff & Tails () const
void TailsAssay (double assay)
double TailsAssay () const
void TailsAssay (double assay)
double TailsAssay () const
virtual void Tick ()
Each facility is prompted to do its beginning-of-time-step stuff at the tick of the timer.
virtual void Tick ()
Each facility is prompted to do its beginning-of-time-step stuff at the tick of the timer.
virtual void Tock ()
Each facility is prompted to its end-of-time-step stuff on the tock of the timer.
virtual void Tock ()
Each facility is prompted to its end-of-time-step stuff on the tock of the timer.
bool ValidReq (const cyclus::Material::Ptr mat)
Determines if a particular material is a valid request to respond to.
bool ValidReq (const cyclus::Material::Ptr mat)
Determines if a particular material is a valid request to respond to.
virtual ~EnrichmentFacility ()
Destructor for the EnrichmentFacility class.
virtual ~EnrichmentFacility ()
Destructor for the EnrichmentFacility class.
Private Member Functions
void AddMat_ (cyclus::Material::Ptr mat)
adds a material into the natural uranium inventory
void AddMat_ (cyclus::Material::Ptr mat)
adds a material into the natural uranium inventory
cyclus::Material::Ptr Enrich_ (cyclus::Material::Ptr mat, double qty)
cyclus::Material::Ptr Enrich_ (cyclus::Material::Ptr mat, double qty)
cyclus::Material::Ptr Offer_ (cyclus::Material::Ptr req)
Generates a material offer for a given request.
cyclus::Material::Ptr Offer_ (cyclus::Material::Ptr req)
Generates a material offer for a given request.
void RecordEnrichment_ (double natural_u, double swu)
records and enrichment with the cyclus::Recorder
void RecordEnrichment_ (double natural_u, double swu)
records and enrichment with the cyclus::Recorder
cyclus::Material::Ptr Request_ ()
generates a request for this facility given its current state.
cyclus::Material::Ptr Request_ ()
generates a request for this facility given its current state.
Private Attributes
double current_swu_capacity
double feed_assay
std::string in_commod
std::string in_recipe
double initial_reserves
cyclus::toolkit::ResourceBuff inventory
double max_inv_size
std::string out_commod
double swu_capacity
cyclus::toolkit::ResourceBuff tails
double tails_assay
Friends
class EnrichmentFacilityTest
Detailed Description
Introduction
The EnrichmentFacility is a simple Agent to agent the enriching of natural Uranium in a Cyclus simulation. It requests its input recipe (nominally natural Uranium), and produces any amount of enriched Uranium, given the its natural uranium inventory constraint and its SWU capacity constraint.
Requests
The EnrichmentFacility will request from the cyclus::ResourceExchange a cyclus::Material whose quantity is its remaining inventory capacity and whose composition is that of its input recipe.
Accepting Trades
The EnrichmentFacility adds any accepted trades to its inventory.
Bids
The EnrichmentFacility will bid on any request for its output commodity. It will bid either the request quantity, or the quanity associated with either its SWU constraint or natural uranium constraint, whichever is lower.
Executing Trades
The EnrichmentFacility will execute trades for its output commodity in the following manner: #. Determine the trade's quantity and product assay #. Determine the natural Uranium and SWU requires to create that product #. Remove the required quantity of natural Uranium from its inventory #. Extract the appropriate composition of enriched Uranium #. Send the enriched Uranium as the trade resource
Gotchas
#. In its current form, the EnrichmentFacility can only accept cyclus::Material having the composition of its input recipe. If a cyclus::Material of a different composition is sent to it, an exception will be thrown.
#. During the trading phase, an exception will be thrown if either the EnrichmentFacility's SWU or inventory constraint is breached.
Improvments
The primary improvement to the EnrichmentFacility would be to relax the requirement that all input material have the in_recipe composition (i.e., allow different base enrichments of Uranium).
How would I go about doing so? I'd likely develop an EnrichmentBuffer-type class that can be queried as to its SWU and natural Uranium capacity.
Definition at line 123 of file build/cycamore/enrichment_facility.h.
Constructor & Destructor Documentation
cycamore::EnrichmentFacility::EnrichmentFacility (cyclus::Context * ctx)
Constructor for the EnrichmentFacility class.
Parameters:
ctx the cyclus context for access to simulation-wide parameters
Definition at line 15 of file build/cycamore/enrichment_facility.cc.
Referenced by Clone().
cycamore::EnrichmentFacility::~EnrichmentFacility () [virtual]
Destructor for the EnrichmentFacility class.
Definition at line 26 of file build/cycamore/enrichment_facility.cc.
cycamore::EnrichmentFacility::EnrichmentFacility (cyclus::Context * ctx)
Constructor for the EnrichmentFacility class.
Parameters:
ctx the cyclus context for access to simulation-wide parameters
virtual cycamore::EnrichmentFacility::~EnrichmentFacility () [virtual]
Destructor for the EnrichmentFacility class.
Member Function Documentation
virtual void cycamore::EnrichmentFacility::AcceptMatlTrades (const std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > & responses) [virtual]
The EnrichmentFacility place accepted trade Materials in their Inventory.
void cycamore::EnrichmentFacility::AcceptMatlTrades (const std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > & responses) [virtual]
The EnrichmentFacility place accepted trade Materials in their Inventory.
Definition at line 91 of file build/cycamore/enrichment_facility.cc.
References AddMat_().
void cycamore::EnrichmentFacility::AddMat_ (cyclus::Material::Ptr mat) [private]
adds a material into the natural uranium inventory
Exceptions:
if the material is not the same composition as the in_recipe
void cycamore::EnrichmentFacility::AddMat_ (cyclus::Material::Ptr mat) [private]
adds a material into the natural uranium inventory
Exceptions:
if the material is not the same composition as the in_recipe
Definition at line 186 of file build/cycamore/enrichment_facility.cc.
References in_commod, in_recipe, and inventory.
Referenced by AcceptMatlTrades(), and cycamore::EnrichmentFacilityTest::DoAddMat().
virtual Json::Value cycamore::EnrichmentFacility::annotations () [inline, virtual]
Definition at line 274 of file build/cycamore/enrichment_facility.h.
virtual void cycamore::EnrichmentFacility::Build (cyclus::Agent * parent) [virtual]
perform module-specific tasks when entering the simulation
void cycamore::EnrichmentFacility::Build (cyclus::Agent * parent) [virtual]
perform module-specific tasks when entering the simulation
Definition at line 42 of file build/cycamore/enrichment_facility.cc.
References in_recipe, initial_reserves, inventory, and str().
virtual cyclus::Agent* cycamore::EnrichmentFacility::Clone () [inline, virtual]
Definition at line 233 of file build/cycamore/enrichment_facility.h.
References EnrichmentFacility(), and InitFrom().
double cycamore::EnrichmentFacility::CurrentSwuCapacity () const [inline]
Definition at line 234 of file src/enrichment_facility.h.
References current_swu_capacity.
double cycamore::EnrichmentFacility::CurrentSwuCapacity () const [inline]
Definition at line 457 of file build/cycamore/enrichment_facility.h.
References current_swu_capacity.
Referenced by Enrich_().
cyclus::Material::Ptr cycamore::EnrichmentFacility::Enrich_ (cyclus::Material::Ptr mat, double qty) [private]
cyclus::Material::Ptr cycamore::EnrichmentFacility::Enrich_ (cyclus::Material::Ptr mat, double qty) [private]
Definition at line 226 of file build/cycamore/enrichment_facility.cc.
References cycamore::NatUConverter::convert(), current_swu_capacity, CurrentSwuCapacity(), feed_assay, FeedAssay(), inventory, RecordEnrichment_(), tails, tails_assay, and TailsAssay().
Referenced by cycamore::EnrichmentFacilityTest::DoEnrich(), and GetMatlTrades().
void cycamore::EnrichmentFacility::FeedAssay (double assay) [inline]
Definition at line 219 of file src/enrichment_facility.h.
References feed_assay.
double cycamore::EnrichmentFacility::FeedAssay () const [inline]
Definition at line 221 of file src/enrichment_facility.h.
References feed_assay.
void cycamore::EnrichmentFacility::FeedAssay (double assay) [inline]
Definition at line 442 of file build/cycamore/enrichment_facility.h.
References feed_assay.
Referenced by cycamore::EnrichmentFacilityTest::SetUpSource(), and cycamore::TEST_F().
double cycamore::EnrichmentFacility::FeedAssay () const [inline]
Definition at line 444 of file build/cycamore/enrichment_facility.h.
References feed_assay.
Referenced by Enrich_(), and str().
virtual std::set<cyclus::BidPortfolio<cyclus::Material>::Ptr> cycamore::EnrichmentFacility::GetMatlBids (cyclus::CommodMap< cyclus::Material >::type & commod_requests) [virtual]
Responds to each request for this facility's commodity.
If a given request is more than this facility's inventory or SWU capacity, it will offer its minimum of its capacities.
std::set< cyclus::BidPortfolio< cyclus::Material >::Ptr > cycamore::EnrichmentFacility::GetMatlBids (cyclus::CommodMap< cyclus::Material >::type & commod_requests) [virtual]
Responds to each request for this facility's commodity.
If a given request is more than this facility's inventory or SWU capacity, it will offer its minimum of its capacities.
Definition at line 105 of file build/cycamore/enrichment_facility.cc.
References feed_assay, inventory, Offer_(), out_commod, swu_capacity, tails_assay, and ValidReq().
virtual std::set<cyclus::RequestPortfolio<cyclus::Material>::Ptr> cycamore::EnrichmentFacility::GetMatlRequests () [virtual]
The EnrichmentFacility request Materials of its given commodity.
std::set< cyclus::RequestPortfolio< cyclus::Material >::Ptr > cycamore::EnrichmentFacility::GetMatlRequests () [virtual]
The EnrichmentFacility request Materials of its given commodity.
Definition at line 72 of file build/cycamore/enrichment_facility.cc.
References in_commod, and Request_().
virtual void cycamore::EnrichmentFacility::GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > & trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > & responses) [virtual]
respond to each trade with a material enriched to the appropriate level given this facility's inventory
Parameters:
trades all trades in which this trader is the supplier
responses a container to populate with responses to each trade
void cycamore::EnrichmentFacility::GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > & trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > & responses) [virtual]
respond to each trade with a material enriched to the appropriate level given this facility's inventory
Parameters:
trades all trades in which this trader is the supplier
responses a container to populate with responses to each trade
Definition at line 159 of file build/cycamore/enrichment_facility.cc.
References current_swu_capacity, Enrich_(), and out_commod.
void cycamore::EnrichmentFacility::in_commodity (std::string in_com) [inline]
Definition at line 196 of file src/enrichment_facility.h.
References in_commod.
std::string cycamore::EnrichmentFacility::in_commodity () const [inline]
Definition at line 198 of file src/enrichment_facility.h.
References in_commod.
void cycamore::EnrichmentFacility::in_commodity (std::string in_com) [inline]
Definition at line 419 of file build/cycamore/enrichment_facility.h.
References in_commod.
Referenced by cycamore::EnrichmentFacilityTest::SetUpSource(), and cycamore::TEST_F().
std::string cycamore::EnrichmentFacility::in_commodity () const [inline]
Definition at line 421 of file build/cycamore/enrichment_facility.h.
References in_commod.
Referenced by str().
virtual void cycamore::EnrichmentFacility::InfileToDb (cyclus::InfileTree * tree, cyclus::DbInit di) [inline, virtual]
Definition at line 165 of file build/cycamore/enrichment_facility.h.
References current_swu_capacity, feed_assay, in_commod, in_recipe, initial_reserves, max_inv_size, out_commod, swu_capacity, and tails_assay.
virtual void cycamore::EnrichmentFacility::InitFrom (cycamore::EnrichmentFacility * m) [inline, virtual]
Definition at line 132 of file build/cycamore/enrichment_facility.h.
References current_swu_capacity, feed_assay, in_commod, in_recipe, initial_reserves, inventory, max_inv_size, out_commod, swu_capacity, tails, and tails_assay.
Referenced by Clone(), and InitFrom().
virtual void cycamore::EnrichmentFacility::InitFrom (cyclus::QueryableBackend * b) [inline, virtual]
Definition at line 148 of file build/cycamore/enrichment_facility.h.
References current_swu_capacity, feed_assay, in_commod, in_recipe, InitFrom(), initial_reserves, inventory, max_inv_size, out_commod, swu_capacity, tails, and tails_assay.
void cycamore::EnrichmentFacility::InitialReserves (double qty) [inline]
this facility's initial conditions
Definition at line 237 of file src/enrichment_facility.h.
References initial_reserves.
double cycamore::EnrichmentFacility::InitialReserves () const [inline]
Definition at line 238 of file src/enrichment_facility.h.
References initial_reserves.
void cycamore::EnrichmentFacility::InitialReserves (double qty) [inline]
this facility's initial conditions
Definition at line 460 of file build/cycamore/enrichment_facility.h.
References initial_reserves.
Referenced by cycamore::EnrichmentFacilityTest::SetUpSource(), and cycamore::TEST_F().
double cycamore::EnrichmentFacility::InitialReserves () const [inline]
Definition at line 461 of file build/cycamore/enrichment_facility.h.
References initial_reserves.
virtual void cycamore::EnrichmentFacility::InitInv (cyclus::Inventories & inv) [inline, virtual]
Definition at line 329 of file build/cycamore/enrichment_facility.h.
References inventory, and tails.
void cycamore::EnrichmentFacility::InRecipe (std::string in_rec) [inline]
Definition at line 206 of file src/enrichment_facility.h.
References in_recipe.
std::string cycamore::EnrichmentFacility::InRecipe () const [inline]
Definition at line 208 of file src/enrichment_facility.h.
References in_recipe.
void cycamore::EnrichmentFacility::InRecipe (std::string in_rec) [inline]
Definition at line 429 of file build/cycamore/enrichment_facility.h.
References in_recipe.
Referenced by cycamore::EnrichmentFacilityTest::SetUpSource(), and cycamore::TEST_F().
std::string cycamore::EnrichmentFacility::InRecipe () const [inline]
Definition at line 431 of file build/cycamore/enrichment_facility.h.
References in_recipe.
double cycamore::EnrichmentFacility::InventorySize () const [inline]
Definition at line 217 of file src/enrichment_facility.h.
References inventory.
double cycamore::EnrichmentFacility::InventorySize () const [inline]
Definition at line 440 of file build/cycamore/enrichment_facility.h.
References inventory.
Referenced by Request_(), and cycamore::TEST_F().
double cycamore::EnrichmentFacility::MaxInventorySize () const [inline]
Definition at line 215 of file src/enrichment_facility.h.
References inventory.
double cycamore::EnrichmentFacility::MaxInventorySize () const [inline]
Definition at line 438 of file build/cycamore/enrichment_facility.h.
References inventory.
Referenced by Request_(), and cycamore::TEST_F().
cyclus::Material::Ptr cycamore::EnrichmentFacility::Offer_ (cyclus::Material::Ptr req) [private]
Generates a material offer for a given request.
The response composition will be comprised only of U235 and U238 at their relative ratio in the requested material. The response quantity will be the same as the requested commodity.
Parameters:
req the requested material being responded to
cyclus::Material::Ptr cycamore::EnrichmentFacility::Offer_ (cyclus::Material::Ptr req) [private]
Generates a material offer for a given request.
The response composition will be comprised only of U235 and U238 at their relative ratio in the requested material. The response quantity will be the same as the requested commodity.
Parameters:
req the requested material being responded to
Definition at line 216 of file build/cycamore/enrichment_facility.cc.
Referenced by cycamore::EnrichmentFacilityTest::DoOffer(), and GetMatlBids().
void cycamore::EnrichmentFacility::out_commodity (std::string out_com) [inline]
Definition at line 200 of file src/enrichment_facility.h.
References out_commod.
std::string cycamore::EnrichmentFacility::out_commodity () const [inline]
Definition at line 204 of file src/enrichment_facility.h.
References out_commod.
void cycamore::EnrichmentFacility::out_commodity (std::string out_com) [inline]
Definition at line 423 of file build/cycamore/enrichment_facility.h.
References out_commod.
Referenced by cycamore::EnrichmentFacilityTest::SetUpSource(), and cycamore::TEST_F().
std::string cycamore::EnrichmentFacility::out_commodity () const [inline]
Definition at line 427 of file build/cycamore/enrichment_facility.h.
References out_commod.
Referenced by str().
void cycamore::EnrichmentFacility::RecordEnrichment_ (double natural_u, double swu) [private]
records and enrichment with the cyclus::Recorder
void cycamore::EnrichmentFacility::RecordEnrichment_ (double natural_u, double swu) [private]
records and enrichment with the cyclus::Recorder
Definition at line 298 of file build/cycamore/enrichment_facility.cc.
Referenced by Enrich_().
cyclus::Material::Ptr cycamore::EnrichmentFacility::Request_ () [private]
generates a request for this facility given its current state.
The quantity of the material will be equal to the remaining inventory size.
cyclus::Material::Ptr cycamore::EnrichmentFacility::Request_ () [private]
generates a request for this facility given its current state.
The quantity of the material will be equal to the remaining inventory size.
Definition at line 209 of file build/cycamore/enrichment_facility.cc.
References in_recipe, InventorySize(), and MaxInventorySize().
Referenced by cycamore::EnrichmentFacilityTest::DoRequest(), and GetMatlRequests().
virtual std::string cycamore::EnrichmentFacility::schema () [inline, virtual]
Definition at line 239 of file build/cycamore/enrichment_facility.h.
void cycamore::EnrichmentFacility::SetMaxInventorySize (double size) [inline]
Definition at line 210 of file src/enrichment_facility.h.
References inventory, and max_inv_size.
void cycamore::EnrichmentFacility::SetMaxInventorySize (double size) [inline]
Definition at line 433 of file build/cycamore/enrichment_facility.h.
References inventory, and max_inv_size.
Referenced by cycamore::EnrichmentFacilityTest::SetUpSource().
virtual void cycamore::EnrichmentFacility::Snapshot (cyclus::DbInit di) [inline, virtual]
Definition at line 344 of file build/cycamore/enrichment_facility.h.
References current_swu_capacity, feed_assay, in_commod, in_recipe, initial_reserves, max_inv_size, out_commod, swu_capacity, and tails_assay.
virtual cyclus::Inventories cycamore::EnrichmentFacility::SnapshotInv () [inline, virtual]
Definition at line 335 of file build/cycamore/enrichment_facility.h.
References inventory, and tails.
virtual std::string cycamore::EnrichmentFacility::str () [virtual]
Print information about this agent.
std::string cycamore::EnrichmentFacility::str () [virtual]
Print information about this agent.
Definition at line 29 of file build/cycamore/enrichment_facility.cc.
References FeedAssay(), in_commodity(), out_commodity(), SwuCapacity(), and TailsAssay().
Referenced by Build().
void cycamore::EnrichmentFacility::SwuCapacity (double capacity) [inline]
Definition at line 227 of file src/enrichment_facility.h.
References current_swu_capacity, and swu_capacity.
double cycamore::EnrichmentFacility::SwuCapacity () const [inline]
Definition at line 232 of file src/enrichment_facility.h.
References swu_capacity.
void cycamore::EnrichmentFacility::SwuCapacity (double capacity) [inline]
Definition at line 450 of file build/cycamore/enrichment_facility.h.
References current_swu_capacity, and swu_capacity.
Referenced by cycamore::EnrichmentFacilityTest::SetUpSource(), and cycamore::TEST_F().
double cycamore::EnrichmentFacility::SwuCapacity () const [inline]
Definition at line 455 of file build/cycamore/enrichment_facility.h.
References swu_capacity.
Referenced by str(), and Tick().
const cyclus::toolkit::ResourceBuff& cycamore::EnrichmentFacility::Tails () const [inline]
Definition at line 240 of file src/enrichment_facility.h.
References tails.
const cyclus::toolkit::ResourceBuff& cycamore::EnrichmentFacility::Tails () const [inline]
Definition at line 463 of file build/cycamore/enrichment_facility.h.
References tails.
void cycamore::EnrichmentFacility::TailsAssay (double assay) [inline]
Definition at line 223 of file src/enrichment_facility.h.
References tails_assay.
double cycamore::EnrichmentFacility::TailsAssay () const [inline]
Definition at line 225 of file src/enrichment_facility.h.
References tails_assay.
void cycamore::EnrichmentFacility::TailsAssay (double assay) [inline]
Definition at line 446 of file build/cycamore/enrichment_facility.h.
References tails_assay.
Referenced by cycamore::EnrichmentFacilityTest::SetUpSource(), and cycamore::TEST_F().
double cycamore::EnrichmentFacility::TailsAssay () const [inline]
Definition at line 448 of file build/cycamore/enrichment_facility.h.
References tails_assay.
Referenced by Enrich_(), str(), and ValidReq().
virtual void cycamore::EnrichmentFacility::Tick () [virtual]
Each facility is prompted to do its beginning-of-time-step stuff at the tick of the timer.
Parameters:
time is the time to perform the tick
void cycamore::EnrichmentFacility::Tick () [virtual]
Each facility is prompted to do its beginning-of-time-step stuff at the tick of the timer.
Parameters:
time is the time to perform the tick
Definition at line 58 of file build/cycamore/enrichment_facility.cc.
References current_swu_capacity, and SwuCapacity().
virtual void cycamore::EnrichmentFacility::Tock () [virtual]
Each facility is prompted to its end-of-time-step stuff on the tock of the timer.
Parameters:
time is the time to perform the tock
void cycamore::EnrichmentFacility::Tock () [virtual]
Each facility is prompted to its end-of-time-step stuff on the tock of the timer.
Parameters:
time is the time to perform the tock
Definition at line 65 of file build/cycamore/enrichment_facility.cc.
bool cycamore::EnrichmentFacility::ValidReq (const cyclus::Material::Ptr mat)
Determines if a particular material is a valid request to respond to.
Valid requests must contain U235 and U238 and must have a relative U235-to-U238 ratio less than this facility's tails_assay().
Returns:
true if the above description is met by the material
bool cycamore::EnrichmentFacility::ValidReq (const cyclus::Material::Ptr mat)
Determines if a particular material is a valid request to respond to.
Valid requests must contain U235 and U238 and must have a relative U235-to-U238 ratio less than this facility's tails_assay().
Returns:
true if the above description is met by the material
Definition at line 151 of file build/cycamore/enrichment_facility.cc.
References TailsAssay().
Referenced by GetMatlBids().
Friends And Related Function Documentation
EnrichmentFacilityTest [friend]
Definition at line 519 of file build/cycamore/enrichment_facility.h.
Member Data Documentation
double cycamore::EnrichmentFacility::current_swu_capacity [private]
Definition at line 510 of file build/cycamore/enrichment_facility.h.
Referenced by CurrentSwuCapacity(), Enrich_(), GetMatlTrades(), InfileToDb(), InitFrom(), Snapshot(), SwuCapacity(), and Tick().
double cycamore::EnrichmentFacility::feed_assay [private]
Definition at line 513 of file build/cycamore/enrichment_facility.h.
Referenced by Enrich_(), FeedAssay(), GetMatlBids(), InfileToDb(), InitFrom(), and Snapshot().
std::string cycamore::EnrichmentFacility::in_commod [private]
Definition at line 489 of file build/cycamore/enrichment_facility.h.
Referenced by AddMat_(), GetMatlRequests(), in_commodity(), InfileToDb(), InitFrom(), and Snapshot().
std::string cycamore::EnrichmentFacility::in_recipe [private]
Definition at line 495 of file build/cycamore/enrichment_facility.h.
Referenced by AddMat_(), Build(), InfileToDb(), InitFrom(), InRecipe(), Request_(), and Snapshot().
double cycamore::EnrichmentFacility::initial_reserves [private]
Definition at line 508 of file build/cycamore/enrichment_facility.h.
Referenced by Build(), InfileToDb(), InitFrom(), InitialReserves(), and Snapshot().
cyclus::toolkit::ResourceBuff cycamore::EnrichmentFacility::inventory [private]
Definition at line 515 of file build/cycamore/enrichment_facility.h.
Referenced by AddMat_(), Build(), Enrich_(), GetMatlBids(), InitFrom(), InitInv(), InventorySize(), MaxInventorySize(), SetMaxInventorySize(), and SnapshotInv().
double cycamore::EnrichmentFacility::max_inv_size [private]
Definition at line 505 of file build/cycamore/enrichment_facility.h.
Referenced by InfileToDb(), InitFrom(), SetMaxInventorySize(), and Snapshot().
std::string cycamore::EnrichmentFacility::out_commod [private]
Definition at line 492 of file build/cycamore/enrichment_facility.h.
Referenced by GetMatlBids(), GetMatlTrades(), InfileToDb(), InitFrom(), out_commodity(), and Snapshot().
double cycamore::EnrichmentFacility::swu_capacity [private]
Definition at line 502 of file build/cycamore/enrichment_facility.h.
Referenced by GetMatlBids(), InfileToDb(), InitFrom(), Snapshot(), and SwuCapacity().
cyclus::toolkit::ResourceBuff cycamore::EnrichmentFacility::tails [private]
Definition at line 517 of file build/cycamore/enrichment_facility.h.
Referenced by Enrich_(), InitFrom(), InitInv(), SnapshotInv(), and Tails().
double cycamore::EnrichmentFacility::tails_assay [private]
Definition at line 499 of file build/cycamore/enrichment_facility.h.
Referenced by Enrich_(), GetMatlBids(), InfileToDb(), InitFrom(), Snapshot(), and TailsAssay().
The documentation for this class was generated from the following files:
build/cycamore/enrichment_facility.h
src/enrichment_facility.h
build/cycamore/enrichment_facility.cc
src/enrichment_facility.cc