CYCAMORE: cycamore::TopupConverter Class Reference
cycamore::TopupConverter Class Reference
Public Member Functions
virtual double convert (cyclus::Material::Ptr m, cyclus::Arc const *a=NULL, cyclus::ExchangeTranslationContext< cyclus::Material > const *ctx=NULL) const
virtual double convert (cyclus::Material::Ptr m, cyclus::Arc const *a=NULL, cyclus::ExchangeTranslationContext< cyclus::Material > const *ctx=NULL) const
virtual double convert (cyclus::Material::Ptr m, cyclus::Arc const *a=NULL, cyclus::ExchangeTranslationContext< cyclus::Material > const *ctx=NULL) const
TopupConverter (Composition::Ptr c_fill, Composition::Ptr c_fiss, Composition::Ptr c_topup, std::string spectrum)
TopupConverter (Composition::Ptr c_fill, Composition::Ptr c_fiss, Composition::Ptr c_topup, std::string spectrum)
TopupConverter (Composition::Ptr c_fill, Composition::Ptr c_fiss, Composition::Ptr c_topup, std::string spectrum)
virtual ~TopupConverter ()
virtual ~TopupConverter ()
virtual ~TopupConverter ()
Private Attributes
Composition::Ptr c_fill_
Composition::Ptr c_fiss_
Composition::Ptr c_topup_
std::string spec_
double w_fill_
double w_fiss_
double w_topup_
Detailed Description
Definition at line 92 of file _tmp_build/cycamore/fuel_fab.cc.
Constructor & Destructor Documentation
cycamore::TopupConverter::TopupConverter (Composition::Ptr c_fill, Composition::Ptr c_fiss, Composition::Ptr c_topup, std::string spectrum) inline
Definition at line 94 of file _tmp_build/cycamore/fuel_fab.cc.
References cycamore::CosiWeight(), w_fill_, w_fiss_, and w_topup_.
virtual cycamore::TopupConverter::~TopupConverter () inline virtual
Definition at line 102 of file _tmp_build/cycamore/fuel_fab.cc.
cycamore::TopupConverter::TopupConverter (Composition::Ptr c_fill, Composition::Ptr c_fiss, Composition::Ptr c_topup, std::string spectrum) inline
Definition at line 94 of file build/cycamore/fuel_fab.cc.
References cycamore::CosiWeight(), w_fill_, w_fiss_, and w_topup_.
virtual cycamore::TopupConverter::~TopupConverter () inline virtual
Definition at line 102 of file build/cycamore/fuel_fab.cc.
cycamore::TopupConverter::TopupConverter (Composition::Ptr c_fill, Composition::Ptr c_fiss, Composition::Ptr c_topup, std::string spectrum) inline
Definition at line 93 of file src/fuel_fab.cc.
References cycamore::CosiWeight(), w_fill_, w_fiss_, and w_topup_.
virtual cycamore::TopupConverter::~TopupConverter () inline virtual
Definition at line 101 of file src/fuel_fab.cc.
Member Function Documentation
virtual double cycamore::TopupConverter::convert (cyclus::Material::Ptr m, cyclus::Arc const * a = NULL, cyclus::ExchangeTranslationContext< cyclus::Material > const * ctx = NULL) const inline virtual
Definition at line 103 of file src/fuel_fab.cc.
References cycamore::AtomToMassFrac(), c_fiss_, c_topup_, cycamore::CosiWeight(), cycamore::HighFrac(), spec_, cycamore::ValidWeights(), w_fill_, w_fiss_, and w_topup_.
virtual double cycamore::TopupConverter::convert (cyclus::Material::Ptr m, cyclus::Arc const * a = NULL, cyclus::ExchangeTranslationContext< cyclus::Material > const * ctx = NULL) const inline virtual
Definition at line 104 of file _tmp_build/cycamore/fuel_fab.cc.
References cycamore::AtomToMassFrac(), c_fiss_, c_topup_, cycamore::CosiWeight(), cycamore::HighFrac(), spec_, cycamore::ValidWeights(), w_fill_, w_fiss_, and w_topup_.
virtual double cycamore::TopupConverter::convert (cyclus::Material::Ptr m, cyclus::Arc const * a = NULL, cyclus::ExchangeTranslationContext< cyclus::Material > const * ctx = NULL) const inline virtual
Definition at line 104 of file build/cycamore/fuel_fab.cc.
References cycamore::AtomToMassFrac(), c_fiss_, c_topup_, cycamore::CosiWeight(), cycamore::HighFrac(), spec_, cycamore::ValidWeights(), w_fill_, w_fiss_, and w_topup_.
Member Data Documentation
Composition::Ptr cycamore::TopupConverter::c_fill_ private
Definition at line 126 of file _tmp_build/cycamore/fuel_fab.cc.
Composition::Ptr cycamore::TopupConverter::c_fiss_ private
Definition at line 125 of file _tmp_build/cycamore/fuel_fab.cc.
Referenced by convert().
Composition::Ptr cycamore::TopupConverter::c_topup_ private
Definition at line 127 of file _tmp_build/cycamore/fuel_fab.cc.
Referenced by convert().
std::string cycamore::TopupConverter::spec_ private
Definition at line 121 of file _tmp_build/cycamore/fuel_fab.cc.
Referenced by convert().
double cycamore::TopupConverter::w_fill_ private
Definition at line 124 of file _tmp_build/cycamore/fuel_fab.cc.
Referenced by convert(), and TopupConverter().
double cycamore::TopupConverter::w_fiss_ private
Definition at line 122 of file _tmp_build/cycamore/fuel_fab.cc.
Referenced by convert(), and TopupConverter().
double cycamore::TopupConverter::w_topup_ private
Definition at line 123 of file _tmp_build/cycamore/fuel_fab.cc.
Referenced by convert(), and TopupConverter().
The documentation for this class was generated from the following file:
_tmp_build/cycamore/fuel_fab.cc