CYCAMORE: cycamore::BatchReactor Class Reference
cycamore::BatchReactor Class Reference
#include <batch_reactor.h>
Classes
struct InitCond
a struct for initial conditions
Public Types
enum Phase {
INITIAL, PROCESS, WAITING, INITIAL,
PROCESS, WAITING
}
defines all possible phases this facility can be in
enum Phase {
INITIAL, PROCESS, WAITING, INITIAL,
PROCESS, WAITING
}
defines all possible phases this facility can be in
Public Member Functions
virtual void AcceptMatlTrades (const std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > &responses)
The BatchReactor places accepted trade Materials in their Inventory.
virtual void AcceptMatlTrades (const std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > &responses)
The BatchReactor places accepted trade Materials in their Inventory.
virtual Json::Value annotations ()
void batch_size (double size)
the size of a batch
double batch_size ()
void batch_size (double size)
the size of a batch
double batch_size ()
BatchReactor (cyclus::Context *ctx)
BatchReactor (cyclus::Context *ctx)
virtual void Build (cyclus::Agent *parent)
perform module-specific tasks when entering the simulation
virtual void Build (cyclus::Agent *parent)
perform module-specific tasks when entering the simulation
virtual cyclus::Agent * Clone ()
virtual cyclus::Agent * Clone ()
void commod_prefs (const std::map< std::string, double > &prefs)
this facility's preference for input commodities
const std::map< std::string,
double > & commod_prefs () const
void commod_prefs (const std::map< std::string, double > &prefs)
this facility's preference for input commodities
const std::map< std::string,
double > & commod_prefs () const
void crctx (const cyclus::toolkit::CommodityRecipeContext &crctx)
this facility's commodity-recipe context
cyclus::toolkit::CommodityRecipeContext crctx () const
void crctx (const cyclus::toolkit::CommodityRecipeContext &crctx)
this facility's commodity-recipe context
cyclus::toolkit::CommodityRecipeContext crctx () const
int end_time () const
the ending time of the last (current) process
int end_time () const
the ending time of the last (current) process
virtual std::set
< cyclus::BidPortfolio
< cyclus::Material >::Ptr > GetMatlBids (cyclus::CommodMap< cyclus::Material >::type &commod_requests)
Responds to each request for this facility's commodity.
virtual std::set
< cyclus::BidPortfolio
< cyclus::Material >::Ptr > GetMatlBids (cyclus::CommodMap< cyclus::Material >::type &commod_requests)
Responds to each request for this facility's commodity.
virtual std::set
< cyclus::RequestPortfolio
< cyclus::Material >::Ptr > GetMatlRequests ()
The BatchReactor requests Materials of its given commodity.
virtual std::set
< cyclus::RequestPortfolio
< cyclus::Material >::Ptr > GetMatlRequests ()
The BatchReactor requests Materials of its given commodity.
virtual void GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > &trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > &responses)
respond to each trade with a material enriched to the appropriate level given this facility's inventory
virtual void GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > &trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > &responses)
respond to each trade with a material enriched to the appropriate level given this facility's inventory
void ics (const InitCond &ics)
this facility's initial conditions
InitCond ics () const
void ics (const InitCond &ics)
this facility's initial conditions
InitCond ics () const
virtual void InfileToDb (cyclus::InfileTree *qe, cyclus::DbInit di)
virtual void InfileToDb (cyclus::InfileTree *qe, cyclus::DbInit di)
virtual void InitFrom (cyclus::QueryableBackend *b)
void InitFrom (BatchReactor *m)
initialize members from a different agent
virtual void InitFrom (cyclus::QueryableBackend *b)
void InitFrom (BatchReactor *m)
initialize members from a different agent
virtual void InitInv (cyclus::Inventories &invs)
virtual void InitInv (cyclus::Inventories &invs)
void n_batches (int n)
the number of batches in a full reactor
int n_batches () const
void n_batches (int n)
the number of batches in a full reactor
int n_batches () const
int n_core () const
the number of batches currently in the reactor
int n_core () const
the number of batches currently in the reactor
void n_load (int n)
the number of batches in reactor refuel loading/unloading
int n_load () const
void n_load (int n)
the number of batches in reactor refuel loading/unloading
int n_load () const
void n_reserves (int n)
the preferred number of fresh fuel batches to keep in reserve
int n_reserves () const
void n_reserves (int n)
the preferred number of fresh fuel batches to keep in reserve
int n_reserves () const
int order_time () const
the time orders should be taking place for the next refueling
int order_time () const
the time orders should be taking place for the next refueling
void phase (Phase p)
the current phase
Phase phase () const
void phase (Phase p)
the current phase
Phase phase () const
void preorder_time (int t)
the amount of time an order should be placed for new fuel before a process is finished
int preorder_time () const
void preorder_time (int t)
the amount of time an order should be placed for new fuel before a process is finished
int preorder_time () const
void process_time (int t)
the processing time required for a full batch process before refueling
int process_time () const
void process_time (int t)
the processing time required for a full batch process before refueling
int process_time () const
void refuel_time (int t)
the time it takes to refuel
int refuel_time () const
void refuel_time (int t)
the time it takes to refuel
int refuel_time () const
virtual std::string schema ()
virtual std::string schema ()
virtual void Snapshot (cyclus::DbInit di)
virtual void Snapshot (cyclus::DbInit di)
virtual cyclus::Inventories SnapshotInv ()
virtual cyclus::Inventories SnapshotInv ()
void start_time (int t)
the starting time of the last (current) process
int start_time () const
void start_time (int t)
the starting time of the last (current) process
int start_time () const
int StorageCount ()
int StorageCount ()
virtual std::string str ()
Print information about this agent.
virtual std::string str ()
Print information about this agent.
virtual void Tick ()
The Tick function specific to the BatchReactor.
virtual void Tick ()
The Tick function specific to the BatchReactor.
int to_begin_time () const
the beginning time for the next phase, set internally
int to_begin_time () const
the beginning time for the next phase, set internally
virtual void Tock ()
The Tick function specific to the BatchReactor.
virtual void Tock ()
The Tick function specific to the BatchReactor.
virtual ~BatchReactor ()
virtual ~BatchReactor ()
Protected Member Functions
cyclus::BidPortfolio
< cyclus::Material >::Ptr GetBids_ (cyclus::CommodMap< cyclus::Material >::type &commod_requests, std::string commod, cyclus::toolkit::ResourceBuff *buffer)
gets bids for a commodity from a buffer
cyclus::BidPortfolio
< cyclus::Material >::Ptr GetBids_ (cyclus::CommodMap< cyclus::Material >::type &commod_requests, std::string commod, cyclus::toolkit::ResourceBuff *buffer)
gets bids for a commodity from a buffer
virtual void MoveBatchOut_ ()
moves a batch from core_ to storage_
virtual void MoveBatchOut_ ()
moves a batch from core_ to storage_
cyclus::Material::Ptr TradeResponse_ (double qty, cyclus::toolkit::ResourceBuff *buffer)
returns a qty of material from a buffer
cyclus::Material::Ptr TradeResponse_ (double qty, cyclus::toolkit::ResourceBuff *buffer)
returns a qty of material from a buffer
Protected Attributes
cyclus::toolkit::ResourceBuff core_
a cyclus::toolkit::ResourceBuff for material while they are inside the core, with all materials guaranteed to be of batch_size_
std::map< std::string,
cyclus::toolkit::ResourceBuff > storage_
a cyclus::toolkit::ResourceBuff for material once they leave the core.
Private Member Functions
void AddBatches_ (std::string commod, cyclus::Material::Ptr mat)
Add a blob of incoming material to reserves_.
void AddBatches_ (std::string commod, cyclus::Material::Ptr mat)
Add a blob of incoming material to reserves_.
cyclus::RequestPortfolio
< cyclus::Material >::Ptr GetOrder_ (double size)
construct a request portfolio for an order of a given size
cyclus::RequestPortfolio
< cyclus::Material >::Ptr GetOrder_ (double size)
construct a request portfolio for an order of a given size
void MoveBatchIn_ ()
moves a batch from reserves_ to core_
void MoveBatchIn_ ()
moves a batch from reserves_ to core_
void Refuel_ ()
refuels the reactor until it is full or reserves_ is out of batches.
void Refuel_ ()
refuels the reactor until it is full or reserves_ is out of batches.
void SetUpPhaseNames_ ()
adds phase names to phase_names_ map
void SetUpPhaseNames_ ()
adds phase names to phase_names_ map
Private Attributes
double batch_size_
std::map< std::string, double > commod_prefs_
preferences for each input commodity
cyclus::toolkit::CommodityRecipeContext crctx_
InitCond ics_
int n_batches_
int n_load_
int n_reserves_
Phase phase_
std::map< int, std::vector
< std::pair< std::string,
double > > > pref_changes_
int preorder_time_
int process_time_
std::map< int, std::vector
< std::pair< std::string,
std::string > > > recipe_changes_
int refuel_time_
cyclus::toolkit::ResourceBuff reserves_
a cyclus::toolkit::ResourceBuff for material before they enter the core, with all materials guaranteed to be of batch_size_
cyclus::Material::Ptr spillover_
allows only batches to enter reserves_
int start_time_
int to_begin_time_
Static Private Attributes
static std::map< Phase,
std::string > phase_names_
Friends
class BatchReactorTest
Detailed Description
Introduction
The BatchReactor is a facility that agents batch processing. It has three storage areas which hold batches of materials: reserves, core, and storage. Incoming material orders are placed into reserves, from which the core is provided batches during refueling. When a process has been completed, batches are moved from the core into storage. Requests for material are bid upon based on the state of the material in storage.
The Reactor can manage multiple input-output commodity pairs, and keeps track of the pair that each batch belongs to. Batches move through the system independently of their input/output commodity types, but when batches reach the storage area, they are offered as bids dependent on their output commodity type.
Parameters
A BatchReactor has the following tunable parameters: #. batch_size : the size of batches #. n_batches : the number of batches that constitute a full core #. process_time : the number of timesteps a batch process takes #. n_load : the number of batches processed at any given time (i.e., n_load is unloaded and reloaded after a process is finished #. n_reserves : the preferred number of batches in reserve #. preorder_time : the amount of time before a process is finished to order fuel #. refuel_time : the number of timesteps required to reload the core after a process has finished
The BatchReactor also maintains a cyclus::CommodityRecipeContext, which allows it to track incommodity-inrecipe/outcommodity-outrecipe groupings.
Operation
After a BatchReactor enters the simulation, it will begin processing its first batch load on the Tick after its core has been filled.
It will maintain its "processing" state for process_time() time steps, including the timestep on which it began. It will unload n_load() batches from its core on the Tock of that time step. For example, if a reactor begins its process at time 1 and has a process_time equal to 10, it will unload batches on the Tock of time step 10.
Starting at the next time step, the reactor will attempt to refuel itself from whatever batches exist in its reserves container (i.e, already-ordered fuel). Assuming its core buffer has been refueled, it will wait reload_time timesteps. On the tick of the following timestep, the process will begin again. Using the previous example, assume that the refuel_time is equal to two and that the core buffer has been refueled appropriately. The refueling "phase" will begin on time step 11, and will end on the Tock of time step 12. The process will begin again on time step 13 (analogous to its state originally at time step 1).
End of Life
If the current time step is equivalent to the facility's lifetime, the reactor will move all material in its core to its storage containers.
Requests
A BatchReactor will make as many requests as it has possible input commodities. It provides a constraint based on a total request amount determined by its batch_size, n_load, and n_reserves parameters. The n_reserves parameter allows agenters to order fuel in advance of when it is needed. The fuel order size is batch_size * (n_load + n_reserves). These requests are made if the current simulation time is less than or equal to the reactor's current order_time(), which is determined by the ending time of the current process less a look ahead time, the preorder_time().
A special case exists when the reactor first enters the simulation, where it will order as much fuel as is needed to fill its full core.
Bids
A BatchReactor will bid on any request for any of its out_commodities, as long as there is a positive quantity of material in its storage area associated with that output commodity.
Initial Conditions
A BatchReactor can be deployed with any number of batches in its reserve, core, and storage buffers. Recipes and commodities for each of these batch groupings must be specified.
Todo:
add decommissioning behavior if material is still in storage
Warning:
The BatchReactor is considered experimental.
preference time changing is based on *full simulation time*, not relative time
the reactor's commodity context *can not* currently remove resources reliably because of toolkit::ResourceBuff::PopQty()'s implementation. Resource removal from the context requires pointer equality in order to remove material, and PopQty will split resources, making new pointers.
the reactor uses a hackish way to input materials into its reserves. See the AddBatches_ member function.
Introduction
The BatchReactor is a facility that agents batch processing. It has three storage areas which hold batches of materials: reserves, core, and storage. Incoming material orders are placed into reserves, from which the core is provided batches during refueling. When a process has been completed, batches are moved from the core into storage. Requests for material are bid upon based on the state of the material in storage.
The Reactor can manage multiple input-output commodity pairs, and keeps track of the pair that each batch belongs to. Batches move through the system independently of their input/output commodity types, but when batches reach the storage area, they are offered as bids dependent on their output commodity type.
Parameters
A BatchReactor has the following tunable parameters: #. batch_size : the size of batches #. n_batches : the number of batches that constitute a full core #. process_time : the number of timesteps a batch process takes #. n_load : the number of batches processed at any given time (i.e., n_load is unloaded and reloaded after a process is finished #. n_reserves : the preferred number of batches in reserve #. preorder_time : the amount of time before a process is finished to order fuel #. refuel_time : the number of timesteps required to reload the core after a process has finished
The BatchReactor also maintains a cyclus::CommodityRecipeContext, which allows it to track incommodity-inrecipe/outcommodity-outrecipe groupings.
Operation
After a BatchReactor enters the simulation, it will begin processing its first batch load on the Tick after its core has been filled.
It will maintain its "processing" state for process_time() time steps, including the timestep on which it began. It will unload n_load() batches from its core on the Tock of that time step. For example, if a reactor begins its process at time 1 and has a process_time equal to 10, it will unload batches on the Tock of time step 10.
Starting at the next time step, the reactor will attempt to refuel itself from whatever batches exist in its reserves container (i.e, already-ordered fuel). Assuming its core buffer has been refueled, it will wait reload_time timesteps. On the tick of the following timestep, the process will begin again. Using the previous example, assume that the refuel_time is equal to two and that the core buffer has been refueled appropriately. The refueling "phase" will begin on time step 11, and will end on the Tock of time step 12. The process will begin again on time step 13 (analogous to its state originally at time step 1).
End of Life
If the current time step is equivalent to the facility's lifetime, the reactor will move all material in its core to its storage containers.
Requests
A BatchReactor will make as many requests as it has possible input commodities. It provides a constraint based on a total request amount determined by its batch_size, n_load, and n_reserves parameters. The n_reserves parameter allows agenters to order fuel in advance of when it is needed. The fuel order size is batch_size * (n_load + n_reserves). These requests are made if the current simulation time is less than or equal to the reactor's current order_time(), which is determined by the ending time of the current process less a look ahead time, the preorder_time().
A special case exists when the reactor first enters the simulation, where it will order as much fuel as is needed to fill its full core.
Bids
A BatchReactor will bid on any request for any of its out_commodities, as long as there is a positive quantity of material in its storage area associated with that output commodity.
Initial Conditions
A BatchReactor can be deployed with any number of batches in its reserve, core, and storage buffers. Recipes and commodities for each of these batch groupings must be specified.
Todo:
add decommissioning behavior if material is still in storage
Warning:
The BatchReactor is considered experimental.
preference time changing is based on *full simulation time*, not relative time
the reactor's commodity context *can not* currently remove resources reliably because of toolkit::ResourceBuff::PopQty()'s implementation. Resource removal from the context requires pointer equality in order to remove material, and PopQty will split resources, making new pointers.
the reactor uses a hackish way to input materials into its reserves. See the AddBatches_ member function.
Definition at line 113 of file build/cycamore/batch_reactor.h.
Member Enumeration Documentation
enum cycamore::BatchReactor::Phase
defines all possible phases this facility can be in
Enumerator:
INITIAL
The initial phase, after the facility is built but before it is filled.
PROCESS
The processing phase.
WAITING
The waiting phase, while the facility is waiting for fuel between processes.
INITIAL
The initial phase, after the facility is built but before it is filled.
PROCESS
The processing phase.
WAITING
The waiting phase, while the facility is waiting for fuel between processes.
Definition at line 116 of file src/batch_reactor.h.
enum cycamore::BatchReactor::Phase
defines all possible phases this facility can be in
Enumerator:
INITIAL
The initial phase, after the facility is built but before it is filled.
PROCESS
The processing phase.
WAITING
The waiting phase, while the facility is waiting for fuel between processes.
INITIAL
The initial phase, after the facility is built but before it is filled.
PROCESS
The processing phase.
WAITING
The waiting phase, while the facility is waiting for fuel between processes.
Definition at line 118 of file build/cycamore/batch_reactor.h.
Constructor & Destructor Documentation
cycamore::BatchReactor::BatchReactor (cyclus::Context * ctx)
Parameters:
ctx the cyclus context for access to simulation-wide parameters
Definition at line 15 of file build/cycamore/batch_reactor.cc.
References phase_names_, SetUpPhaseNames_(), and spillover_.
Referenced by Clone().
cycamore::BatchReactor::~BatchReactor () [virtual]
Definition at line 36 of file build/cycamore/batch_reactor.cc.
cycamore::BatchReactor::BatchReactor (cyclus::Context * ctx)
Parameters:
ctx the cyclus context for access to simulation-wide parameters
virtual cycamore::BatchReactor::~BatchReactor () [virtual]
Member Function Documentation
virtual void cycamore::BatchReactor::AcceptMatlTrades (const std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > & responses) [virtual]
The BatchReactor places accepted trade Materials in their Inventory.
void cycamore::BatchReactor::AcceptMatlTrades (const std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > & responses) [virtual]
The BatchReactor places accepted trade Materials in their Inventory.
Definition at line 762 of file build/cycamore/batch_reactor.cc.
References AddBatches_().
void cycamore::BatchReactor::AddBatches_ (std::string commod, cyclus::Material::Ptr mat) [private]
Add a blob of incoming material to reserves_.
The last material to join reserves_ is first investigated to see if it is of batch_size_. If not, material from mat is added to it and it is returned to reserves_. If more material remains, chunks of batch_size_ are removed and added to reserves_. The final chunk may be <= batch_size_.
void cycamore::BatchReactor::AddBatches_ (std::string commod, cyclus::Material::Ptr mat) [private]
Add a blob of incoming material to reserves_.
The last material to join reserves_ is first investigated to see if it is of batch_size_. If not, material from mat is added to it and it is returned to reserves_. If more material remains, chunks of batch_size_ are removed and added to reserves_. The final chunk may be <= batch_size_.
Definition at line 946 of file build/cycamore/batch_reactor.cc.
References batch_size(), crctx_, reserves_, and spillover_.
Referenced by AcceptMatlTrades(), and cycamore::BatchReactorTest::TestReserveBatches().
virtual Json::Value cycamore::BatchReactor::annotations () [inline, virtual]
Definition at line 166 of file build/cycamore/batch_reactor.h.
void cycamore::BatchReactor::batch_size (double size) [inline]
the size of a batch
Definition at line 321 of file src/batch_reactor.h.
References batch_size_.
double cycamore::BatchReactor::batch_size () [inline]
Definition at line 324 of file src/batch_reactor.h.
References batch_size_.
void cycamore::BatchReactor::batch_size (double size) [inline]
the size of a batch
Definition at line 340 of file build/cycamore/batch_reactor.h.
References batch_size_.
Referenced by InitFrom(), and cycamore::BatchReactorTest::SetUpSource().
double cycamore::BatchReactor::batch_size () [inline]
Definition at line 343 of file build/cycamore/batch_reactor.h.
References batch_size_.
Referenced by AddBatches_(), Build(), GetMatlRequests(), InitFrom(), and str().
virtual void cycamore::BatchReactor::Build (cyclus::Agent * parent) [virtual]
perform module-specific tasks when entering the simulation
void cycamore::BatchReactor::Build (cyclus::Agent * parent) [virtual]
perform module-specific tasks when entering the simulation
Definition at line 542 of file build/cycamore/batch_reactor.cc.
References batch_size(), core_, cycamore::BatchReactor::InitCond::core_commod, cycamore::BatchReactor::InitCond::core_rec, crctx_, ics_, INITIAL, cycamore::BatchReactor::InitCond::n_core, cycamore::BatchReactor::InitCond::n_reserves, cycamore::BatchReactor::InitCond::n_storage, phase(), reserves_, cycamore::BatchReactor::InitCond::reserves_commod, cycamore::BatchReactor::InitCond::reserves_rec, spillover_, storage_, cycamore::BatchReactor::InitCond::storage_commod, cycamore::BatchReactor::InitCond::storage_rec, and str().
virtual cyclus::Agent* cycamore::BatchReactor::Clone () [virtual]
cyclus::Agent * cycamore::BatchReactor::Clone () [virtual]
Definition at line 489 of file build/cycamore/batch_reactor.cc.
References BatchReactor(), and InitFrom().
void cycamore::BatchReactor::commod_prefs (const std::map< std::string, double > & prefs) [inline]
this facility's preference for input commodities
Definition at line 351 of file src/batch_reactor.h.
References commod_prefs_.
const std::map<std::string, double>& cycamore::BatchReactor::commod_prefs () const [inline]
Definition at line 354 of file src/batch_reactor.h.
References commod_prefs_.
void cycamore::BatchReactor::commod_prefs (const std::map< std::string, double > & prefs) [inline]
this facility's preference for input commodities
Definition at line 370 of file build/cycamore/batch_reactor.h.
References commod_prefs_.
Referenced by InitFrom(), and cycamore::BatchReactorTest::SetUpSource().
const std::map<std::string, double>& cycamore::BatchReactor::commod_prefs () const [inline]
Definition at line 373 of file build/cycamore/batch_reactor.h.
References commod_prefs_.
Referenced by InitFrom().
void cycamore::BatchReactor::crctx (const cyclus::toolkit::CommodityRecipeContext & crctx) [inline]
this facility's commodity-recipe context
Definition at line 329 of file src/batch_reactor.h.
References crctx(), and crctx_.
cyclus::toolkit::CommodityRecipeContext cycamore::BatchReactor::crctx () const [inline]
Definition at line 332 of file src/batch_reactor.h.
References crctx_.
void cycamore::BatchReactor::crctx (const cyclus::toolkit::CommodityRecipeContext & crctx) [inline]
this facility's commodity-recipe context
Definition at line 348 of file build/cycamore/batch_reactor.h.
References crctx(), and crctx_.
Referenced by cycamore::BatchReactorTest::SetUpSource().
cyclus::toolkit::CommodityRecipeContext cycamore::BatchReactor::crctx () const [inline]
Definition at line 351 of file build/cycamore/batch_reactor.h.
References crctx_.
Referenced by crctx().
int cycamore::BatchReactor::end_time () const [inline]
the ending time of the last (current) process
Warning:
the - 1 is to ensure that a 1 period process time that begins on the tick ends on the tock
Definition at line 277 of file src/batch_reactor.h.
References process_time(), and start_time().
int cycamore::BatchReactor::end_time () const [inline]
the ending time of the last (current) process
Warning:
the - 1 is to ensure that a 1 period process time that begins on the tick ends on the tock
Definition at line 296 of file build/cycamore/batch_reactor.h.
References process_time(), and start_time().
Referenced by order_time(), Tick(), and Tock().
cyclus::BidPortfolio<cyclus::Material>::Ptr cycamore::BatchReactor::GetBids_ (cyclus::CommodMap< cyclus::Material >::type & commod_requests, std::string commod, cyclus::toolkit::ResourceBuff * buffer) [protected]
gets bids for a commodity from a buffer
cyclus::BidPortfolio< cyclus::Material >::Ptr cycamore::BatchReactor::GetBids_ (cyclus::CommodMap< cyclus::Material >::type & commod_requests, std::string commod, cyclus::toolkit::ResourceBuff * buffer) [protected]
gets bids for a commodity from a buffer
Definition at line 974 of file build/cycamore/batch_reactor.cc.
Referenced by GetMatlBids().
virtual std::set<cyclus::BidPortfolio<cyclus::Material>::Ptr> cycamore::BatchReactor::GetMatlBids (cyclus::CommodMap< cyclus::Material >::type & commod_requests) [virtual]
Responds to each request for this facility's commodity.
If a given request is more than this facility's inventory or SWU capacity, it will offer its minimum of its capacities.
std::set< cyclus::BidPortfolio< cyclus::Material >::Ptr > cycamore::BatchReactor::GetMatlBids (cyclus::CommodMap< cyclus::Material >::type & commod_requests) [virtual]
Responds to each request for this facility's commodity.
If a given request is more than this facility's inventory or SWU capacity, it will offer its minimum of its capacities.
Definition at line 794 of file build/cycamore/batch_reactor.cc.
References crctx_, GetBids_(), and storage_.
virtual std::set<cyclus::RequestPortfolio<cyclus::Material>::Ptr> cycamore::BatchReactor::GetMatlRequests () [virtual]
The BatchReactor requests Materials of its given commodity.
std::set< cyclus::RequestPortfolio< cyclus::Material >::Ptr > cycamore::BatchReactor::GetMatlRequests () [virtual]
The BatchReactor requests Materials of its given commodity.
Definition at line 708 of file build/cycamore/batch_reactor.cc.
References batch_size(), core_, GetOrder_(), INITIAL, n_batches(), n_load(), n_reserves(), order_time(), phase(), preorder_time(), reserves_, and spillover_.
virtual void cycamore::BatchReactor::GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > & trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > & responses) [virtual]
respond to each trade with a material enriched to the appropriate level given this facility's inventory
Parameters:
trades all trades in which this trader is the supplier
responses a container to populate with responses to each trade
void cycamore::BatchReactor::GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > & trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > & responses) [virtual]
respond to each trade with a material enriched to the appropriate level given this facility's inventory
Parameters:
trades all trades in which this trader is the supplier
responses a container to populate with responses to each trade
Definition at line 816 of file build/cycamore/batch_reactor.cc.
References storage_, and TradeResponse_().
cyclus::RequestPortfolio<cyclus::Material>::Ptr cycamore::BatchReactor::GetOrder_ (double size) [private]
construct a request portfolio for an order of a given size
cyclus::RequestPortfolio< cyclus::Material >::Ptr cycamore::BatchReactor::GetOrder_ (double size) [private]
construct a request portfolio for an order of a given size
Definition at line 912 of file build/cycamore/batch_reactor.cc.
References commod_prefs_, and crctx_.
Referenced by GetMatlRequests().
void cycamore::BatchReactor::ics (const InitCond & ics) [inline]
this facility's initial conditions
Definition at line 337 of file src/batch_reactor.h.
References ics(), and ics_.
InitCond cycamore::BatchReactor::ics () const [inline]
Definition at line 340 of file src/batch_reactor.h.
References ics_.
void cycamore::BatchReactor::ics (const InitCond & ics) [inline]
this facility's initial conditions
Definition at line 356 of file build/cycamore/batch_reactor.h.
References ics(), and ics_.
Referenced by InitFrom(), and cycamore::BatchReactorTest::SetUpSource().
InitCond cycamore::BatchReactor::ics () const [inline]
Definition at line 359 of file build/cycamore/batch_reactor.h.
References ics_.
Referenced by ics(), and InitFrom().
virtual void cycamore::BatchReactor::InfileToDb (cyclus::InfileTree * qe, cyclus::DbInit di) [virtual]
void cycamore::BatchReactor::InfileToDb (cyclus::InfileTree * qe, cyclus::DbInit di) [virtual]
Definition at line 266 of file build/cycamore/batch_reactor.cc.
References crctx_, INITIAL, n_load(), n_reserves(), preorder_time(), and refuel_time().
virtual void cycamore::BatchReactor::InitFrom (cyclus::QueryableBackend * b) [virtual]
void cycamore::BatchReactor::InitFrom (BatchReactor * m)
initialize members from a different agent
void cycamore::BatchReactor::InitFrom (cyclus::QueryableBackend * b) [virtual]
Definition at line 181 of file build/cycamore/batch_reactor.cc.
References cycamore::BatchReactor::InitCond::AddCore(), cycamore::BatchReactor::InitCond::AddReserves(), cycamore::BatchReactor::InitCond::AddStorage(), batch_size_, commod_prefs_, crctx_, ics_, n_batches_, n_load_, n_reserves_, phase_, pref_changes_, preorder_time_, process_time_, recipe_changes_, refuel_time_, start_time_, and to_begin_time_.
Referenced by Clone(), and InitFrom().
void cycamore::BatchReactor::InitFrom (BatchReactor * m)
initialize members from a different agent
Definition at line 496 of file build/cycamore/batch_reactor.cc.
References batch_size(), commod_prefs(), crctx_, ics(), InitFrom(), n_batches(), n_load(), n_reserves(), pref_changes_, preorder_time(), process_time(), recipe_changes_, and refuel_time().
virtual void cycamore::BatchReactor::InitInv (cyclus::Inventories & invs) [virtual]
void cycamore::BatchReactor::InitInv (cyclus::Inventories & invs) [virtual]
Definition at line 456 of file build/cycamore/batch_reactor.cc.
References core_, reserves_, spillover_, and storage_.
void cycamore::BatchReactor::MoveBatchIn_ () [private]
moves a batch from reserves_ to core_
void cycamore::BatchReactor::MoveBatchIn_ () [private]
moves a batch from reserves_ to core_
Definition at line 875 of file build/cycamore/batch_reactor.cc.
References core_, and reserves_.
Referenced by Refuel_().
virtual void cycamore::BatchReactor::MoveBatchOut_ () [protected, virtual]
moves a batch from core_ to storage_
void cycamore::BatchReactor::MoveBatchOut_ () [protected, virtual]
moves a batch from core_ to storage_
Definition at line 887 of file build/cycamore/batch_reactor.cc.
References core_, crctx_, and storage_.
Referenced by Tick(), and Tock().
void cycamore::BatchReactor::n_batches (int n) [inline]
the number of batches in a full reactor
Definition at line 292 of file src/batch_reactor.h.
References n_batches_.
int cycamore::BatchReactor::n_batches () const [inline]
Definition at line 295 of file src/batch_reactor.h.
References n_batches_.
void cycamore::BatchReactor::n_batches (int n) [inline]
the number of batches in a full reactor
Definition at line 311 of file build/cycamore/batch_reactor.h.
References n_batches_.
Referenced by InitFrom(), and cycamore::BatchReactorTest::SetUpSource().
int cycamore::BatchReactor::n_batches () const [inline]
Definition at line 314 of file build/cycamore/batch_reactor.h.
References n_batches_.
Referenced by GetMatlRequests(), InitFrom(), Refuel_(), str(), and Tick().
int cycamore::BatchReactor::n_core () const [inline]
the number of batches currently in the reactor
Definition at line 316 of file src/batch_reactor.h.
References core_.
int cycamore::BatchReactor::n_core () const [inline]
the number of batches currently in the reactor
Definition at line 335 of file build/cycamore/batch_reactor.h.
References core_.
Referenced by Refuel_(), and Tick().
void cycamore::BatchReactor::n_load (int n) [inline]
the number of batches in reactor refuel loading/unloading
Definition at line 300 of file src/batch_reactor.h.
References n_load_.
int cycamore::BatchReactor::n_load () const [inline]
Definition at line 303 of file src/batch_reactor.h.
References n_load_.
void cycamore::BatchReactor::n_load (int n) [inline]
the number of batches in reactor refuel loading/unloading
Definition at line 319 of file build/cycamore/batch_reactor.h.
References n_load_.
Referenced by InitFrom(), and cycamore::BatchReactorTest::SetUpSource().
int cycamore::BatchReactor::n_load () const [inline]
Definition at line 322 of file build/cycamore/batch_reactor.h.
References n_load_.
Referenced by GetMatlRequests(), InfileToDb(), InitFrom(), str(), and Tock().
void cycamore::BatchReactor::n_reserves (int n) [inline]
the preferred number of fresh fuel batches to keep in reserve
Definition at line 308 of file src/batch_reactor.h.
References n_reserves_.
int cycamore::BatchReactor::n_reserves () const [inline]
Definition at line 311 of file src/batch_reactor.h.
References n_reserves_.
void cycamore::BatchReactor::n_reserves (int n) [inline]
the preferred number of fresh fuel batches to keep in reserve
Definition at line 327 of file build/cycamore/batch_reactor.h.
References n_reserves_.
Referenced by InitFrom(), and cycamore::BatchReactorTest::SetUpSource().
int cycamore::BatchReactor::n_reserves () const [inline]
Definition at line 330 of file build/cycamore/batch_reactor.h.
References n_reserves_.
Referenced by GetMatlRequests(), InfileToDb(), InitFrom(), and str().
int cycamore::BatchReactor::order_time () const [inline]
the time orders should be taking place for the next refueling
Definition at line 287 of file src/batch_reactor.h.
References end_time(), and preorder_time().
int cycamore::BatchReactor::order_time () const [inline]
the time orders should be taking place for the next refueling
Definition at line 306 of file build/cycamore/batch_reactor.h.
References end_time(), and preorder_time().
Referenced by GetMatlRequests(), Tick(), and Tock().
void cycamore::BatchReactor::phase (Phase p)
the current phase
Phase cycamore::BatchReactor::phase () const [inline]
Definition at line 346 of file src/batch_reactor.h.
References phase_.
void cycamore::BatchReactor::phase (BatchReactor::Phase p)
the current phase
Definition at line 851 of file build/cycamore/batch_reactor.cc.
References phase_, phase_names_, PROCESS, and start_time().
Phase cycamore::BatchReactor::phase () const [inline]
Definition at line 365 of file build/cycamore/batch_reactor.h.
References phase_.
Referenced by Build(), GetMatlRequests(), Tick(), and Tock().
void cycamore::BatchReactor::preorder_time (int t) [inline]
the amount of time an order should be placed for new fuel before a process is finished
Definition at line 259 of file src/batch_reactor.h.
References preorder_time_.
int cycamore::BatchReactor::preorder_time () const [inline]
Definition at line 262 of file src/batch_reactor.h.
References preorder_time_.
void cycamore::BatchReactor::preorder_time (int t) [inline]
the amount of time an order should be placed for new fuel before a process is finished
Definition at line 278 of file build/cycamore/batch_reactor.h.
References preorder_time_.
Referenced by InitFrom(), and cycamore::BatchReactorTest::SetUpSource().
int cycamore::BatchReactor::preorder_time () const [inline]
Definition at line 281 of file build/cycamore/batch_reactor.h.
References preorder_time_.
Referenced by GetMatlRequests(), InfileToDb(), InitFrom(), order_time(), and str().
void cycamore::BatchReactor::process_time (int t) [inline]
the processing time required for a full batch process before refueling
Definition at line 242 of file src/batch_reactor.h.
References process_time_.
int cycamore::BatchReactor::process_time () const [inline]
Definition at line 245 of file src/batch_reactor.h.
References process_time_.
void cycamore::BatchReactor::process_time (int t) [inline]
the processing time required for a full batch process before refueling
Definition at line 261 of file build/cycamore/batch_reactor.h.
References process_time_.
Referenced by InitFrom(), and cycamore::BatchReactorTest::SetUpSource().
int cycamore::BatchReactor::process_time () const [inline]
Definition at line 264 of file build/cycamore/batch_reactor.h.
References process_time_.
Referenced by end_time(), InitFrom(), and str().
void cycamore::BatchReactor::Refuel_ () [private]
refuels the reactor until it is full or reserves_ is out of batches.
If the core is full after refueling, the Phase is set to PROCESS.
void cycamore::BatchReactor::Refuel_ () [private]
refuels the reactor until it is full or reserves_ is out of batches.
If the core is full after refueling, the Phase is set to PROCESS.
Definition at line 865 of file build/cycamore/batch_reactor.cc.
References MoveBatchIn_(), n_batches(), n_core(), process_time_, refuel_time_, reserves_, start_time_, and to_begin_time_.
Referenced by Tock().
void cycamore::BatchReactor::refuel_time (int t) [inline]
the time it takes to refuel
Definition at line 250 of file src/batch_reactor.h.
References refuel_time_.
int cycamore::BatchReactor::refuel_time () const [inline]
Definition at line 253 of file src/batch_reactor.h.
References refuel_time_.
void cycamore::BatchReactor::refuel_time (int t) [inline]
the time it takes to refuel
Definition at line 269 of file build/cycamore/batch_reactor.h.
References refuel_time_.
Referenced by InitFrom(), and cycamore::BatchReactorTest::SetUpSource().
int cycamore::BatchReactor::refuel_time () const [inline]
Definition at line 272 of file build/cycamore/batch_reactor.h.
References refuel_time_.
Referenced by InfileToDb(), InitFrom(), and str().
virtual std::string cycamore::BatchReactor::schema () [virtual]
std::string cycamore::BatchReactor::schema () [virtual]
Definition at line 39 of file build/cycamore/batch_reactor.cc.
References crctx_.
void cycamore::BatchReactor::SetUpPhaseNames_ () [private]
adds phase names to phase_names_ map
void cycamore::BatchReactor::SetUpPhaseNames_ () [private]
adds phase names to phase_names_ map
Definition at line 1039 of file build/cycamore/batch_reactor.cc.
References INITIAL, phase_names_, PROCESS, and WAITING.
Referenced by BatchReactor().
virtual void cycamore::BatchReactor::Snapshot (cyclus::DbInit di) [virtual]
void cycamore::BatchReactor::Snapshot (cyclus::DbInit di) [virtual]
Definition at line 369 of file build/cycamore/batch_reactor.cc.
References batch_size_, commod_prefs_, cycamore::BatchReactor::InitCond::core_commod, cycamore::BatchReactor::InitCond::core_rec, crctx_, ics_, n_batches_, cycamore::BatchReactor::InitCond::n_core, n_load_, cycamore::BatchReactor::InitCond::n_reserves, n_reserves_, cycamore::BatchReactor::InitCond::n_storage, phase_, pref_changes_, preorder_time_, process_time_, recipe_changes_, refuel_time_, cycamore::BatchReactor::InitCond::reserves_commod, cycamore::BatchReactor::InitCond::reserves_rec, start_time_, cycamore::BatchReactor::InitCond::storage_commod, cycamore::BatchReactor::InitCond::storage_rec, and to_begin_time_.
virtual cyclus::Inventories cycamore::BatchReactor::SnapshotInv () [virtual]
cyclus::Inventories cycamore::BatchReactor::SnapshotInv () [virtual]
Definition at line 470 of file build/cycamore/batch_reactor.cc.
References core_, reserves_, spillover_, and storage_.
void cycamore::BatchReactor::start_time (int t) [inline]
the starting time of the last (current) process
Definition at line 267 of file src/batch_reactor.h.
References start_time_.
int cycamore::BatchReactor::start_time () const [inline]
Definition at line 270 of file src/batch_reactor.h.
References start_time_.
void cycamore::BatchReactor::start_time (int t) [inline]
the starting time of the last (current) process
Definition at line 286 of file build/cycamore/batch_reactor.h.
References start_time_.
int cycamore::BatchReactor::start_time () const [inline]
Definition at line 289 of file build/cycamore/batch_reactor.h.
References start_time_.
Referenced by end_time(), and phase().
int cycamore::BatchReactor::StorageCount ()
Returns:
the total number of batches in storage
int cycamore::BatchReactor::StorageCount ()
Returns:
the total number of batches in storage
Definition at line 841 of file build/cycamore/batch_reactor.cc.
References storage_.
Referenced by Tick(), and Tock().
virtual std::string cycamore::BatchReactor::str () [virtual]
Print information about this agent.
std::string cycamore::BatchReactor::str () [virtual]
Print information about this agent.
Definition at line 526 of file build/cycamore/batch_reactor.cc.
References batch_size(), n_batches(), n_load(), n_reserves(), preorder_time(), process_time(), and refuel_time().
Referenced by Build().
virtual void cycamore::BatchReactor::Tick () [virtual]
The Tick function specific to the BatchReactor.
Parameters:
time the time of the tick
void cycamore::BatchReactor::Tick () [virtual]
The Tick function specific to the BatchReactor.
Parameters:
time the time of the tick
Definition at line 581 of file build/cycamore/batch_reactor.cc.
References commod_prefs_, core_, crctx_, end_time(), INITIAL, MoveBatchOut_(), n_batches(), n_core(), order_time(), phase(), phase_, phase_names_, pref_changes_, PROCESS, recipe_changes_, reserves_, spillover_, start_time_, StorageCount(), to_begin_time(), and WAITING.
int cycamore::BatchReactor::to_begin_time () const [inline]
the beginning time for the next phase, set internally
Definition at line 282 of file src/batch_reactor.h.
References to_begin_time_.
int cycamore::BatchReactor::to_begin_time () const [inline]
the beginning time for the next phase, set internally
Definition at line 301 of file build/cycamore/batch_reactor.h.
References to_begin_time_.
Referenced by Tick().
virtual void cycamore::BatchReactor::Tock () [virtual]
The Tick function specific to the BatchReactor.
Parameters:
time the time of the tock
void cycamore::BatchReactor::Tock () [virtual]
The Tick function specific to the BatchReactor.
Parameters:
time the time of the tock
Definition at line 660 of file build/cycamore/batch_reactor.cc.
References core_, end_time(), MoveBatchOut_(), n_load(), order_time(), phase(), phase_, phase_names_, PROCESS, Refuel_(), reserves_, spillover_, start_time_, StorageCount(), and WAITING.
cyclus::Material::Ptr cycamore::BatchReactor::TradeResponse_ (double qty, cyclus::toolkit::ResourceBuff * buffer) [protected]
returns a qty of material from a buffer
cyclus::Material::Ptr cycamore::BatchReactor::TradeResponse_ (double qty, cyclus::toolkit::ResourceBuff * buffer) [protected]
returns a qty of material from a buffer
Definition at line 1014 of file build/cycamore/batch_reactor.cc.
References crctx_.
Referenced by GetMatlTrades().
Friends And Related Function Documentation
BatchReactorTest [friend]
Definition at line 458 of file build/cycamore/batch_reactor.h.
Member Data Documentation
double cycamore::BatchReactor::batch_size_ [private]
Definition at line 432 of file build/cycamore/batch_reactor.h.
Referenced by batch_size(), InitFrom(), and Snapshot().
std::map< std::string, double > cycamore::BatchReactor::commod_prefs_ [private]
preferences for each input commodity
Definition at line 445 of file build/cycamore/batch_reactor.h.
Referenced by commod_prefs(), GetOrder_(), InitFrom(), Snapshot(), and Tick().
cyclus::toolkit::ResourceBuff cycamore::BatchReactor::core_ [protected]
a cyclus::toolkit::ResourceBuff for material while they are inside the core, with all materials guaranteed to be of batch_size_
Definition at line 393 of file build/cycamore/batch_reactor.h.
Referenced by Build(), GetMatlRequests(), InitInv(), MoveBatchIn_(), MoveBatchOut_(), n_core(), SnapshotInv(), Tick(), and Tock().
cyclus::toolkit::CommodityRecipeContext cycamore::BatchReactor::crctx_ [private]
Definition at line 437 of file build/cycamore/batch_reactor.h.
Referenced by AddBatches_(), Build(), crctx(), GetMatlBids(), GetOrder_(), InfileToDb(), InitFrom(), MoveBatchOut_(), schema(), Snapshot(), cycamore::BatchReactorTest::TestReserveBatches(), Tick(), and TradeResponse_().
InitCond cycamore::BatchReactor::ics_ [private]
Definition at line 435 of file build/cycamore/batch_reactor.h.
Referenced by Build(), ics(), InitFrom(), and Snapshot().
int cycamore::BatchReactor::n_batches_ [private]
Definition at line 429 of file build/cycamore/batch_reactor.h.
Referenced by InitFrom(), n_batches(), and Snapshot().
int cycamore::BatchReactor::n_load_ [private]
Definition at line 430 of file build/cycamore/batch_reactor.h.
Referenced by InitFrom(), n_load(), and Snapshot().
int cycamore::BatchReactor::n_reserves_ [private]
Definition at line 431 of file build/cycamore/batch_reactor.h.
Referenced by InitFrom(), n_reserves(), and Snapshot().
Phase cycamore::BatchReactor::phase_ [private]
Definition at line 433 of file build/cycamore/batch_reactor.h.
Referenced by InitFrom(), phase(), Snapshot(), Tick(), and Tock().
static std::map< Phase, std::string > cycamore::BatchReactor::phase_names_ [static, private]
Initial value:
    std::map<Phase, std::string>()
Definition at line 423 of file build/cycamore/batch_reactor.h.
Referenced by BatchReactor(), phase(), SetUpPhaseNames_(), Tick(), and Tock().
std::map< int, std::vector< std::pair< std::string, double > > > cycamore::BatchReactor::pref_changes_ [private]
Warning:
as is, the int key is **simulation time**, i.e., context()->time == key. This should be fixed for future use!
Definition at line 449 of file build/cycamore/batch_reactor.h.
Referenced by InitFrom(), cycamore::BatchReactorTest::SetUpSource(), Snapshot(), and Tick().
int cycamore::BatchReactor::preorder_time_ [private]
Definition at line 425 of file build/cycamore/batch_reactor.h.
Referenced by InitFrom(), preorder_time(), and Snapshot().
int cycamore::BatchReactor::process_time_ [private]
Definition at line 424 of file build/cycamore/batch_reactor.h.
Referenced by InitFrom(), process_time(), Refuel_(), and Snapshot().
std::map< int, std::vector< std::pair< std::string, std::string > > > cycamore::BatchReactor::recipe_changes_ [private]
Warning:
as is, the int key is **simulation time**, i.e., context()->time == key. This should be fixed for future use!
Definition at line 442 of file build/cycamore/batch_reactor.h.
Referenced by InitFrom(), cycamore::BatchReactorTest::SetUpSource(), Snapshot(), and Tick().
int cycamore::BatchReactor::refuel_time_ [private]
Definition at line 426 of file build/cycamore/batch_reactor.h.
Referenced by InitFrom(), Refuel_(), refuel_time(), and Snapshot().
cyclus::toolkit::ResourceBuff cycamore::BatchReactor::reserves_ [private]
a cyclus::toolkit::ResourceBuff for material before they enter the core, with all materials guaranteed to be of batch_size_
Definition at line 456 of file build/cycamore/batch_reactor.h.
Referenced by AddBatches_(), Build(), GetMatlRequests(), InitInv(), MoveBatchIn_(), Refuel_(), SnapshotInv(), cycamore::BatchReactorTest::TestReserveBatches(), Tick(), and Tock().
cyclus::Material::Ptr cycamore::BatchReactor::spillover_ [private]
allows only batches to enter reserves_
Definition at line 452 of file build/cycamore/batch_reactor.h.
Referenced by AddBatches_(), BatchReactor(), Build(), GetMatlRequests(), InitInv(), SnapshotInv(), cycamore::BatchReactorTest::TestReserveBatches(), Tick(), and Tock().
int cycamore::BatchReactor::start_time_ [private]
Definition at line 427 of file build/cycamore/batch_reactor.h.
Referenced by InitFrom(), Refuel_(), Snapshot(), start_time(), Tick(), and Tock().
std::map< std::string, cyclus::toolkit::ResourceBuff > cycamore::BatchReactor::storage_ [protected]
a cyclus::toolkit::ResourceBuff for material once they leave the core.
there is one storage for each outcommodity
Warning:
no guarantee can be made to the size of each item in storage_, as requests can be met that are larger or smaller than batch_size_
Definition at line 399 of file build/cycamore/batch_reactor.h.
Referenced by Build(), GetMatlBids(), GetMatlTrades(), InitInv(), MoveBatchOut_(), SnapshotInv(), and StorageCount().
int cycamore::BatchReactor::to_begin_time_ [private]
Definition at line 428 of file build/cycamore/batch_reactor.h.
Referenced by InitFrom(), Refuel_(), Snapshot(), and to_begin_time().
The documentation for this class was generated from the following files:
build/cycamore/batch_reactor.h
src/batch_reactor.h
build/cycamore/batch_reactor.cc
src/batch_reactor.cc