CYCAMORE: cycamore::GrowthRegion Class Reference
cycamore::GrowthRegion Class Reference
This region determines if there is a need to meet a certain capacity (as defined via input) at each time step.
#include <growth_region.h>
Public Member Functions
void AddCommodityDemand (cyclus::toolkit::Commodity commod)
add a demand for a commodity on which this region request that facilities be built
void AddCommodityDemand (cyclus::toolkit::Commodity commod)
add a demand for a commodity on which this region request that facilities be built
virtual Json::Value annotations ()
virtual void Build (cyclus::Agent *parent)
perform module-specific tasks when entering the simulation
virtual void Build (cyclus::Agent *parent)
perform module-specific tasks when entering the simulation
virtual void BuildNotify (Agent *m)
register a new child
virtual void BuildNotify (Agent *m)
register a new child
virtual cyclus::Agent * Clone ()
virtual void DecomNotify (Agent *m)
unregister a child
virtual void DecomNotify (Agent *m)
unregister a child
virtual void EnterNotify ()
enter the simulation and register any children present
virtual void EnterNotify ()
enter the simulation and register any children present
GrowthRegion (cyclus::Context *ctx)
The default constructor for the GrowthRegion.
GrowthRegion (cyclus::Context *ctx)
The default constructor for the GrowthRegion.
virtual void InfileToDb (cyclus::InfileTree *tree, cyclus::DbInit di)
virtual void InitFrom (cycamore::GrowthRegion *m)
virtual void InitFrom (cyclus::QueryableBackend *b)
virtual void InitInv (cyclus::Inventories &inv)
virtual std::string schema ()
cyclus::toolkit::SupplyDemandManager * sdmanager ()
cyclus::toolkit::SupplyDemandManager * sdmanager ()
virtual void Snapshot (cyclus::DbInit di)
virtual cyclus::Inventories SnapshotInv ()
virtual void Tick ()
On each tick, the GrowthRegion queries its supply demand manager to determine if there exists some demand.
virtual void Tick ()
On each tick, the GrowthRegion queries its supply demand manager to determine if there exists some demand.
virtual ~GrowthRegion ()
The default destructor for the GrowthRegion.
virtual ~GrowthRegion ()
The default destructor for the GrowthRegion.
Protected Member Functions
void OrderBuild (cyclus::Agent *builder, cyclus::Agent *prototype)
orders builder to build a prototype
void OrderBuild (cyclus::Agent *builder, cyclus::Agent *prototype)
orders builder to build a prototype
void OrderBuilds (cyclus::toolkit::Commodity &commodity, double unmetdemand)
orders builds given a commodity and an unmet demand for production capacity of that commodity
void OrderBuilds (cyclus::toolkit::Commodity &commodity, double unmetdemand)
orders builds given a commodity and an unmet demand for production capacity of that commodity
void Register_ (cyclus::Agent *agent)
register a child
void Register_ (cyclus::Agent *agent)
register a child
void Unregister_ (cyclus::Agent *agent)
unregister a child
void Unregister_ (cyclus::Agent *agent)
unregister a child
Protected Attributes
cyclus::toolkit::BuildingManager buildmanager_
manager for building things
cyclus::toolkit::Commodity commod_
std::string commodity_name
std::vector< std::string > demand_params
std::vector< int > demand_times
std::vector< std::string > demand_types
cyclus::toolkit::SupplyDemandManager sdmanager_
manager for Supply and demand
Friends
class GrowthRegionTests
Detailed Description
This region determines if there is a need to meet a certain capacity (as defined via input) at each time step.
If there is such a need, the region will determine how many of each facility type are required and then determine, facility by facility, which of its institutions are available to build each facility.
In order to make GrowthRegion copacetic with init/restart, its input parameter space was simplified. For now it can only provide growth support for a single demanded commodity. A relatively simple next step will be to determin an input API and corresponding implementation that again supports multiple commodities being demanded.
Warning:
The growth region is experimental
Definition at line 34 of file build/cycamore/growth_region.h.
Constructor & Destructor Documentation
cycamore::GrowthRegion::GrowthRegion (cyclus::Context * ctx)
The default constructor for the GrowthRegion.
Definition at line 8 of file build/cycamore/growth_region.cc.
Referenced by Clone().
cycamore::GrowthRegion::~GrowthRegion () [virtual]
The default destructor for the GrowthRegion.
Definition at line 13 of file build/cycamore/growth_region.cc.
cycamore::GrowthRegion::GrowthRegion (cyclus::Context * ctx)
The default constructor for the GrowthRegion.
virtual cycamore::GrowthRegion::~GrowthRegion () [virtual]
The default destructor for the GrowthRegion.
Member Function Documentation
void cycamore::GrowthRegion::AddCommodityDemand (cyclus::toolkit::Commodity commod)
add a demand for a commodity on which this region request that facilities be built
void cycamore::GrowthRegion::AddCommodityDemand (cyclus::toolkit::Commodity commod)
add a demand for a commodity on which this region request that facilities be built
Definition at line 16 of file build/cycamore/growth_region.cc.
References demand_params, demand_times, demand_types, and sdmanager_.
Referenced by Build(), and EnterNotify().
virtual Json::Value cycamore::GrowthRegion::annotations () [inline, virtual]
Definition at line 162 of file build/cycamore/growth_region.h.
virtual void cycamore::GrowthRegion::Build (cyclus::Agent * parent) [virtual]
perform module-specific tasks when entering the simulation
void cycamore::GrowthRegion::Build (cyclus::Agent * parent) [virtual]
perform module-specific tasks when entering the simulation
Definition at line 32 of file build/cycamore/growth_region.cc.
References AddCommodityDemand(), commod_, and commodity_name.
virtual void cycamore::GrowthRegion::BuildNotify (Agent * m) [virtual]
register a new child
void cycamore::GrowthRegion::BuildNotify (Agent * m) [virtual]
register a new child
Definition at line 52 of file build/cycamore/growth_region.cc.
References Register_().
virtual cyclus::Agent* cycamore::GrowthRegion::Clone () [inline, virtual]
Definition at line 126 of file build/cycamore/growth_region.h.
References GrowthRegion(), and InitFrom().
virtual void cycamore::GrowthRegion::DecomNotify (Agent * m) [virtual]
unregister a child
void cycamore::GrowthRegion::DecomNotify (Agent * m) [virtual]
unregister a child
Definition at line 56 of file build/cycamore/growth_region.cc.
References Unregister_().
virtual void cycamore::GrowthRegion::EnterNotify () [virtual]
enter the simulation and register any children present
void cycamore::GrowthRegion::EnterNotify () [virtual]
enter the simulation and register any children present
Definition at line 38 of file build/cycamore/growth_region.cc.
References AddCommodityDemand(), commod_, commodity_name, and Register_().
virtual void cycamore::GrowthRegion::InfileToDb (cyclus::InfileTree * tree, cyclus::DbInit di) [inline, virtual]
Definition at line 61 of file build/cycamore/growth_region.h.
References commodity_name, demand_params, demand_times, and demand_types.
virtual void cycamore::GrowthRegion::InitFrom (cycamore::GrowthRegion * m) [inline, virtual]
Definition at line 42 of file build/cycamore/growth_region.h.
References commodity_name, demand_params, demand_times, and demand_types.
Referenced by Clone(), and InitFrom().
virtual void cycamore::GrowthRegion::InitFrom (cyclus::QueryableBackend * b) [inline, virtual]
Definition at line 51 of file build/cycamore/growth_region.h.
References commodity_name, demand_params, demand_times, demand_types, and InitFrom().
virtual void cycamore::GrowthRegion::InitInv (cyclus::Inventories & inv) [inline, virtual]
Definition at line 193 of file build/cycamore/growth_region.h.
void cycamore::GrowthRegion::OrderBuild (cyclus::Agent * builder, cyclus::Agent * prototype) [protected]
orders builder to build a prototype
Parameters:
builder the agent that can build buildee
prototype the agent to be built
void cycamore::GrowthRegion::OrderBuild (cyclus::Agent * builder, cyclus::Agent * prototype) [protected]
orders builder to build a prototype
Parameters:
builder the agent that can build buildee
prototype the agent to be built
void cycamore::GrowthRegion::OrderBuilds (cyclus::toolkit::Commodity & commodity, double unmetdemand) [protected]
orders builds given a commodity and an unmet demand for production capacity of that commodity
Parameters:
commodity the commodity being demanded
unmetdemand the unmet demand
void cycamore::GrowthRegion::OrderBuilds (cyclus::toolkit::Commodity & commodity, double unmetdemand) [protected]
orders builds given a commodity and an unmet demand for production capacity of that commodity
Parameters:
commodity the commodity being demanded
unmetdemand the unmet demand
Definition at line 118 of file build/cycamore/growth_region.cc.
References buildmanager_.
Referenced by Tick().
void cycamore::GrowthRegion::Register_ (cyclus::Agent * agent) [protected]
register a child
void cycamore::GrowthRegion::Register_ (cyclus::Agent * agent) [protected]
register a child
Definition at line 60 of file build/cycamore/growth_region.cc.
References buildmanager_, and sdmanager_.
Referenced by BuildNotify(), and EnterNotify().
virtual std::string cycamore::GrowthRegion::schema () [inline, virtual]
Definition at line 132 of file build/cycamore/growth_region.h.
cyclus::toolkit::SupplyDemandManager* cycamore::GrowthRegion::sdmanager () [inline]
Definition at line 69 of file src/growth_region.h.
References sdmanager_.
cyclus::toolkit::SupplyDemandManager* cycamore::GrowthRegion::sdmanager () [inline]
Definition at line 236 of file build/cycamore/growth_region.h.
References sdmanager_.
Referenced by cycamore::GrowthRegionTests::ManagesCommodity().
virtual void cycamore::GrowthRegion::Snapshot (cyclus::DbInit di) [inline, virtual]
Definition at line 201 of file build/cycamore/growth_region.h.
References commodity_name, demand_params, demand_times, and demand_types.
virtual cyclus::Inventories cycamore::GrowthRegion::SnapshotInv () [inline, virtual]
Definition at line 196 of file build/cycamore/growth_region.h.
virtual void cycamore::GrowthRegion::Tick () [virtual]
On each tick, the GrowthRegion queries its supply demand manager to determine if there exists some demand.
If demand for a commodity exists, then the correct build order for that demand is constructed and executed.
Parameters:
time is the time to perform the tick
void cycamore::GrowthRegion::Tick () [virtual]
On each tick, the GrowthRegion queries its supply demand manager to determine if there exists some demand.
If demand for a commodity exists, then the correct build order for that demand is constructed and executed.
Parameters:
time is the time to perform the tick
Definition at line 97 of file build/cycamore/growth_region.cc.
References commod_, OrderBuilds(), and sdmanager_.
void cycamore::GrowthRegion::Unregister_ (cyclus::Agent * agent) [protected]
unregister a child
void cycamore::GrowthRegion::Unregister_ (cyclus::Agent * agent) [protected]
unregister a child
Definition at line 82 of file build/cycamore/growth_region.cc.
References buildmanager_, and sdmanager_.
Referenced by DecomNotify().
Friends And Related Function Documentation
GrowthRegionTests [friend]
Definition at line 35 of file build/cycamore/growth_region.h.
Member Data Documentation
cyclus::toolkit::BuildingManager cycamore::GrowthRegion::buildmanager_ [protected]
manager for building things
Definition at line 260 of file build/cycamore/growth_region.h.
Referenced by OrderBuilds(), Register_(), and Unregister_().
cyclus::toolkit::Commodity cycamore::GrowthRegion::commod_ [protected]
Definition at line 257 of file build/cycamore/growth_region.h.
Referenced by Build(), EnterNotify(), and Tick().
std::string cycamore::GrowthRegion::commodity_name [protected]
Definition at line 243 of file build/cycamore/growth_region.h.
Referenced by Build(), EnterNotify(), InfileToDb(), InitFrom(), and Snapshot().
std::vector< std::string > cycamore::GrowthRegion::demand_params [protected]
Definition at line 251 of file build/cycamore/growth_region.h.
Referenced by AddCommodityDemand(), InfileToDb(), InitFrom(), and Snapshot().
std::vector< int > cycamore::GrowthRegion::demand_times [protected]
Definition at line 255 of file build/cycamore/growth_region.h.
Referenced by AddCommodityDemand(), InfileToDb(), InitFrom(), and Snapshot().
std::vector< std::string > cycamore::GrowthRegion::demand_types [protected]
Definition at line 247 of file build/cycamore/growth_region.h.
Referenced by AddCommodityDemand(), InfileToDb(), InitFrom(), and Snapshot().
cyclus::toolkit::SupplyDemandManager cycamore::GrowthRegion::sdmanager_ [protected]
manager for Supply and demand
Definition at line 263 of file build/cycamore/growth_region.h.
Referenced by AddCommodityDemand(), Register_(), sdmanager(), Tick(), and Unregister_().
The documentation for this class was generated from the following files:
build/cycamore/growth_region.h
src/growth_region.h
build/cycamore/growth_region.cc
src/growth_region.cc