CYCAMORE: cycamore::MixerTest Class Reference
cycamore::MixerTest Class Reference
Public Types
typedef cyclus::toolkit::ResBuf< cyclus::Material > InvBuffer
typedef cyclus::toolkit::ResBuf< cyclus::Material > InvBuffer
Public Member Functions
InvBuffer * GetOutPutBuffer ()
InvBuffer * GetOutPutBuffer ()
double GetOutStream_capacity ()
double GetOutStream_capacity ()
std::string GetOutStream_comds ()
std::string GetOutStream_comds ()
std::vector< double > GetStream_capacity ()
std::vector< double > GetStream_capacity ()
std::vector< double > GetStream_ratio ()
std::vector< double > GetStream_ratio ()
std::map< std::string, InvBuffer > GetStreamBuffer ()
std::map< std::string, InvBuffer > GetStreamBuffer ()
double GetThroughput ()
double GetThroughput ()
void SetIn_stream (t_instream streams)
void SetIn_stream (t_instream streams)
void SetIn_stream (std::vector< std::map< std::string, double > > in_stream, std::vector< double > ratios, std::vector< double > caps)
void SetIn_stream (std::vector< std::map< std::string, double > > in_stream, std::vector< double > ratios, std::vector< double > caps)
void SetInputInv (std::vector< cyclus::Material::Ptr > mat)
void SetInputInv (std::vector< cyclus::Material::Ptr > mat)
void SetOutStream_capacity (double cap)
void SetOutStream_capacity (double cap)
void SetOutStream_comds (std::string com)
void SetOutStream_comds (std::string com)
void SetStream_capacity (std::vector< double > new_caps)
void SetStream_capacity (std::vector< double > new_caps)
void SetStream_ratio (std::vector< double > new_ratios)
void SetStream_ratio (std::vector< double > new_ratios)
void SetThroughput (double thpt)
void SetThroughput (double thpt)
virtual void SetUp ()
virtual void SetUp ()
virtual void TearDown ()
virtual void TearDown ()
Public Attributes
std::vector< double > in_cap
std::vector< std::map< std::string, double > > in_coms
std::vector< double > in_frac
Mixer * mf_facility_
double out_cap
std::string out_com
cyclus::TestContext tc_
double throughput
Detailed Description
Definition at line 50 of file _tmp_build/cycamore/mixer_tests.cc.
Member Typedef Documentation
InvBuffer [1/2]
typedef cyclus::toolkit::ResBuf<cyclus::Material> cycamore::MixerTest::InvBuffer
Definition at line 52 of file _tmp_build/cycamore/mixer_tests.cc.
InvBuffer [2/2]
typedef cyclus::toolkit::ResBuf<cyclus::Material> cycamore::MixerTest::InvBuffer
Definition at line 52 of file src/mixer_tests.cc.
Member Function Documentation
GetOutPutBuffer() [1/2]
InvBuffer* cycamore::MixerTest::GetOutPutBuffer () inline
Definition at line 168 of file _tmp_build/cycamore/mixer_tests.cc.
References cycamore::Mixer::output.
Referenced by GetStreamBuffer(), and cycamore::TEST_F().
GetOutPutBuffer() [2/2]
InvBuffer* cycamore::MixerTest::GetOutPutBuffer () inline
Definition at line 168 of file src/mixer_tests.cc.
References cycamore::Mixer::output.
GetOutStream_capacity() [1/2]
double cycamore::MixerTest::GetOutStream_capacity () inline
Definition at line 164 of file _tmp_build/cycamore/mixer_tests.cc.
References cycamore::Mixer::out_buf_size.
GetOutStream_capacity() [2/2]
double cycamore::MixerTest::GetOutStream_capacity () inline
Definition at line 164 of file src/mixer_tests.cc.
References cycamore::Mixer::out_buf_size.
GetOutStream_comds() [1/2]
std::string cycamore::MixerTest::GetOutStream_comds () inline
Definition at line 162 of file _tmp_build/cycamore/mixer_tests.cc.
References cycamore::Mixer::out_commod.
GetOutStream_comds() [2/2]
std::string cycamore::MixerTest::GetOutStream_comds () inline
Definition at line 162 of file src/mixer_tests.cc.
References cycamore::Mixer::out_commod.
GetStream_capacity() [1/2]
std::vector<double> cycamore::MixerTest::GetStream_capacity () inline
Definition at line 158 of file src/mixer_tests.cc.
References cycamore::Mixer::in_buf_sizes.
GetStream_capacity() [2/2]
std::vector<double> cycamore::MixerTest::GetStream_capacity () inline
Definition at line 158 of file _tmp_build/cycamore/mixer_tests.cc.
References cycamore::Mixer::in_buf_sizes.
GetStream_ratio() [1/2]
std::vector<double> cycamore::MixerTest::GetStream_ratio () inline
Definition at line 156 of file _tmp_build/cycamore/mixer_tests.cc.
References cycamore::Mixer::mixing_ratios.
Referenced by GetStreamBuffer(), and cycamore::TEST_F().
GetStream_ratio() [2/2]
std::vector<double> cycamore::MixerTest::GetStream_ratio () inline
Definition at line 156 of file src/mixer_tests.cc.
References cycamore::Mixer::mixing_ratios.
GetStreamBuffer() [1/2]
std::map<std::string, InvBuffer> cycamore::MixerTest::GetStreamBuffer () inline
Definition at line 170 of file _tmp_build/cycamore/mixer_tests.cc.
References cycamore::Mixer::streambufs.
Referenced by GetStreamBuffer(), and cycamore::TEST_F().
GetStreamBuffer() [2/2]
std::map<std::string, InvBuffer> cycamore::MixerTest::GetStreamBuffer () inline
Definition at line 170 of file src/mixer_tests.cc.
References cycamore::c_natu(), cycamore::c_pustream(), cycamore::c_uox(), cycamore::Mixer::EnterNotify(), GetOutPutBuffer(), GetStream_ratio(), GetStreamBuffer(), in_cap, in_coms, in_frac, mf_facility_, SetInputInv(), SetOutStream_capacity(), SetStream_capacity(), SetStream_ratio(), SetThroughput(), cycamore::Mixer::streambufs, cycamore::string, cycamore::TEST(), cycamore::TEST_F(), throughput, and cycamore::Mixer::Tick().
GetThroughput() [1/2]
double cycamore::MixerTest::GetThroughput () inline
Definition at line 166 of file src/mixer_tests.cc.
References cycamore::Mixer::throughput.
GetThroughput() [2/2]
double cycamore::MixerTest::GetThroughput () inline
Definition at line 166 of file _tmp_build/cycamore/mixer_tests.cc.
References cycamore::Mixer::throughput.
SetIn_stream() [1/4]
void cycamore::MixerTest::SetIn_stream (t_instream streams) inline
Definition at line 99 of file _tmp_build/cycamore/mixer_tests.cc.
References cycamore::Mixer::streams_.
Referenced by SetIn_stream(), and SetUp().
SetIn_stream() [2/4]
void cycamore::MixerTest::SetIn_stream (t_instream streams) inline
Definition at line 99 of file src/mixer_tests.cc.
References cycamore::Mixer::streams_.
SetIn_stream() [3/4]
void cycamore::MixerTest::SetIn_stream (std::vector< std::map< std::string, double > > in_stream, std::vector< double > ratios, std::vector< double > caps) inline
Definition at line 110 of file _tmp_build/cycamore/mixer_tests.cc.
References SetIn_stream().
SetIn_stream() [4/4]
void cycamore::MixerTest::SetIn_stream (std::vector< std::map< std::string, double > > in_stream, std::vector< double > ratios, std::vector< double > caps) inline
Definition at line 110 of file src/mixer_tests.cc.
References SetIn_stream().
SetInputInv() [1/2]
void cycamore::MixerTest::SetInputInv (std::vector< cyclus::Material::Ptr > mat) inline
Definition at line 149 of file _tmp_build/cycamore/mixer_tests.cc.
References cycamore::Mixer::streambufs, and cycamore::string.
Referenced by GetStreamBuffer(), and cycamore::TEST_F().
SetInputInv() [2/2]
void cycamore::MixerTest::SetInputInv (std::vector< cyclus::Material::Ptr > mat) inline
Definition at line 149 of file src/mixer_tests.cc.
References cycamore::Mixer::streambufs, and cycamore::string.
SetOutStream_capacity() [1/2]
void cycamore::MixerTest::SetOutStream_capacity (double cap) inline
Definition at line 144 of file _tmp_build/cycamore/mixer_tests.cc.
References cycamore::Mixer::out_buf_size.
Referenced by GetStreamBuffer(), and cycamore::TEST_F().
SetOutStream_capacity() [2/2]
void cycamore::MixerTest::SetOutStream_capacity (double cap) inline
Definition at line 144 of file src/mixer_tests.cc.
References cycamore::Mixer::out_buf_size.
SetOutStream_comds() [1/2]
void cycamore::MixerTest::SetOutStream_comds (std::string com) inline
Definition at line 139 of file _tmp_build/cycamore/mixer_tests.cc.
References cycamore::Mixer::out_commod.
Referenced by SetUp().
SetOutStream_comds() [2/2]
void cycamore::MixerTest::SetOutStream_comds (std::string com) inline
Definition at line 139 of file src/mixer_tests.cc.
References cycamore::Mixer::out_commod.
SetStream_capacity() [1/2]
void cycamore::MixerTest::SetStream_capacity (std::vector< double > new_caps) inline
Definition at line 131 of file src/mixer_tests.cc.
References cycamore::Mixer::in_buf_sizes, and cycamore::Mixer::streams_.
SetStream_capacity() [2/2]
void cycamore::MixerTest::SetStream_capacity (std::vector< double > new_caps) inline
Definition at line 131 of file _tmp_build/cycamore/mixer_tests.cc.
References cycamore::Mixer::in_buf_sizes, and cycamore::Mixer::streams_.
Referenced by GetStreamBuffer(), and cycamore::TEST_F().
SetStream_ratio() [1/2]
void cycamore::MixerTest::SetStream_ratio (std::vector< double > new_ratios) inline
Definition at line 123 of file _tmp_build/cycamore/mixer_tests.cc.
References cycamore::Mixer::mixing_ratios, and cycamore::Mixer::streams_.
Referenced by GetStreamBuffer(), and cycamore::TEST_F().
SetStream_ratio() [2/2]
void cycamore::MixerTest::SetStream_ratio (std::vector< double > new_ratios) inline
Definition at line 123 of file src/mixer_tests.cc.
References cycamore::Mixer::mixing_ratios, and cycamore::Mixer::streams_.
SetThroughput() [1/2]
void cycamore::MixerTest::SetThroughput (double thpt) inline
Definition at line 94 of file src/mixer_tests.cc.
References cycamore::Mixer::throughput.
SetThroughput() [2/2]
void cycamore::MixerTest::SetThroughput (double thpt) inline
Definition at line 94 of file _tmp_build/cycamore/mixer_tests.cc.
References cycamore::Mixer::throughput.
Referenced by GetStreamBuffer(), and cycamore::TEST_F().
SetUp() [1/2]
virtual void cycamore::MixerTest::SetUp () inline virtual
Definition at line 57 of file _tmp_build/cycamore/mixer_tests.cc.
References SetIn_stream(), and SetOutStream_comds().
SetUp() [2/2]
virtual void cycamore::MixerTest::SetUp () inline virtual
Definition at line 57 of file src/mixer_tests.cc.
References SetIn_stream(), and SetOutStream_comds().
TearDown() [1/2]
virtual void cycamore::MixerTest::TearDown () inline virtual
Definition at line 83 of file src/mixer_tests.cc.
References in_cap, in_coms, in_frac, mf_facility_, out_cap, out_com, cycamore::string, and throughput.
TearDown() [2/2]
virtual void cycamore::MixerTest::TearDown () inline virtual
Definition at line 83 of file _tmp_build/cycamore/mixer_tests.cc.
References mf_facility_.
Member Data Documentation
in_cap
std::vector< double > cycamore::MixerTest::in_cap
Definition at line 87 of file _tmp_build/cycamore/mixer_tests.cc.
Referenced by GetStreamBuffer(), TearDown(), and cycamore::TEST_F().
in_coms
std::vector< std::map< std::string, double > > cycamore::MixerTest::in_coms
Definition at line 85 of file _tmp_build/cycamore/mixer_tests.cc.
Referenced by GetStreamBuffer(), TearDown(), and cycamore::TEST_F().
in_frac
std::vector< double > cycamore::MixerTest::in_frac
Definition at line 86 of file _tmp_build/cycamore/mixer_tests.cc.
Referenced by GetStreamBuffer(), TearDown(), and cycamore::TEST_F().
mf_facility_
Mixer * cycamore::MixerTest::mf_facility_
Definition at line 55 of file _tmp_build/cycamore/mixer_tests.cc.
Referenced by GetStreamBuffer(), TearDown(), and cycamore::TEST_F().
out_cap
double cycamore::MixerTest::out_cap
Definition at line 90 of file _tmp_build/cycamore/mixer_tests.cc.
Referenced by TearDown().
out_com
std::string cycamore::MixerTest::out_com
Definition at line 89 of file _tmp_build/cycamore/mixer_tests.cc.
Referenced by TearDown().
tc_
cyclus::TestContext cycamore::MixerTest::tc_
Definition at line 54 of file _tmp_build/cycamore/mixer_tests.cc.
throughput
double cycamore::MixerTest::throughput
Definition at line 92 of file _tmp_build/cycamore/mixer_tests.cc.
Referenced by GetStreamBuffer(), TearDown(), and cycamore::TEST_F().
The documentation for this class was generated from the following file:
_tmp_build/cycamore/mixer_tests.cc