CYCAMORE: cycamore::Source Class Reference
cycamore::Source Class Reference
The Source class inherits from the cyclus::Facility class and is dynamically loaded by the Agent class when requested.
#include <source.h>
Public Member Functions
virtual Json::Value annotations ()
void Capacity (double cap)
sets the capacity of a material generated at any given time step
double Capacity () const
void Capacity (double cap)
sets the capacity of a material generated at any given time step
double Capacity () const
virtual cyclus::Agent * Clone ()
void commodity (std::string name)
sets the output commodity name
std::string commodity () const
void commodity (std::string name)
sets the output commodity name
std::string commodity () const
double CurrentCapacity () const
double CurrentCapacity () const
virtual void EnterNotify ()
virtual void EnterNotify ()
virtual std::set
< cyclus::BidPortfolio
< cyclus::Material >::Ptr > GetMatlBids (cyclus::CommodMap< cyclus::Material >::type &commod_requests)
Responds to each request for this source facility's commodity.
virtual std::set
< cyclus::BidPortfolio
< cyclus::Material >::Ptr > GetMatlBids (cyclus::CommodMap< cyclus::Material >::type &commod_requests)
Responds to each request for this source facility's commodity.
virtual void GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > &trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > &responses)
respond to each trade with a material made from this facility's recipe
virtual void GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > &trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > &responses)
respond to each trade with a material made from this facility's recipe
cyclus::Material::Ptr GetOffer (const cyclus::Material::Ptr target) const
creates a material object to offer to a requester
cyclus::Material::Ptr GetOffer (const cyclus::Material::Ptr target) const
creates a material object to offer to a requester
virtual void InfileToDb (cyclus::InfileTree *tree, cyclus::DbInit di)
virtual void InitFrom (cycamore::Source *m)
virtual void InitFrom (cyclus::QueryableBackend *b)
virtual void InitInv (cyclus::Inventories &inv)
void recipe (std::string name)
sets the name of the recipe to be produced
std::string recipe () const
void recipe (std::string name)
sets the name of the recipe to be produced
std::string recipe () const
virtual std::string schema ()
virtual void Snapshot (cyclus::DbInit di)
virtual cyclus::Inventories SnapshotInv ()
Source (cyclus::Context *ctx)
Constructor for the Source class.
Source (cyclus::Context *ctx)
Constructor for the Source class.
virtual std::string str ()
Print information about this agent.
virtual std::string str ()
Print information about this agent.
virtual void Tick ()
Each facility is prompted to do its beginning-of-time-step stuff at the tick of the timer.
virtual void Tick ()
Each facility is prompted to do its beginning-of-time-step stuff at the tick of the timer.
virtual void Tock ()
Each facility is prompted to its end-of-time-step stuff on the tock of the timer.
virtual void Tock ()
Each facility is prompted to its end-of-time-step stuff on the tock of the timer.
virtual ~Source ()
virtual ~Source ()
Private Attributes
double capacity
The capacity is defined in terms of the number of units of the recipe that can be provided each time step.
cyclus::toolkit::Commodity commod_
double current_capacity
The capacity at the current time step.
std::string out_commod
This facility has only one output commodity.
std::string recipe_name
Name of the recipe this facility uses.
Detailed Description
The Source class inherits from the cyclus::Facility class and is dynamically loaded by the Agent class when requested.
This cyclus::Facility provides a simple source of some capacity (possibly infinite) of some commodity/Recipe.
Introduction
The Source is a facility type in Cyclus capable of providing a finite or infinite.Supply of a particular material to the simulation. A Source generates material of a certain composition and commodity type, then offers that material on the appropriate market. Shipments of this material are executed when the market issues an order that the offer has been matched with a request.
Agent Parameters
Source behavior is comprehensively defined by the following parameters:
double capacity: The production capacity of the facility (units vary, but typically kg/month). Capacity is infinite if a negative value is provided.
int startDate: The date on which the facility begins to operate (months).
int lifeTime: The length of time that the facility operates (months). - std::string outCommod: the commodity that this facility produces - double inventorysize: the maximum quantity of material to be held in the inventory
double commodprice: the price of the output material PER UNIT
map<Nucs, NumDens> outComp
Optional Parameters
Source behavior may also be specified with the following optional parameters which have default values listed here.
double capacityFactor: The ratio of actual production capacity to the rated production capacity. Default is 1 (actual/rated).
double availFactor: The percent of time the facility operates at its capacity factor. Default is 100%.
double capitalCost: The cost of constructing and commissioning this facility. Default is 0 ($).
double opCost: The annual cost of operation and maintenance of this facility. Default is 0 ($/year).
int constrTime: The number of months it takes to construct and commission this facility. Default is 0 (months).
int decomTime: The number of months it takes to deconstruct and decommission this facility. Default is 0 (months).
Inst* inst: The institution responsible for this facility.
string name: A non-generic name for this facility.
Detailed Behavior
If Finite Capacity:
The Source starts operation when the simulation reaches the month specified as the startDate. It immediately begins to produce material at the rate defined by its capacity. Each month the Source adds the amount it has produced to its inventory. It then offers to the appropriate market exactly as much material as it has in its inventory. If an offer is matched with a request, the Source executes that order by subtracting the quantity from its inventory and sending that amount to the requesting facility. When the simulation time equals the startDate plus the lifeTime, the facility ceases to operate.
If Infinite Capacity:
The Source starts operation when the simulation reaches the month specified as the startDate. Each month the Source offers an infinite amount of material to the appropriate market. If there is a request for that material, the Source executes that order by sending that amount to the requesting facility. When the simulation time equals the startDate plus the lifeTime, the facility ceases to operate.
Question:
What is the best way to allow offers of an infinite amount of material on a market?
Definition at line 89 of file build/cycamore/source.h.
Constructor & Destructor Documentation
cycamore::Source::Source (cyclus::Context * ctx)
Constructor for the Source class.
Parameters:
ctx the cyclus context for access to simulation-wide parameters
Definition at line 13 of file build/cycamore/source.cc.
Referenced by Clone().
cycamore::Source::~Source () [virtual]
Definition at line 20 of file build/cycamore/source.cc.
cycamore::Source::Source (cyclus::Context * ctx)
Constructor for the Source class.
Parameters:
ctx the cyclus context for access to simulation-wide parameters
virtual cycamore::Source::~Source () [virtual]
Member Function Documentation
Json::Value cycamore::Source::annotations () [virtual]
Definition at line 46 of file build/cycamore/source.cc.
void cycamore::Source::Capacity (double cap) [inline]
sets the capacity of a material generated at any given time step
Parameters:
capacity the production capacity
Definition at line 153 of file src/source.h.
References capacity, and current_capacity.
double cycamore::Source::Capacity () const [inline]
Returns:
the production capacity at any given time step
Definition at line 159 of file src/source.h.
References capacity.
void cycamore::Source::Capacity (double cap) [inline]
sets the capacity of a material generated at any given time step
Parameters:
capacity the production capacity
Definition at line 172 of file build/cycamore/source.h.
References capacity, and current_capacity.
Referenced by SourceTest::SetUpSource(), and TEST_F().
double cycamore::Source::Capacity () const [inline]
Returns:
the production capacity at any given time step
Definition at line 178 of file build/cycamore/source.h.
References capacity.
Referenced by str().
cyclus::Agent * cycamore::Source::Clone () [virtual]
Definition at line 21 of file build/cycamore/source.cc.
References InitFrom(), and Source().
void cycamore::Source::commodity (std::string name) [inline]
sets the output commodity name
Parameters:
name the commodity name
Definition at line 146 of file src/source.h.
References out_commod.
std::string cycamore::Source::commodity () const [inline]
Returns:
the output commodity
Definition at line 149 of file src/source.h.
References out_commod.
void cycamore::Source::commodity (std::string name) [inline]
sets the output commodity name
Parameters:
name the commodity name
Definition at line 165 of file build/cycamore/source.h.
References out_commod.
Referenced by SourceTest::SetUpSource(), and TEST_F().
std::string cycamore::Source::commodity () const [inline]
Returns:
the output commodity
Definition at line 168 of file build/cycamore/source.h.
References out_commod.
double cycamore::Source::CurrentCapacity () const [inline]
Returns:
the current timestep's capacity
Definition at line 169 of file src/source.h.
References current_capacity.
double cycamore::Source::CurrentCapacity () const [inline]
Returns:
the current timestep's capacity
Definition at line 188 of file build/cycamore/source.h.
References current_capacity.
Referenced by TEST_F().
virtual void cycamore::Source::EnterNotify () [virtual]
void cycamore::Source::EnterNotify () [virtual]
Definition at line 154 of file build/cycamore/source.cc.
References capacity, commod_, and out_commod.
virtual std::set<cyclus::BidPortfolio<cyclus::Material>::Ptr> cycamore::Source::GetMatlBids (cyclus::CommodMap< cyclus::Material >::type & commod_requests) [virtual]
Responds to each request for this source facility's commodity.
If a given request is more than this facility's capacity, it will offer its capacity.
std::set< cyclus::BidPortfolio< cyclus::Material >::Ptr > cycamore::Source::GetMatlBids (cyclus::CommodMap< cyclus::Material >::type & commod_requests) [virtual]
Responds to each request for this source facility's commodity.
If a given request is more than this facility's capacity, it will offer its capacity.
Definition at line 211 of file build/cycamore/source.cc.
References capacity, GetOffer(), and out_commod.
virtual void cycamore::Source::GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > & trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > & responses) [virtual]
respond to each trade with a material made from this facility's recipe
Parameters:
trades all trades in which this trader is the supplier
responses a container to populate with responses to each trade
void cycamore::Source::GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > & trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > & responses) [virtual]
respond to each trade with a material made from this facility's recipe
Parameters:
trades all trades in which this trader is the supplier
responses a container to populate with responses to each trade
Definition at line 242 of file build/cycamore/source.cc.
References capacity, current_capacity, out_commod, and recipe_name.
cyclus::Material::Ptr cycamore::Source::GetOffer (const cyclus::Material::Ptr target) const
creates a material object to offer to a requester
Parameters:
target the material target a request desires
cyclus::Material::Ptr cycamore::Source::GetOffer (const cyclus::Material::Ptr target) const
creates a material object to offer to a requester
Parameters:
target the material target a request desires
Definition at line 202 of file build/cycamore/source.cc.
References capacity, and recipe_name.
Referenced by GetMatlBids().
void cycamore::Source::InfileToDb (cyclus::InfileTree * tree, cyclus::DbInit di) [virtual]
Definition at line 78 of file build/cycamore/source.cc.
References capacity, current_capacity, out_commod, and recipe_name.
void cycamore::Source::InitFrom (cycamore::Source * m) [virtual]
Definition at line 131 of file build/cycamore/source.cc.
References capacity, current_capacity, out_commod, and recipe_name.
Referenced by Clone(), and InitFrom().
void cycamore::Source::InitFrom (cyclus::QueryableBackend * b) [virtual]
Definition at line 140 of file build/cycamore/source.cc.
References capacity, commod_, current_capacity, InitFrom(), out_commod, and recipe_name.
void cycamore::Source::InitInv (cyclus::Inventories & inv) [virtual]
Definition at line 126 of file build/cycamore/source.cc.
void cycamore::Source::recipe (std::string name) [inline]
sets the name of the recipe to be produced
Parameters:
name the recipe name
Definition at line 163 of file src/source.h.
References recipe_name.
std::string cycamore::Source::recipe () const [inline]
Returns:
the name of the output recipe
Definition at line 166 of file src/source.h.
References recipe_name.
void cycamore::Source::recipe (std::string name) [inline]
sets the name of the recipe to be produced
Parameters:
name the recipe name
Definition at line 182 of file build/cycamore/source.h.
References recipe_name.
Referenced by SourceTest::SetUpSource(), and TEST_F().
std::string cycamore::Source::recipe () const [inline]
Returns:
the name of the output recipe
Definition at line 185 of file build/cycamore/source.h.
References recipe_name.
std::string cycamore::Source::schema () [virtual]
Definition at line 28 of file build/cycamore/source.cc.
void cycamore::Source::Snapshot (cyclus::DbInit di) [virtual]
Definition at line 110 of file build/cycamore/source.cc.
References capacity, current_capacity, out_commod, and recipe_name.
cyclus::Inventories cycamore::Source::SnapshotInv () [virtual]
Definition at line 120 of file build/cycamore/source.cc.
virtual std::string cycamore::Source::str () [virtual]
Print information about this agent.
std::string cycamore::Source::str () [virtual]
Print information about this agent.
Definition at line 163 of file build/cycamore/source.cc.
References Capacity(), capacity, commod_, out_commod, and recipe_name.
Referenced by Tick().
virtual void cycamore::Source::Tick () [virtual]
Each facility is prompted to do its beginning-of-time-step stuff at the tick of the timer.
Parameters:
time is the time to perform the tick
void cycamore::Source::Tick () [virtual]
Each facility is prompted to do its beginning-of-time-step stuff at the tick of the timer.
Parameters:
time is the time to perform the tick
Definition at line 185 of file build/cycamore/source.cc.
References capacity, current_capacity, out_commod, and str().
virtual void cycamore::Source::Tock () [virtual]
Each facility is prompted to its end-of-time-step stuff on the tock of the timer.
Parameters:
time is the time to perform the tock
void cycamore::Source::Tock () [virtual]
Each facility is prompted to its end-of-time-step stuff on the tock of the timer.
Parameters:
time is the time to perform the tock
Definition at line 196 of file build/cycamore/source.cc.
Member Data Documentation
double cycamore::Source::capacity [private]
The capacity is defined in terms of the number of units of the recipe that can be provided each time step.
A very large number can be provided to represent infinte capacity.
Definition at line 208 of file build/cycamore/source.h.
Referenced by Capacity(), EnterNotify(), GetMatlBids(), GetMatlTrades(), GetOffer(), InfileToDb(), InitFrom(), Snapshot(), str(), and Tick().
cyclus::toolkit::Commodity cycamore::Source::commod_ [private]
Definition at line 191 of file build/cycamore/source.h.
Referenced by EnterNotify(), InitFrom(), and str().
double cycamore::Source::current_capacity [private]
The capacity at the current time step.
Definition at line 212 of file build/cycamore/source.h.
Referenced by Capacity(), CurrentCapacity(), GetMatlTrades(), InfileToDb(), InitFrom(), Snapshot(), and Tick().
std::string cycamore::Source::out_commod [private]
This facility has only one output commodity.
Definition at line 196 of file build/cycamore/source.h.
Referenced by commodity(), EnterNotify(), GetMatlBids(), GetMatlTrades(), InfileToDb(), InitFrom(), Snapshot(), str(), and Tick().
std::string cycamore::Source::recipe_name [private]
Name of the recipe this facility uses.
Definition at line 201 of file build/cycamore/source.h.
Referenced by GetMatlTrades(), GetOffer(), InfileToDb(), InitFrom(), recipe(), Snapshot(), and str().
The documentation for this class was generated from the following files:
build/cycamore/source.h
src/source.h
build/cycamore/source.cc
src/source.cc