CYCAMORE: cycamore::SourceTest Class Reference
cycamore::SourceTest Class Reference
#include <source_tests.h>
Public Member Functions
boost::shared_ptr< cyclus::ExchangeContext< cyclus::Material > > GetContext (int nreqs, std::string commodity)
boost::shared_ptr< cyclus::ExchangeContext< cyclus::Material > > GetContext (int nreqs, std::string commodity)
void InitParameters ()
void InitParameters ()
std::string outcommod (cycamore::Source *s)
std::string outcommod (cycamore::Source *s)
void outcommod (cycamore::Source *s, std::string commod)
void outcommod (cycamore::Source *s, std::string commod)
std::string outrecipe (cycamore::Source *s)
std::string outrecipe (cycamore::Source *s)
void outrecipe (cycamore::Source *s, std::string recipe)
void outrecipe (cycamore::Source *s, std::string recipe)
virtual void SetUp ()
virtual void SetUp ()
void SetUpSource ()
void SetUpSource ()
virtual void TearDown ()
virtual void TearDown ()
double throughput (cycamore::Source *s)
double throughput (cycamore::Source *s)
void throughput (cycamore::Source *s, double val)
void throughput (cycamore::Source *s, double val)
Public Attributes
double capacity
std::string commod
cyclus::Composition::Ptr recipe
std::string recipe_name
cycamore::Source * src_facility
cyclus::TestContext tc
TestFacility * trader
Detailed Description
Definition at line 17 of file _tmp_build/cycamore/source_tests.h.
Member Function Documentation
GetContext() [1/2]
boost::shared_ptr< cyclus::ExchangeContext< cyclus::Material > > cycamore::SourceTest::GetContext (int nreqs, std::string commodity)
Definition at line 157 of file _tmp_build/cycamore/source_tests.cc.
References trader.
Referenced by cycamore::TEST_F(), and throughput().
GetContext() [2/2]
boost::shared_ptr<cyclus::ExchangeContext<cyclus::Material> > cycamore::SourceTest::GetContext (int nreqs, std::string commodity)
InitParameters() [1/2]
void cycamore::SourceTest::InitParameters ()
Definition at line 24 of file _tmp_build/cycamore/source_tests.cc.
References capacity, commod, recipe, recipe_name, and tc.
Referenced by SetUp().
InitParameters() [2/2]
void cycamore::SourceTest::InitParameters ()
outcommod() [1/4]
std::string cycamore::SourceTest::outcommod (cycamore::Source * s) inline
Definition at line 32 of file src/source_tests.h.
References cycamore::Source::outcommod.
outcommod() [2/4]
std::string cycamore::SourceTest::outcommod (cycamore::Source * s) inline
Definition at line 32 of file _tmp_build/cycamore/source_tests.h.
References cycamore::Source::outcommod.
Referenced by SetUpSource(), and cycamore::TEST_F().
outcommod() [3/4]
void cycamore::SourceTest::outcommod (cycamore::Source * s, std::string commod) inline
Definition at line 38 of file src/source_tests.h.
References commod, and cycamore::Source::outcommod.
outcommod() [4/4]
void cycamore::SourceTest::outcommod (cycamore::Source * s, std::string commod) inline
Definition at line 38 of file _tmp_build/cycamore/source_tests.h.
References commod, and cycamore::Source::outcommod.
outrecipe() [1/4]
std::string cycamore::SourceTest::outrecipe (cycamore::Source * s) inline
Definition at line 31 of file _tmp_build/cycamore/source_tests.h.
References cycamore::Source::outrecipe.
Referenced by SetUpSource(), and cycamore::TEST_F().
outrecipe() [2/4]
std::string cycamore::SourceTest::outrecipe (cycamore::Source * s) inline
Definition at line 31 of file src/source_tests.h.
References cycamore::Source::outrecipe.
outrecipe() [3/4]
void cycamore::SourceTest::outrecipe (cycamore::Source * s, std::string recipe) inline
Definition at line 35 of file _tmp_build/cycamore/source_tests.h.
References cycamore::Source::outrecipe, and recipe.
outrecipe() [4/4]
void cycamore::SourceTest::outrecipe (cycamore::Source * s, std::string recipe) inline
Definition at line 35 of file src/source_tests.h.
References cycamore::Source::outrecipe, and recipe.
SetUp() [1/2]
void cycamore::SourceTest::SetUp () virtual
Definition at line 13 of file _tmp_build/cycamore/source_tests.cc.
References InitParameters(), SetUpSource(), src_facility, tc, and trader.
SetUp() [2/2]
virtual void cycamore::SourceTest::SetUp () virtual
SetUpSource() [1/2]
void cycamore::SourceTest::SetUpSource ()
Definition at line 33 of file _tmp_build/cycamore/source_tests.cc.
References capacity, commod, outcommod(), outrecipe(), recipe_name, src_facility, and throughput().
Referenced by SetUp().
SetUpSource() [2/2]
void cycamore::SourceTest::SetUpSource ()
TearDown() [1/2]
void cycamore::SourceTest::TearDown () virtual
Definition at line 20 of file _tmp_build/cycamore/source_tests.cc.
References src_facility.
TearDown() [2/2]
virtual void cycamore::SourceTest::TearDown () virtual
throughput() [1/4]
double cycamore::SourceTest::throughput (cycamore::Source * s) inline
Definition at line 33 of file _tmp_build/cycamore/source_tests.h.
References cycamore::Source::throughput.
Referenced by SetUpSource(), and cycamore::TEST_F().
throughput() [2/4]
double cycamore::SourceTest::throughput (cycamore::Source * s) inline
Definition at line 33 of file src/source_tests.h.
References cycamore::Source::throughput.
throughput() [3/4]
void cycamore::SourceTest::throughput (cycamore::Source * s, double val) inline
Definition at line 41 of file src/source_tests.h.
References GetContext(), cycamore::string, and cycamore::Source::throughput.
throughput() [4/4]
void cycamore::SourceTest::throughput (cycamore::Source * s, double val) inline
Definition at line 41 of file _tmp_build/cycamore/source_tests.h.
References GetContext(), cycamore::string, and cycamore::Source::throughput.
Member Data Documentation
capacity
double cycamore::SourceTest::capacity
Definition at line 23 of file _tmp_build/cycamore/source_tests.h.
Referenced by InitParameters(), SetUpSource(), and cycamore::TEST_F().
commod
std::string cycamore::SourceTest::commod
Definition at line 22 of file _tmp_build/cycamore/source_tests.h.
Referenced by InitParameters(), outcommod(), SetUpSource(), and cycamore::TEST_F().
recipe
cyclus::Composition::Ptr cycamore::SourceTest::recipe
Definition at line 24 of file _tmp_build/cycamore/source_tests.h.
Referenced by InitParameters(), outrecipe(), and cycamore::TEST_F().
recipe_name
std::string cycamore::SourceTest::recipe_name
Definition at line 22 of file _tmp_build/cycamore/source_tests.h.
Referenced by InitParameters(), and SetUpSource().
src_facility
cycamore::Source * cycamore::SourceTest::src_facility
Definition at line 21 of file _tmp_build/cycamore/source_tests.h.
Referenced by SetUp(), SetUpSource(), TearDown(), and cycamore::TEST_F().
tc
cyclus::TestContext cycamore::SourceTest::tc
Definition at line 19 of file _tmp_build/cycamore/source_tests.h.
Referenced by InitParameters(), SetUp(), and cycamore::TEST_F().
trader
TestFacility * cycamore::SourceTest::trader
Definition at line 20 of file _tmp_build/cycamore/source_tests.h.
Referenced by GetContext(), SetUp(), and cycamore::TEST_F().
The documentation for this class was generated from the following files:
_tmp_build/cycamore/source_tests.h
_tmp_build/cycamore/source_tests.cc