CYCAMORE: cycamore::ManagerInst Class Reference
cycamore::ManagerInst Class Reference
#include <manager_inst.h>
Public Member Functions
virtual Json::Value annotations ()
virtual void BuildNotify (Agent *m)
register a new child
virtual void BuildNotify (Agent *m)
register a new child
virtual cyclus::Agent * Clone ()
virtual void DecomNotify (Agent *m)
unregister a child
virtual void DecomNotify (Agent *m)
unregister a child
virtual void EnterNotify ()
enter the simulation and register any children present
virtual void EnterNotify ()
enter the simulation and register any children present
virtual void InfileToDb (cyclus::InfileTree *tree, cyclus::DbInit di)
virtual void InitFrom (cycamore::ManagerInst *m)
virtual void InitFrom (cyclus::QueryableBackend *b)
virtual void InitInv (cyclus::Inventories &inv)
ManagerInst (cyclus::Context *ctx)
Default constructor.
ManagerInst (cyclus::Context *ctx)
Default constructor.
virtual std::string schema ()
virtual void Snapshot (cyclus::DbInit di)
virtual cyclus::Inventories SnapshotInv ()
virtual std::string version ()
virtual std::string version ()
void WriteProducerInformation (cyclus::toolkit::CommodityProducer *producer)
write information about a commodity producer to a stream
void WriteProducerInformation (cyclus::toolkit::CommodityProducer *producer)
write information about a commodity producer to a stream
virtual ~ManagerInst ()
Default destructor.
virtual ~ManagerInst ()
Default destructor.
Private Member Functions
void RecordPosition ()
Records an agent's latitude and longitude to the output db.
void RecordPosition ()
Records an agent's latitude and longitude to the output db.
void Register_ (cyclus::Agent *agent)
register a child
void Register_ (cyclus::Agent *agent)
register a child
void Unregister_ (cyclus::Agent *agent)
unregister a child
void Unregister_ (cyclus::Agent *agent)
unregister a child
Private Attributes
cyclus::toolkit::Position coordinates
std::vector< int > cycpp_shape_latitude
std::vector< int > cycpp_shape_longitude
std::vector< int > cycpp_shape_prototypes
double latitude
double longitude
std::vector< std::string > prototypes
Detailed Description
Introduction
Detailed Behavior
Warning
The ManagerInst is experimental
Definition at line 15 of file _tmp_build/cycamore/manager_inst.h.
Constructor & Destructor Documentation
ManagerInst() [1/2]
cycamore::ManagerInst::ManagerInst (cyclus::Context * ctx)
Default constructor.
Definition at line 8 of file _tmp_build/cycamore/manager_inst.cc.
Referenced by cycamore::ConstructManagerInst().
~ManagerInst() [1/2]
cycamore::ManagerInst::~ManagerInst () virtual
Default destructor.
Definition at line 15 of file _tmp_build/cycamore/manager_inst.cc.
ManagerInst() [2/2]
cycamore::ManagerInst::ManagerInst (cyclus::Context * ctx)
Default constructor.
~ManagerInst() [2/2]
virtual cycamore::ManagerInst::~ManagerInst () virtual
Default destructor.
Member Function Documentation
annotations()
virtual Json::Value cycamore::ManagerInst::annotations () inline virtual
Definition at line 138 of file _tmp_build/cycamore/manager_inst.h.
BuildNotify() [1/2]
virtual void cycamore::ManagerInst::BuildNotify (Agent * m) virtual
register a new child
BuildNotify() [2/2]
void cycamore::ManagerInst::BuildNotify (Agent * m) virtual
register a new child
Definition at line 17 of file _tmp_build/cycamore/manager_inst.cc.
References Register_().
Referenced by Snapshot(), and version().
Clone()
virtual cyclus::Agent* cycamore::ManagerInst::Clone () inline virtual
Definition at line 109 of file _tmp_build/cycamore/manager_inst.h.
References InitFrom().
DecomNotify() [1/2]
virtual void cycamore::ManagerInst::DecomNotify (Agent * m) virtual
unregister a child
DecomNotify() [2/2]
void cycamore::ManagerInst::DecomNotify (Agent * m) virtual
unregister a child
Definition at line 21 of file _tmp_build/cycamore/manager_inst.cc.
References Unregister_().
Referenced by Snapshot(), and version().
EnterNotify() [1/2]
virtual void cycamore::ManagerInst::EnterNotify () virtual
enter the simulation and register any children present
EnterNotify() [2/2]
void cycamore::ManagerInst::EnterNotify () virtual
enter the simulation and register any children present
Definition at line 25 of file _tmp_build/cycamore/manager_inst.cc.
References prototypes, RecordPosition(), Register_(), and Unregister_().
Referenced by Snapshot(), and version().
InfileToDb()
virtual void cycamore::ManagerInst::InfileToDb (cyclus::InfileTree * tree, cyclus::DbInit di) inline virtual
Definition at line 57 of file _tmp_build/cycamore/manager_inst.h.
References cycpp_shape_latitude, cycpp_shape_longitude, cycpp_shape_prototypes, latitude, longitude, prototypes, and cycamore::string.
InitFrom() [1/2]
virtual void cycamore::ManagerInst::InitFrom (cycamore::ManagerInst * m) inline virtual
Definition at line 28 of file _tmp_build/cycamore/manager_inst.h.
References cycpp_shape_latitude, cycpp_shape_longitude, cycpp_shape_prototypes, latitude, longitude, and prototypes.
Referenced by Clone().
InitFrom() [2/2]
virtual void cycamore::ManagerInst::InitFrom (cyclus::QueryableBackend * b) inline virtual
Definition at line 42 of file _tmp_build/cycamore/manager_inst.h.
References cycpp_shape_latitude, cycpp_shape_longitude, cycpp_shape_prototypes, latitude, longitude, and prototypes.
InitInv()
virtual void cycamore::ManagerInst::InitInv (cyclus::Inventories & inv) inline virtual
Definition at line 180 of file _tmp_build/cycamore/manager_inst.h.
RecordPosition() [1/2]
void cycamore::ManagerInst::RecordPosition () private
Records an agent's latitude and longitude to the output db.
RecordPosition() [2/2]
void cycamore::ManagerInst::RecordPosition () private
Records an agent's latitude and longitude to the output db.
Definition at line 93 of file _tmp_build/cycamore/manager_inst.cc.
References latitude, longitude, and cycamore::string.
Referenced by EnterNotify(), and version().
Register_() [1/2]
void cycamore::ManagerInst::Register_ (cyclus::Agent * agent) private
register a child
Register_() [2/2]
void cycamore::ManagerInst::Register_ (cyclus::Agent * agent) private
register a child
Referenced by BuildNotify(), EnterNotify(), Snapshot(), and version().
schema()
virtual std::string cycamore::ManagerInst::schema () inline virtual
Definition at line 115 of file _tmp_build/cycamore/manager_inst.h.
Snapshot()
virtual void cycamore::ManagerInst::Snapshot (cyclus::DbInit di) inline virtual
Definition at line 188 of file _tmp_build/cycamore/manager_inst.h.
References BuildNotify(), cycpp_shape_latitude, cycpp_shape_longitude, cycpp_shape_prototypes, DecomNotify(), EnterNotify(), latitude, longitude, prototypes, Register_(), Unregister_(), and WriteProducerInformation().
SnapshotInv()
virtual cyclus::Inventories cycamore::ManagerInst::SnapshotInv () inline virtual
Definition at line 183 of file _tmp_build/cycamore/manager_inst.h.
Unregister_() [1/2]
void cycamore::ManagerInst::Unregister_ (cyclus::Agent * agent) private
unregister a child
Unregister_() [2/2]
void cycamore::ManagerInst::Unregister_ (cyclus::Agent * agent) private
unregister a child
Referenced by DecomNotify(), EnterNotify(), Snapshot(), and version().
version() [1/2]
virtual std::string cycamore::ManagerInst::version () inline virtual
Definition at line 25 of file src/manager_inst.h.
References BuildNotify(), coordinates, CYCAMORE_VERSION, DecomNotify(), EnterNotify(), latitude, longitude, prototypes, RecordPosition(), Register_(), Unregister_(), and WriteProducerInformation().
version() [2/2]
virtual std::string cycamore::ManagerInst::version () inline virtual
Definition at line 27 of file _tmp_build/cycamore/manager_inst.h.
References CYCAMORE_VERSION.
WriteProducerInformation() [1/2]
void cycamore::ManagerInst::WriteProducerInformation (cyclus::toolkit::CommodityProducer * producer)
write information about a commodity producer to a stream
Parameters
producer the producer
WriteProducerInformation() [2/2]
void cycamore::ManagerInst::WriteProducerInformation (cyclus::toolkit::CommodityProducer * producer)
write information about a commodity producer to a stream
Parameters
producer the producer
Definition at line 73 of file _tmp_build/cycamore/manager_inst.cc.
Referenced by Snapshot(), and version().
Member Data Documentation
coordinates
cyclus::toolkit::Position cycamore::ManagerInst::coordinates private
Definition at line 241 of file _tmp_build/cycamore/manager_inst.h.
Referenced by version().
cycpp_shape_latitude
std::vector<int> cycamore::ManagerInst::cycpp_shape_latitude private
Definition at line 230 of file _tmp_build/cycamore/manager_inst.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
cycpp_shape_longitude
std::vector<int> cycamore::ManagerInst::cycpp_shape_longitude private
Definition at line 237 of file _tmp_build/cycamore/manager_inst.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
cycpp_shape_prototypes
std::vector<int> cycamore::ManagerInst::cycpp_shape_prototypes private
Definition at line 223 of file _tmp_build/cycamore/manager_inst.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
latitude
double cycamore::ManagerInst::latitude private
Definition at line 229 of file _tmp_build/cycamore/manager_inst.h.
Referenced by InfileToDb(), InitFrom(), RecordPosition(), Snapshot(), and version().
longitude
double cycamore::ManagerInst::longitude private
Definition at line 236 of file _tmp_build/cycamore/manager_inst.h.
Referenced by InfileToDb(), InitFrom(), RecordPosition(), Snapshot(), and version().
prototypes
std::vector< std::string > cycamore::ManagerInst::prototypes private
Definition at line 222 of file _tmp_build/cycamore/manager_inst.h.
Referenced by EnterNotify(), InfileToDb(), InitFrom(), Snapshot(), and version().
The documentation for this class was generated from the following files:
_tmp_build/cycamore/manager_inst.h
_tmp_build/cycamore/manager_inst.cc