CYCAMORE: run_inputs.Summary Class Reference
run_inputs.Summary Class Reference
Public Member Functions
def __init__
def __init__
def __init__
def add_to_summary
def add_to_summary
def add_to_summary
def print_summary
def print_summary
def print_summary
Public Attributes
failed
passed
Detailed Description
An object to hold the results of all the tests
Definition at line 95 of file _tmp_build/bin/run_inputs.py.
Constructor & Destructor Documentation
def run_inputs.Summary.__init__ (self)
Definition at line 97 of file _tmp_build/bin/run_inputs.py.
Referenced by run_inputs.Summary.__init__().
def run_inputs.Summary.__init__ (self)
Definition at line 97 of file build/bin/run_inputs.py.
References run_inputs.Summary.__init__(), run_inputs.Summary.failed, and run_inputs.Summary.passed.
def run_inputs.Summary.__init__ (self)
Definition at line 97 of file tests/run_inputs.py.
References run_inputs.Summary.__init__(), run_inputs.Summary.failed, and run_inputs.Summary.passed.
Member Function Documentation
def run_inputs.Summary.add_to_summary (self, test_file)
Adds a test file to this summary object
Definition at line 101 of file _tmp_build/bin/run_inputs.py.
Referenced by run_inputs.Summary.add_to_summary().
def run_inputs.Summary.add_to_summary (self, test_file)
Adds a test file to this summary object
Definition at line 101 of file tests/run_inputs.py.
References run_inputs.Summary.add_to_summary().
def run_inputs.Summary.add_to_summary (self, test_file)
Adds a test file to this summary object
Definition at line 101 of file build/bin/run_inputs.py.
References run_inputs.Summary.add_to_summary().
def run_inputs.Summary.print_summary (self)
Prints the summary
Definition at line 108 of file build/bin/run_inputs.py.
References run_inputs.Summary.failed, run_inputs.Summary.passed, and run_inputs.Summary.print_summary().
def run_inputs.Summary.print_summary (self)
Prints the summary
Definition at line 108 of file _tmp_build/bin/run_inputs.py.
References run_inputs.Summary.failed, and run_inputs.Summary.passed.
Referenced by run_inputs.Summary.print_summary().
def run_inputs.Summary.print_summary (self)
Prints the summary
Definition at line 108 of file tests/run_inputs.py.
References run_inputs.Summary.failed, run_inputs.Summary.passed, and run_inputs.Summary.print_summary().
Member Data Documentation
run_inputs.Summary.failed
Definition at line 99 of file _tmp_build/bin/run_inputs.py.
Referenced by run_inputs.Summary.__init__(), and run_inputs.Summary.print_summary().
run_inputs.Summary.passed
Definition at line 98 of file _tmp_build/bin/run_inputs.py.
Referenced by run_inputs.Summary.__init__(), run_inputs.TestFile.__init__(), run_inputs.Summary.print_summary(), and run_inputs.TestFile.run().
The documentation for this class was generated from the following file:
_tmp_build/bin/run_inputs.py