CYCAMORE: SourceTest Class Reference
SourceTest Class Reference
#include <source_tests.h>
Public Member Functions
boost::shared_ptr
< cyclus::ExchangeContext
< cyclus::Material > > GetContext (int nreqs, std::string commodity)
boost::shared_ptr
< cyclus::ExchangeContext
< cyclus::Material > > GetContext (int nreqs, std::string commodity)
void InitParameters ()
void InitParameters ()
virtual void SetUp ()
virtual void SetUp ()
void SetUpSource ()
void SetUpSource ()
virtual void TearDown ()
virtual void TearDown ()
Public Attributes
double capacity
std::string commod
cyclus::Composition::Ptr recipe
std::string recipe_name
cycamore::Source * src_facility
cyclus::TestContext tc
TestFacility * trader
Detailed Description
Definition at line 16 of file build/cycamore/source_tests.h.
Member Function Documentation
boost::shared_ptr< cyclus::ExchangeContext< cyclus::Material > > SourceTest::GetContext (int nreqs, std::string commodity)
Definition at line 175 of file build/cycamore/source_tests.cc.
References trader.
boost::shared_ptr< cyclus::ExchangeContext<cyclus::Material> > SourceTest::GetContext (int nreqs, std::string commodity)
void SourceTest::InitParameters ()
void SourceTest::InitParameters ()
Definition at line 25 of file build/cycamore/source_tests.cc.
References capacity, commod, recipe, recipe_name, and tc.
Referenced by SetUp().
void SourceTest::SetUp () [virtual]
Definition at line 12 of file build/cycamore/source_tests.cc.
References InitParameters(), SetUpSource(), src_facility, tc, and trader.
virtual void SourceTest::SetUp () [virtual]
void SourceTest::SetUpSource ()
void SourceTest::SetUpSource ()
Definition at line 35 of file build/cycamore/source_tests.cc.
References capacity, cycamore::Source::Capacity(), commod, cycamore::Source::commodity(), cycamore::Source::recipe(), recipe_name, and src_facility.
Referenced by SetUp().
virtual void SourceTest::TearDown () [virtual]
void SourceTest::TearDown () [virtual]
Definition at line 20 of file build/cycamore/source_tests.cc.
References src_facility.
Member Data Documentation
double SourceTest::capacity
Definition at line 22 of file build/cycamore/source_tests.h.
Referenced by InitParameters(), and SetUpSource().
std::string SourceTest::commod
Definition at line 21 of file build/cycamore/source_tests.h.
Referenced by InitParameters(), and SetUpSource().
cyclus::Composition::Ptr SourceTest::recipe
Definition at line 23 of file build/cycamore/source_tests.h.
Referenced by InitParameters().
std::string SourceTest::recipe_name
Definition at line 21 of file build/cycamore/source_tests.h.
Referenced by InitParameters(), and SetUpSource().
cycamore::Source * SourceTest::src_facility
Definition at line 20 of file build/cycamore/source_tests.h.
Referenced by SetUp(), SetUpSource(), and TearDown().
cyclus::TestContext SourceTest::tc
Definition at line 18 of file build/cycamore/source_tests.h.
Referenced by InitParameters(), and SetUp().
TestFacility * SourceTest::trader
Definition at line 19 of file build/cycamore/source_tests.h.
Referenced by GetContext(), and SetUp().
The documentation for this class was generated from the following files:
build/cycamore/source_tests.h
src/source_tests.h
build/cycamore/source_tests.cc
src/source_tests.cc