CYCAMORE: cycamore::Enrichment Class Reference
cycamore::Enrichment Class Reference
The Enrichment facility is a simple Agent that enriches natural uranium in a Cyclus simulation.
#include <enrichment.h>
Public Member Functions
virtual void AcceptMatlTrades (const std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > &responses)
The Enrichment place accepted trade Materials in their Inventory.
virtual void AcceptMatlTrades (const std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > &responses)
The Enrichment place accepted trade Materials in their Inventory.
virtual void AdjustMatlPrefs (cyclus::PrefMap< cyclus::Material >::type &prefs)
The Enrichment adjusts preferences for offers of natural uranium it has received to maximize U-235 content Any offers that have zero U-235 content are not accepted.
virtual void AdjustMatlPrefs (cyclus::PrefMap< cyclus::Material >::type &prefs)
The Enrichment adjusts preferences for offers of natural uranium it has received to maximize U-235 content Any offers that have zero U-235 content are not accepted.
virtual Json::Value annotations ()
virtual void Build (cyclus::Agent *parent)
perform module-specific tasks when entering the simulation
virtual void Build (cyclus::Agent *parent)
perform module-specific tasks when entering the simulation
virtual cyclus::Agent * Clone ()
Enrichment (cyclus::Context *ctx)
Constructor for the Enrichment class.
Enrichment (cyclus::Context *ctx)
Constructor for the Enrichment class.
virtual std::set< cyclus::BidPortfolio< cyclus::Material >::Ptr > GetMatlBids (cyclus::CommodMap< cyclus::Material >::type &commod_requests)
Responds to each request for this facility's commodity.
virtual std::set< cyclus::BidPortfolio< cyclus::Material >::Ptr > GetMatlBids (cyclus::CommodMap< cyclus::Material >::type &commod_requests)
Responds to each request for this facility's commodity.
virtual std::set< cyclus::RequestPortfolio< cyclus::Material >::Ptr > GetMatlRequests ()
The Enrichment request Materials of its given commodity.
virtual std::set< cyclus::RequestPortfolio< cyclus::Material >::Ptr > GetMatlRequests ()
The Enrichment request Materials of its given commodity.
virtual void GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > &trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > &responses)
respond to each trade with a material enriched to the appropriate level given this facility's inventory
virtual void GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > &trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > &responses)
respond to each trade with a material enriched to the appropriate level given this facility's inventory
virtual void InfileToDb (cyclus::InfileTree *tree, cyclus::DbInit di)
virtual void InitFrom (cycamore::Enrichment *m)
virtual void InitFrom (cyclus::QueryableBackend *b)
virtual void InitInv (cyclus::Inventories &inv)
virtual std::string schema ()
void SetMaxInventorySize (double size)
void SetMaxInventorySize (double size)
virtual void Snapshot (cyclus::DbInit di)
virtual cyclus::Inventories SnapshotInv ()
virtual std::string str ()
Print information about this agent.
virtual std::string str ()
Print information about this agent.
void SwuCapacity (double capacity)
double SwuCapacity () const
void SwuCapacity (double capacity)
double SwuCapacity () const
const cyclus::toolkit::ResBuf< cyclus::Material > & Tails () const
const cyclus::toolkit::ResBuf< cyclus::Material > & Tails () const
virtual void Tick ()
Each facility is prompted to do its beginning-of-time-step stuff at the tick of the timer.
virtual void Tick ()
Each facility is prompted to do its beginning-of-time-step stuff at the tick of the timer.
virtual void Tock ()
Each facility is prompted to its end-of-time-step stuff on the tock of the timer.
virtual void Tock ()
Each facility is prompted to its end-of-time-step stuff on the tock of the timer.
bool ValidReq (const cyclus::Material::Ptr mat)
Determines if a particular material is a valid request to respond to.
bool ValidReq (const cyclus::Material::Ptr mat)
Determines if a particular material is a valid request to respond to.
virtual std::string version ()
virtual std::string version ()
virtual ~Enrichment ()
Destructor for the Enrichment class.
virtual ~Enrichment ()
Destructor for the Enrichment class.
Private Member Functions
void AddMat_ (cyclus::Material::Ptr mat)
adds a material into the natural uranium inventory
void AddMat_ (cyclus::Material::Ptr mat)
adds a material into the natural uranium inventory
cyclus::Material::Ptr Enrich_ (cyclus::Material::Ptr mat, double qty)
cyclus::Material::Ptr Enrich_ (cyclus::Material::Ptr mat, double qty)
double FeedAssay ()
calculates the feed assay based on the unenriched inventory
double FeedAssay ()
calculates the feed assay based on the unenriched inventory
cyclus::Material::Ptr Offer_ (cyclus::Material::Ptr req)
Generates a material offer for a given request.
cyclus::Material::Ptr Offer_ (cyclus::Material::Ptr req)
Generates a material offer for a given request.
void RecordEnrichment_ (double natural_u, double swu)
records and enrichment with the cyclus::Recorder
void RecordEnrichment_ (double natural_u, double swu)
records and enrichment with the cyclus::Recorder
void RecordPosition ()
Records an agent's latitude and longitude to the output db.
void RecordPosition ()
Records an agent's latitude and longitude to the output db.
cyclus::Material::Ptr Request_ ()
generates a request for this facility given its current state.
cyclus::Material::Ptr Request_ ()
generates a request for this facility given its current state.
Private Attributes
cyclus::toolkit::Position coordinates
double current_swu_capacity
std::vector< int > cycpp_shape_feed_commod
std::vector< int > cycpp_shape_feed_recipe
std::vector< int > cycpp_shape_initial_feed
std::vector< int > cycpp_shape_inventory
std::vector< int > cycpp_shape_latitude
std::vector< int > cycpp_shape_longitude
std::vector< int > cycpp_shape_max_enrich
std::vector< int > cycpp_shape_max_feed_inventory
std::vector< int > cycpp_shape_order_prefs
std::vector< int > cycpp_shape_product_commod
std::vector< int > cycpp_shape_swu_capacity
std::vector< int > cycpp_shape_tails
std::vector< int > cycpp_shape_tails_assay
std::vector< int > cycpp_shape_tails_commod
std::string feed_commod
std::string feed_recipe
double initial_feed
double intra_timestep_feed_
double intra_timestep_swu_
cyclus::toolkit::ResBuf< cyclus::Material > inventory
double latitude
double longitude
double max_enrich
double max_feed_inventory
bool order_prefs
std::string product_commod
double swu_capacity
cyclus::toolkit::ResBuf< cyclus::Material > tails
double tails_assay
std::string tails_commod
Friends
class EnrichmentTest
Detailed Description
The Enrichment facility is a simple Agent that enriches natural uranium in a Cyclus simulation.
It does not explicitly compute the physical enrichment process, rather it calculates the SWU required to convert an source uranium recipe (ie. natural uranium) into a requested enriched recipe (ie. 4% enriched uranium), given the natural uranium inventory constraint and its SWU capacity constraint.
The Enrichment facility requests an input commodity and associated recipe whose quantity is its remaining inventory capacity. All facilities trading the same input commodity (even with different recipes) will offer materials for trade. The Enrichment facility accepts any input materials with enrichments less than its tails assay, as long as some U235 is present, and preference increases with U235 content. If no U235 is present in the offered material, the trade preference is set to -1 and the material is not accepted. Any material components other other than U235 and U238 are sent directly to the tails buffer.
The Enrichment facility will bid on any request for its output commodity up to the maximum allowed enrichment (if not specified, default is 100%) It bids on either the request quantity, or the maximum quanity allowed by its SWU constraint or natural uranium inventory, whichever is lower. If multiple output commodities with different enrichment levels are requested and the facility does not have the SWU or quantity capacity to meet all requests, the requests are fully, then partially filled in unspecified but repeatable order.
The Enrichment facility also offers its tails as an output commodity with no associated recipe. Bids for tails are constrained only by total tails inventory.
Definition at line 120 of file _tmp_build/cycamore/enrichment.h.
Constructor & Destructor Documentation
Enrichment() [1/2]
cycamore::Enrichment::Enrichment (cyclus::Context * ctx)
Constructor for the Enrichment class.
Parameters
ctx the cyclus context for access to simulation-wide parameters
Definition at line 16 of file _tmp_build/cycamore/enrichment.cc.
Referenced by cycamore::ConstructEnrichment().
~Enrichment() [1/2]
cycamore::Enrichment::~Enrichment () virtual
Destructor for the Enrichment class.
Definition at line 32 of file _tmp_build/cycamore/enrichment.cc.
Enrichment() [2/2]
cycamore::Enrichment::Enrichment (cyclus::Context * ctx)
Constructor for the Enrichment class.
Parameters
ctx the cyclus context for access to simulation-wide parameters
~Enrichment() [2/2]
virtual cycamore::Enrichment::~Enrichment () virtual
Destructor for the Enrichment class.
Member Function Documentation
AcceptMatlTrades() [1/2]
virtual void cycamore::Enrichment::AcceptMatlTrades (const std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > & responses) virtual
The Enrichment place accepted trade Materials in their Inventory.
AcceptMatlTrades() [2/2]
void cycamore::Enrichment::AcceptMatlTrades (const std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > & responses) virtual
The Enrichment place accepted trade Materials in their Inventory.
Definition at line 160 of file _tmp_build/cycamore/enrichment.cc.
References AddMat_().
AddMat_() [1/2]
void cycamore::Enrichment::AddMat_ (cyclus::Material::Ptr mat) private
adds a material into the natural uranium inventory
Exceptions
if the material is not the same composition as the feed_recipe
AddMat_() [2/2]
void cycamore::Enrichment::AddMat_ (cyclus::Material::Ptr mat) private
adds a material into the natural uranium inventory
Exceptions
if the material is not the same composition as the feed_recipe
Definition at line 303 of file _tmp_build/cycamore/enrichment.cc.
References feed_commod, and inventory.
Referenced by AcceptMatlTrades(), and cycamore::EnrichmentTest::DoAddMat().
AdjustMatlPrefs() [1/2]
virtual void cycamore::Enrichment::AdjustMatlPrefs (cyclus::PrefMap< cyclus::Material >::type & prefs) virtual
The Enrichment adjusts preferences for offers of natural uranium it has received to maximize U-235 content Any offers that have zero U-235 content are not accepted.
AdjustMatlPrefs() [2/2]
void cycamore::Enrichment::AdjustMatlPrefs (cyclus::PrefMap< cyclus::Material >::type & prefs) virtual
The Enrichment adjusts preferences for offers of natural uranium it has received to maximize U-235 content Any offers that have zero U-235 content are not accepted.
Definition at line 115 of file _tmp_build/cycamore/enrichment.cc.
References order_prefs, and cycamore::SortBids().
annotations()
virtual Json::Value cycamore::Enrichment::annotations () inline virtual
Definition at line 433 of file _tmp_build/cycamore/enrichment.h.
Build() [1/2]
virtual void cycamore::Enrichment::Build (cyclus::Agent * parent) virtual
perform module-specific tasks when entering the simulation
Build() [2/2]
void cycamore::Enrichment::Build (cyclus::Agent * parent) virtual
perform module-specific tasks when entering the simulation
Definition at line 47 of file _tmp_build/cycamore/enrichment.cc.
References feed_recipe, initial_feed, inventory, RecordPosition(), and str().
Clone()
virtual cyclus::Agent* cycamore::Enrichment::Clone () inline virtual
Definition at line 366 of file _tmp_build/cycamore/enrichment.h.
References InitFrom().
Enrich_() [1/2]
cyclus::Material::Ptr cycamore::Enrichment::Enrich_ (cyclus::Material::Ptr mat, double qty) private
Enrich_() [2/2]
cyclus::Material::Ptr cycamore::Enrichment::Enrich_ (cyclus::Material::Ptr mat, double qty) private
Definition at line 362 of file _tmp_build/cycamore/enrichment.cc.
References cycamore::NatUConverter::convert(), current_swu_capacity, FeedAssay(), intra_timestep_feed_, intra_timestep_swu_, inventory, RecordEnrichment_(), tails, and tails_assay.
Referenced by cycamore::EnrichmentTest::DoEnrich(), and GetMatlTrades().
FeedAssay() [1/2]
double cycamore::Enrichment::FeedAssay () private
calculates the feed assay based on the unenriched inventory
FeedAssay() [2/2]
double cycamore::Enrichment::FeedAssay () private
calculates the feed assay based on the unenriched inventory
Definition at line 459 of file _tmp_build/cycamore/enrichment.cc.
References inventory.
Referenced by Enrich_(), GetMatlBids(), and str().
GetMatlBids() [1/2]
virtual std::set<cyclus::BidPortfolio<cyclus::Material>::Ptr> cycamore::Enrichment::GetMatlBids (cyclus::CommodMap< cyclus::Material >::type & commod_requests) virtual
Responds to each request for this facility's commodity.
If a given request is more than this facility's inventory or SWU capacity, it will offer its minimum of its capacities.
GetMatlBids() [2/2]
std::set< cyclus::BidPortfolio< cyclus::Material >::Ptr > cycamore::Enrichment::GetMatlBids (cyclus::CommodMap< cyclus::Material >::type & commod_requests) virtual
Responds to each request for this facility's commodity.
If a given request is more than this facility's inventory or SWU capacity, it will offer its minimum of its capacities.
Definition at line 173 of file _tmp_build/cycamore/enrichment.cc.
References FeedAssay(), inventory, max_enrich, Offer_(), product_commod, swu_capacity, tails, tails_assay, tails_commod, and ValidReq().
GetMatlRequests() [1/2]
virtual std::set<cyclus::RequestPortfolio<cyclus::Material>::Ptr> cycamore::Enrichment::GetMatlRequests () virtual
The Enrichment request Materials of its given commodity.
GetMatlRequests() [2/2]
std::set< cyclus::RequestPortfolio< cyclus::Material >::Ptr > cycamore::Enrichment::GetMatlRequests () virtual
The Enrichment request Materials of its given commodity.
Definition at line 82 of file _tmp_build/cycamore/enrichment.cc.
References feed_commod, and Request_().
GetMatlTrades() [1/2]
virtual void cycamore::Enrichment::GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > & trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > & responses) virtual
respond to each trade with a material enriched to the appropriate level given this facility's inventory
Parameters
trades all trades in which this trader is the supplier
responses a container to populate with responses to each trade
GetMatlTrades() [2/2]
void cycamore::Enrichment::GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > & trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > & responses) virtual
respond to each trade with a material enriched to the appropriate level given this facility's inventory
Parameters
trades all trades in which this trader is the supplier
responses a container to populate with responses to each trade
Definition at line 258 of file _tmp_build/cycamore/enrichment.cc.
References current_swu_capacity, Enrich_(), intra_timestep_feed_, intra_timestep_swu_, product_commod, cycamore::string, tails, and tails_commod.
Referenced by cycamore::TEST_F().
InfileToDb()
virtual void cycamore::Enrichment::InfileToDb (cyclus::InfileTree * tree, cyclus::DbInit di) inline virtual
Definition at line 229 of file _tmp_build/cycamore/enrichment.h.
References cycamore::latitude, cycamore::longitude, and cycamore::string.
InitFrom() [1/2]
virtual void cycamore::Enrichment::InitFrom (cycamore::Enrichment * m) inline virtual
Definition at line 135 of file _tmp_build/cycamore/enrichment.h.
References feed_commod, feed_recipe, initial_feed, inventory, cycamore::latitude, latitude, cycamore::longitude, longitude, max_enrich, max_feed_inventory, order_prefs, product_commod, swu_capacity, tails, tails_assay, and tails_commod.
Referenced by Clone().
InitFrom() [2/2]
virtual void cycamore::Enrichment::InitFrom (cyclus::QueryableBackend * b) inline virtual
Definition at line 182 of file _tmp_build/cycamore/enrichment.h.
References cycamore::latitude, cycamore::longitude, and cycamore::string.
InitInv()
virtual void cycamore::Enrichment::InitInv (cyclus::Inventories & inv) inline virtual
Definition at line 562 of file _tmp_build/cycamore/enrichment.h.
Offer_() [1/2]
cyclus::Material::Ptr cycamore::Enrichment::Offer_ (cyclus::Material::Ptr req) private
Generates a material offer for a given request.
The response composition will be comprised only of U235 and U238 at their relative ratio in the requested material. The response quantity will be the same as the requested commodity.
Parameters
req the requested material being responded to
Offer_() [2/2]
cyclus::Material::Ptr cycamore::Enrichment::Offer_ (cyclus::Material::Ptr req) private
Generates a material offer for a given request.
The response composition will be comprised only of U235 and U238 at their relative ratio in the requested material. The response quantity will be the same as the requested commodity.
Parameters
req the requested material being responded to
Definition at line 353 of file _tmp_build/cycamore/enrichment.cc.
Referenced by cycamore::EnrichmentTest::DoOffer(), and GetMatlBids().
RecordEnrichment_() [1/2]
void cycamore::Enrichment::RecordEnrichment_ (double natural_u, double swu) private
records and enrichment with the cyclus::Recorder
RecordEnrichment_() [2/2]
void cycamore::Enrichment::RecordEnrichment_ (double natural_u, double swu) private
records and enrichment with the cyclus::Recorder
Definition at line 441 of file _tmp_build/cycamore/enrichment.cc.
Referenced by Enrich_().
RecordPosition() [1/2]
void cycamore::Enrichment::RecordPosition () private
Records an agent's latitude and longitude to the output db.
RecordPosition() [2/2]
void cycamore::Enrichment::RecordPosition () private
Records an agent's latitude and longitude to the output db.
Definition at line 473 of file _tmp_build/cycamore/enrichment.cc.
References latitude, longitude, and cycamore::string.
Referenced by Build().
Request_() [1/2]
cyclus::Material::Ptr cycamore::Enrichment::Request_ () private
generates a request for this facility given its current state.
Quantity of the material will be equal to remaining inventory size.
Request_() [2/2]
cyclus::Material::Ptr cycamore::Enrichment::Request_ () private
generates a request for this facility given its current state.
Quantity of the material will be equal to remaining inventory size.
Definition at line 346 of file _tmp_build/cycamore/enrichment.cc.
References feed_recipe, and inventory.
Referenced by cycamore::EnrichmentTest::DoRequest(), and GetMatlRequests().
schema()
virtual std::string cycamore::Enrichment::schema () inline virtual
Definition at line 372 of file _tmp_build/cycamore/enrichment.h.
SetMaxInventorySize() [1/2]
void cycamore::Enrichment::SetMaxInventorySize (double size) inline
Definition at line 229 of file src/enrichment.h.
SetMaxInventorySize() [2/2]
void cycamore::Enrichment::SetMaxInventorySize (double size) inline
Definition at line 657 of file _tmp_build/cycamore/enrichment.h.
Referenced by cycamore::EnrichmentTest::SetUpSource(), and cycamore::TEST_F().
Snapshot()
virtual void cycamore::Enrichment::Snapshot (cyclus::DbInit di) inline virtual
Definition at line 577 of file _tmp_build/cycamore/enrichment.h.
References cycamore::latitude, cycamore::longitude, and cycamore::string.
SnapshotInv()
virtual cyclus::Inventories cycamore::Enrichment::SnapshotInv () inline virtual
Definition at line 568 of file _tmp_build/cycamore/enrichment.h.
str() [1/2]
virtual std::string cycamore::Enrichment::str () virtual
Print information about this agent.
str() [2/2]
std::string cycamore::Enrichment::str () virtual
Print information about this agent.
Definition at line 35 of file _tmp_build/cycamore/enrichment.cc.
References feed_commod, FeedAssay(), product_commod, SwuCapacity(), tails_assay, and tails_commod.
Referenced by Build().
SwuCapacity() [1/4]
void cycamore::Enrichment::SwuCapacity (double capacity) inline
Definition at line 234 of file src/enrichment.h.
SwuCapacity() [2/4]
double cycamore::Enrichment::SwuCapacity () const inline
Definition at line 239 of file src/enrichment.h.
SwuCapacity() [3/4]
void cycamore::Enrichment::SwuCapacity (double capacity) inline
Definition at line 662 of file _tmp_build/cycamore/enrichment.h.
Referenced by cycamore::EnrichmentTest::SetUpSource(), and cycamore::TEST_F().
SwuCapacity() [4/4]
double cycamore::Enrichment::SwuCapacity () const inline
Definition at line 667 of file _tmp_build/cycamore/enrichment.h.
Referenced by str(), and Tick().
Tails() [1/2]
const cyclus::toolkit::ResBuf<cyclus::Material>& cycamore::Enrichment::Tails () const inline
Definition at line 241 of file src/enrichment.h.
References cycamore::coordinates, cycamore::latitude, cycamore::longitude, cycamore::RecordPosition(), and cycamore::string.
Tails() [2/2]
const cyclus::toolkit::ResBuf<cyclus::Material>& cycamore::Enrichment::Tails () const inline
Definition at line 669 of file _tmp_build/cycamore/enrichment.h.
References cycamore::RecordPosition().
Referenced by cycamore::TEST_F().
Tick() [1/2]
virtual void cycamore::Enrichment::Tick () virtual
Each facility is prompted to do its beginning-of-time-step stuff at the tick of the timer.
Parameters
time is the time to perform the tick
Tick() [2/2]
void cycamore::Enrichment::Tick () virtual
Each facility is prompted to do its beginning-of-time-step stuff at the tick of the timer.
Parameters
time is the time to perform the tick
Definition at line 63 of file _tmp_build/cycamore/enrichment.cc.
References current_swu_capacity, and SwuCapacity().
Tock() [1/2]
virtual void cycamore::Enrichment::Tock () virtual
Each facility is prompted to its end-of-time-step stuff on the tock of the timer.
Parameters
time is the time to perform the tock
Tock() [2/2]
void cycamore::Enrichment::Tock () virtual
Each facility is prompted to its end-of-time-step stuff on the tock of the timer.
Parameters
time is the time to perform the tock
Definition at line 69 of file _tmp_build/cycamore/enrichment.cc.
References feed_commod, intra_timestep_feed_, and intra_timestep_swu_.
ValidReq() [1/2]
bool cycamore::Enrichment::ValidReq (const cyclus::Material::Ptr mat)
Determines if a particular material is a valid request to respond to.
Valid requests must contain U235 and U238 and must have a relative U235-to-U238 ratio less than this facility's tails_assay().
Returns
true if the above description is met by the material
ValidReq() [2/2]
bool cycamore::Enrichment::ValidReq (const cyclus::Material::Ptr mat)
Determines if a particular material is a valid request to respond to.
Valid requests must contain U235 and U238 and must have a relative U235-to-U238 ratio less than this facility's tails_assay().
Returns
true if the above description is met by the material
Definition at line 250 of file _tmp_build/cycamore/enrichment.cc.
References tails_assay.
Referenced by GetMatlBids(), and cycamore::TEST_F().
version() [1/2]
virtual std::string cycamore::Enrichment::version () inline virtual
Definition at line 134 of file _tmp_build/cycamore/enrichment.h.
References CYCAMORE_VERSION.
version() [2/2]
virtual std::string cycamore::Enrichment::version () inline virtual
Definition at line 163 of file src/enrichment.h.
References CYCAMORE_VERSION, and cycamore::string.
Friends And Related Function Documentation
EnrichmentTest
EnrichmentTest friend
Definition at line 789 of file _tmp_build/cycamore/enrichment.h.
Member Data Documentation
coordinates
cyclus::toolkit::Position cycamore::Enrichment::coordinates private
Definition at line 806 of file _tmp_build/cycamore/enrichment.h.
current_swu_capacity
double cycamore::Enrichment::current_swu_capacity private
Definition at line 771 of file _tmp_build/cycamore/enrichment.h.
Referenced by Enrich_(), GetMatlTrades(), and Tick().
cycpp_shape_feed_commod
std::vector<int> cycamore::Enrichment::cycpp_shape_feed_commod private
Definition at line 704 of file _tmp_build/cycamore/enrichment.h.
cycpp_shape_feed_recipe
std::vector<int> cycamore::Enrichment::cycpp_shape_feed_recipe private
Definition at line 711 of file _tmp_build/cycamore/enrichment.h.
cycpp_shape_initial_feed
std::vector<int> cycamore::Enrichment::cycpp_shape_initial_feed private
Definition at line 739 of file _tmp_build/cycamore/enrichment.h.
cycpp_shape_inventory
std::vector<int> cycamore::Enrichment::cycpp_shape_inventory private
Definition at line 775 of file _tmp_build/cycamore/enrichment.h.
cycpp_shape_latitude
std::vector<int> cycamore::Enrichment::cycpp_shape_latitude private
Definition at line 795 of file _tmp_build/cycamore/enrichment.h.
cycpp_shape_longitude
std::vector<int> cycamore::Enrichment::cycpp_shape_longitude private
Definition at line 802 of file _tmp_build/cycamore/enrichment.h.
cycpp_shape_max_enrich
std::vector<int> cycamore::Enrichment::cycpp_shape_max_enrich private
Definition at line 753 of file _tmp_build/cycamore/enrichment.h.
cycpp_shape_max_feed_inventory
std::vector<int> cycamore::Enrichment::cycpp_shape_max_feed_inventory private
Definition at line 746 of file _tmp_build/cycamore/enrichment.h.
cycpp_shape_order_prefs
std::vector<int> cycamore::Enrichment::cycpp_shape_order_prefs private
Definition at line 760 of file _tmp_build/cycamore/enrichment.h.
cycpp_shape_product_commod
std::vector<int> cycamore::Enrichment::cycpp_shape_product_commod private
Definition at line 718 of file _tmp_build/cycamore/enrichment.h.
cycpp_shape_swu_capacity
std::vector<int> cycamore::Enrichment::cycpp_shape_swu_capacity private
Definition at line 767 of file _tmp_build/cycamore/enrichment.h.
cycpp_shape_tails
std::vector<int> cycamore::Enrichment::cycpp_shape_tails private
Definition at line 780 of file _tmp_build/cycamore/enrichment.h.
cycpp_shape_tails_assay
std::vector<int> cycamore::Enrichment::cycpp_shape_tails_assay private
Definition at line 732 of file _tmp_build/cycamore/enrichment.h.
cycpp_shape_tails_commod
std::vector<int> cycamore::Enrichment::cycpp_shape_tails_commod private
Definition at line 725 of file _tmp_build/cycamore/enrichment.h.
feed_commod
std::string cycamore::Enrichment::feed_commod private
Definition at line 703 of file _tmp_build/cycamore/enrichment.h.
Referenced by AddMat_(), GetMatlRequests(), InitFrom(), cycamore::EnrichmentTest::SetUpSource(), str(), and Tock().
feed_recipe
std::string cycamore::Enrichment::feed_recipe private
Definition at line 710 of file _tmp_build/cycamore/enrichment.h.
Referenced by Build(), InitFrom(), Request_(), and cycamore::EnrichmentTest::SetUpSource().
initial_feed
double cycamore::Enrichment::initial_feed private
Definition at line 738 of file _tmp_build/cycamore/enrichment.h.
Referenced by Build(), InitFrom(), and cycamore::EnrichmentTest::SetUpSource().
intra_timestep_feed_
double cycamore::Enrichment::intra_timestep_feed_ private
Definition at line 787 of file _tmp_build/cycamore/enrichment.h.
Referenced by Enrich_(), GetMatlTrades(), and Tock().
intra_timestep_swu_
double cycamore::Enrichment::intra_timestep_swu_ private
Definition at line 786 of file _tmp_build/cycamore/enrichment.h.
Referenced by Enrich_(), GetMatlTrades(), and Tock().
inventory
cyclus::toolkit::ResBuf< cyclus::Material > cycamore::Enrichment::inventory private
Definition at line 774 of file _tmp_build/cycamore/enrichment.h.
Referenced by AddMat_(), Build(), Enrich_(), FeedAssay(), GetMatlBids(), InitFrom(), and Request_().
latitude
double cycamore::Enrichment::latitude private
Definition at line 794 of file _tmp_build/cycamore/enrichment.h.
Referenced by InitFrom(), and RecordPosition().
longitude
double cycamore::Enrichment::longitude private
Definition at line 801 of file _tmp_build/cycamore/enrichment.h.
Referenced by InitFrom(), and RecordPosition().
max_enrich
double cycamore::Enrichment::max_enrich private
Definition at line 752 of file _tmp_build/cycamore/enrichment.h.
Referenced by GetMatlBids(), InitFrom(), and cycamore::EnrichmentTest::SetUpSource().
max_feed_inventory
double cycamore::Enrichment::max_feed_inventory private
Definition at line 745 of file _tmp_build/cycamore/enrichment.h.
Referenced by InitFrom().
order_prefs
bool cycamore::Enrichment::order_prefs private
Definition at line 759 of file _tmp_build/cycamore/enrichment.h.
Referenced by AdjustMatlPrefs(), and InitFrom().
product_commod
std::string cycamore::Enrichment::product_commod private
Definition at line 717 of file _tmp_build/cycamore/enrichment.h.
Referenced by GetMatlBids(), GetMatlTrades(), InitFrom(), cycamore::EnrichmentTest::SetUpSource(), and str().
swu_capacity
double cycamore::Enrichment::swu_capacity private
Definition at line 766 of file _tmp_build/cycamore/enrichment.h.
Referenced by GetMatlBids(), and InitFrom().
tails
cyclus::toolkit::ResBuf< cyclus::Material > cycamore::Enrichment::tails private
Definition at line 779 of file _tmp_build/cycamore/enrichment.h.
Referenced by Enrich_(), GetMatlBids(), GetMatlTrades(), and InitFrom().
tails_assay
double cycamore::Enrichment::tails_assay private
Definition at line 731 of file _tmp_build/cycamore/enrichment.h.
Referenced by Enrich_(), GetMatlBids(), InitFrom(), cycamore::EnrichmentTest::SetUpSource(), str(), and ValidReq().
tails_commod
std::string cycamore::Enrichment::tails_commod private
Definition at line 724 of file _tmp_build/cycamore/enrichment.h.
Referenced by GetMatlBids(), GetMatlTrades(), InitFrom(), cycamore::EnrichmentTest::SetUpSource(), and str().
The documentation for this class was generated from the following files:
_tmp_build/cycamore/enrichment.h
_tmp_build/cycamore/enrichment.cc