CYCAMORE: test_regression._Recycle Class Reference
test_regression._Recycle Class Reference
Public Member Functions
def __init__ (self, args, kwargs)
def do_compare (self, fromfac, tofac, nuclide, exp_invs)
def test_pu239_reactor_repo (self)
def test_pu239_sep_repo (self)
Public Member Functions inherited from test_regression.TestRegression
def __init__ (self, args, kwargs)
def find_ids (self, spec, a, spec_col="Spec", id_col="AgentId")
def setUp (self)
def tearDown (self)
def to_ary (self, a, k)
Public Attributes
ext
outf
sql
Public Attributes inherited from test_regression.TestRegression
agent_entry
agent_exit
compositions
conn
cur
enrichments
ext
inf
info
outf
resources
rsrc_qtys
transactions
Detailed Description
This class tests the input/recycle.xml file.
Definition at line 408 of file test_regression.py.
Constructor & Destructor Documentation
def test_regression._Recycle.__init__ (self, args, kwargs)
Definition at line 411 of file test_regression.py.
References test_regression.TestRegression.outf.
Member Function Documentation
def test_regression._Recycle.do_compare (self, fromfac, tofac, nuclide, exp_invs)
Definition at line 428 of file test_regression.py.
References test_regression.TestRegression.outf, and test_regression._Recycle.sql.
Referenced by test_regression._Recycle.test_pu239_reactor_repo(), and test_regression._Recycle.test_pu239_sep_repo().
def test_regression._Recycle.test_pu239_reactor_repo (self)
Definition at line 491 of file test_regression.py.
References test_regression._Recycle.do_compare().
def test_regression._Recycle.test_pu239_sep_repo (self)
Definition at line 457 of file test_regression.py.
References test_regression._Recycle.do_compare().
Member Data Documentation
test_regression._Recycle.ext
Definition at line 417 of file test_regression.py.
test_regression._Recycle.outf
Definition at line 418 of file test_regression.py.
test_regression._Recycle.sql
Definition at line 419 of file test_regression.py.
Referenced by test_regression._Recycle.do_compare().
The documentation for this class was generated from the following file:
test_regression.py