CYCAMORE: cycamore::Reactor Class Reference
cycamore::Reactor Class Reference
Reactor is a simple, general reactor based on static compositional transformations to model fuel burnup.
#include <reactor.h>
Public Member Functions
virtual void AcceptMatlTrades (const std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > &responses)
virtual void AcceptMatlTrades (const std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > &responses)
virtual Json::Value annotations ()
virtual bool CheckDecommissionCondition ()
virtual bool CheckDecommissionCondition ()
virtual cyclus::Agent * Clone ()
virtual void EnterNotify ()
virtual void EnterNotify ()
virtual std::set< cyclus::BidPortfolio< cyclus::Material >::Ptr > GetMatlBids (cyclus::CommodMap< cyclus::Material >::type &commod_requests)
virtual std::set< cyclus::BidPortfolio< cyclus::Material >::Ptr > GetMatlBids (cyclus::CommodMap< cyclus::Material >::type &commod_requests)
virtual std::set< cyclus::RequestPortfolio< cyclus::Material >::Ptr > GetMatlRequests ()
virtual std::set< cyclus::RequestPortfolio< cyclus::Material >::Ptr > GetMatlRequests ()
virtual void GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > &trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > &responses)
virtual void GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > &trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > &responses)
virtual void InfileToDb (cyclus::InfileTree *tree, cyclus::DbInit di)
virtual void InitFrom (cycamore::Reactor *m)
virtual void InitFrom (cyclus::QueryableBackend *b)
virtual void InitInv (cyclus::Inventories &inv)
Reactor (cyclus::Context *ctx)
Reactor (cyclus::Context *ctx)
virtual std::string schema ()
virtual void Snapshot (cyclus::DbInit di)
virtual cyclus::Inventories SnapshotInv ()
virtual void Tick ()
virtual void Tick ()
virtual void Tock ()
virtual void Tock ()
virtual std::string version ()
virtual std::string version ()
virtual ~Reactor ()
virtual ~Reactor ()
Private Member Functions
bool Discharge ()
Discharge a batch from the core if there is room in the spent fuel inventory.
bool Discharge ()
Discharge a batch from the core if there is room in the spent fuel inventory.
std::string fuel_incommod (cyclus::Material::Ptr m)
std::string fuel_incommod (cyclus::Material::Ptr m)
std::string fuel_inrecipe (cyclus::Material::Ptr m)
std::string fuel_inrecipe (cyclus::Material::Ptr m)
std::string fuel_outcommod (cyclus::Material::Ptr m)
std::string fuel_outcommod (cyclus::Material::Ptr m)
std::string fuel_outrecipe (cyclus::Material::Ptr m)
std::string fuel_outrecipe (cyclus::Material::Ptr m)
double fuel_pref (cyclus::Material::Ptr m)
double fuel_pref (cyclus::Material::Ptr m)
void index_res (cyclus::Resource::Ptr m, std::string incommod)
Store fuel info index for the given resource received on incommod.
void index_res (cyclus::Resource::Ptr m, std::string incommod)
Store fuel info index for the given resource received on incommod.
void Load ()
Top up core inventory as much as possible.
void Load ()
Top up core inventory as much as possible.
std::map< std::string, cyclus::toolkit::MatVec > PeekSpent ()
Returns all spent assemblies indexed by outcommod without removing them from the spent fuel buffer.
std::map< std::string, cyclus::toolkit::MatVec > PeekSpent ()
Returns all spent assemblies indexed by outcommod without removing them from the spent fuel buffer.
std::map< std::string, cyclus::toolkit::MatVec > PopSpent ()
Returns all spent assemblies indexed by outcommod - removing them from the spent fuel buffer.
std::map< std::string, cyclus::toolkit::MatVec > PopSpent ()
Returns all spent assemblies indexed by outcommod - removing them from the spent fuel buffer.
void PushSpent (std::map< std::string, cyclus::toolkit::MatVec > leftover)
Complement of PopSpent - must be called with all materials passed that were not traded away to other agents.
void PushSpent (std::map< std::string, cyclus::toolkit::MatVec > leftover)
Complement of PopSpent - must be called with all materials passed that were not traded away to other agents.
void Record (std::string name, std::string val)
Records a reactor event to the output db with the given name and note val.
void Record (std::string name, std::string val)
Records a reactor event to the output db with the given name and note val.
bool retired ()
bool retired ()
void Transmute ()
Transmute the batch that is about to be discharged from the core to its fully burnt state as defined by its outrecipe.
void Transmute (int n_assem)
Transmute the specified number of assemblies in the core to their fully burnt state as defined by their outrecipe.
void Transmute ()
Transmute the batch that is about to be discharged from the core to its fully burnt state as defined by its outrecipe.
void Transmute (int n_assem)
Transmute the specified number of assemblies in the core to their fully burnt state as defined by their outrecipe.
Private Attributes
double assem_size
cyclus::toolkit::ResBuf< cyclus::Material > core
int cycle_step
int cycle_time
std::vector< int > cycpp_shape_assem_size
std::vector< int > cycpp_shape_core
std::vector< int > cycpp_shape_cycle_step
std::vector< int > cycpp_shape_cycle_time
std::vector< int > cycpp_shape_discharged
std::vector< int > cycpp_shape_fresh
std::vector< int > cycpp_shape_fuel_incommods
std::vector< int > cycpp_shape_fuel_inrecipes
std::vector< int > cycpp_shape_fuel_outcommods
std::vector< int > cycpp_shape_fuel_outrecipes
std::vector< int > cycpp_shape_fuel_prefs
std::vector< int > cycpp_shape_n_assem_batch
std::vector< int > cycpp_shape_n_assem_core
std::vector< int > cycpp_shape_n_assem_fresh
std::vector< int > cycpp_shape_n_assem_spent
std::vector< int > cycpp_shape_power_cap
std::vector< int > cycpp_shape_power_name
std::vector< int > cycpp_shape_pref_change_commods
std::vector< int > cycpp_shape_pref_change_times
std::vector< int > cycpp_shape_pref_change_values
std::vector< int > cycpp_shape_recipe_change_commods
std::vector< int > cycpp_shape_recipe_change_in
std::vector< int > cycpp_shape_recipe_change_out
std::vector< int > cycpp_shape_recipe_change_times
std::vector< int > cycpp_shape_refuel_time
std::vector< int > cycpp_shape_res_indexes
std::vector< int > cycpp_shape_spent
bool discharged
cyclus::toolkit::ResBuf< cyclus::Material > fresh
std::vector< std::string > fuel_incommods
std::vector< std::string > fuel_inrecipes
std::vector< std::string > fuel_outcommods
std::vector< std::string > fuel_outrecipes
std::vector< double > fuel_prefs
int n_assem_batch
int n_assem_core
int n_assem_fresh
int n_assem_spent
double power_cap
std::string power_name
std::vector< std::string > pref_change_commods
std::vector< int > pref_change_times
std::vector< double > pref_change_values
std::vector< std::string > recipe_change_commods
std::vector< std::string > recipe_change_in
std::vector< std::string > recipe_change_out
std::vector< int > recipe_change_times
int refuel_time
std::map< int, int > res_indexes
cyclus::toolkit::ResBuf< cyclus::Material > spent
std::set< std::string > uniq_outcommods_
Detailed Description
Reactor is a simple, general reactor based on static compositional transformations to model fuel burnup.
The user specifies a set of input fuels and corresponding burnt compositions that fuel is transformed to when it is discharged from the core. No incremental transmutation takes place. Rather, at the end of an operational cycle, the batch being discharged from the core is instantaneously transmuted from its original fresh fuel composition into its spent fuel form.
Each fuel is identified by a specific input commodity and has an associated input recipe (nuclide composition), output recipe, output commidity, and preference. The preference identifies which input fuels are preferred when requesting. Changes in these preferences can be specified as a function of time using the pref_change variables. Changes in the input-output recipe compositions can also be specified as a function of time using the recipe_change variables.
The reactor treats fuel as individual assemblies that are never split, combined or otherwise treated in any non-discrete way. Fuel is requested in full-or-nothing assembly sized quanta. If real-world assembly modeling is unnecessary, parameters can be adjusted (e.g. n_assem_core, assem_size, n_assem_batch). At the end of every cycle, a full batch is discharged from the core consisting of n_assem_batch assemblies of assem_size kg. The reactor also has a specifiable refueling time period following the end of each cycle at the end of which it will resume operation on the next cycle if it has enough fuel for a full core; otherwise it waits until it has enough fresh fuel assemblies.
In addition to its core, the reactor has an on-hand fresh fuel inventory and a spent fuel inventory whose capacities are specified by n_assem_fresh and n_assem_spent respectively. Each time step the reactor will attempt to acquire enough fresh fuel to fill its fresh fuel inventory (and its core if the core isn't currently full). If the fresh fuel inventory has zero capacity, fuel will be ordered just-in-time after the end of each operational cycle before the next begins. If the spent fuel inventory becomes full, the reactor will halt operation at the end of the next cycle until there is more room. Each time step, the reactor will try to trade away as much of its spent fuel inventory as possible.
When the reactor reaches the end of its lifetime, it will discharge all material from its core and trade away all its spent fuel as quickly as possible. Full decommissioning will be delayed until all spent fuel is gone. If the reactor has a full core when it is decommissioned (i.e. is mid-cycle) when the reactor is decommissioned, half (rounded up to nearest int) of its assemblies are transmuted to their respective burnt compositions.
Definition at line 57 of file _tmp_build/cycamore/reactor.h.
Constructor & Destructor Documentation
cycamore::Reactor::Reactor (cyclus::Context * ctx)
Definition at line 15 of file _tmp_build/cycamore/reactor.cc.
Referenced by cycamore::ConstructReactor().
virtual cycamore::Reactor::~Reactor () inline virtual
Definition at line 64 of file _tmp_build/cycamore/reactor.h.
cycamore::Reactor::Reactor (cyclus::Context * ctx)
virtual cycamore::Reactor::~Reactor () inline virtual
Definition at line 110 of file src/reactor.h.
Member Function Documentation
virtual void cycamore::Reactor::AcceptMatlTrades (const std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > & responses) virtual
Referenced by GetMatlRequests(), and version().
virtual void cycamore::Reactor::AcceptMatlTrades (const std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > & responses) virtual
Json::Value cycamore::Reactor::annotations () virtual
Definition at line 182 of file _tmp_build/cycamore/reactor.cc.
Referenced by version().
bool cycamore::Reactor::CheckDecommissionCondition () virtual
Definition at line 1105 of file _tmp_build/cycamore/reactor.cc.
References core, and spent.
Referenced by version().
virtual bool cycamore::Reactor::CheckDecommissionCondition () virtual
cyclus::Agent * cycamore::Reactor::Clone () virtual
Definition at line 28 of file _tmp_build/cycamore/reactor.cc.
References InitFrom(), and m.
Referenced by version().
bool cycamore::Reactor::Discharge () private
Discharge a batch from the core if there is room in the spent fuel inventory.
Returns true if a batch was successfully discharged.
Definition at line 1399 of file _tmp_build/cycamore/reactor.cc.
References core, n_assem_batch, n_assem_spent, Record(), and spent.
Referenced by retired(), and Tick().
bool cycamore::Reactor::Discharge () private
Discharge a batch from the core if there is room in the spent fuel inventory.
Returns true if a batch was successfully discharged.
void cycamore::Reactor::EnterNotify () virtual
Definition at line 1062 of file _tmp_build/cycamore/reactor.cc.
References fuel_outcommods, fuel_prefs, pref_change_commods, pref_change_times, pref_change_values, recipe_change_commods, recipe_change_in, recipe_change_out, and recipe_change_times.
Referenced by version().
virtual void cycamore::Reactor::EnterNotify () virtual
std::string cycamore::Reactor::fuel_incommod (cyclus::Material::Ptr m) private
Referenced by Load(), and version().
std::string cycamore::Reactor::fuel_incommod (cyclus::Material::Ptr m) private
std::string cycamore::Reactor::fuel_inrecipe (cyclus::Material::Ptr m) private
Referenced by Load(), and version().
std::string cycamore::Reactor::fuel_inrecipe (cyclus::Material::Ptr m) private
std::string cycamore::Reactor::fuel_outcommod (cyclus::Material::Ptr m) private
Referenced by Load(), PeekSpent(), PopSpent(), and version().
std::string cycamore::Reactor::fuel_outcommod (cyclus::Material::Ptr m) private
std::string cycamore::Reactor::fuel_outrecipe (cyclus::Material::Ptr m) private
Referenced by Load(), Transmute(), and version().
std::string cycamore::Reactor::fuel_outrecipe (cyclus::Material::Ptr m) private
double cycamore::Reactor::fuel_pref (cyclus::Material::Ptr m) private
Referenced by Load(), and version().
double cycamore::Reactor::fuel_pref (cyclus::Material::Ptr m) private
virtual std::set<cyclus::BidPortfolio<cyclus::Material>::Ptr> cycamore::Reactor::GetMatlBids (cyclus::CommodMap< cyclus::Material >::type & commod_requests) virtual
Referenced by GetMatlRequests(), and version().
virtual std::set<cyclus::BidPortfolio<cyclus::Material>::Ptr> cycamore::Reactor::GetMatlBids (cyclus::CommodMap< cyclus::Material >::type & commod_requests) virtual
std::set< cyclus::RequestPortfolio< Material >::Ptr > cycamore::Reactor::GetMatlRequests () virtual
Definition at line 1196 of file _tmp_build/cycamore/reactor.cc.
References AcceptMatlTrades(), assem_size, cc, core, cycle_step, cycle_time, fresh, fuel_incommods, fuel_inrecipes, fuel_outcommods, fuel_prefs, GetMatlBids(), GetMatlTrades(), index_res(), m, n_assem_batch, n_assem_core, n_assem_fresh, PeekSpent(), PopSpent(), PushSpent(), Record(), refuel_time, res_indexes, retired(), cycamore::string, and uniq_outcommods_.
Referenced by version().
virtual std::set<cyclus::RequestPortfolio<cyclus::Material>::Ptr> cycamore::Reactor::GetMatlRequests () virtual
virtual void cycamore::Reactor::GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > & trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > & responses) virtual
Referenced by GetMatlRequests(), and version().
virtual void cycamore::Reactor::GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > & trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > & responses) virtual
void cycamore::Reactor::index_res (cyclus::Resource::Ptr m, std::string incommod) private
Store fuel info index for the given resource received on incommod.
Definition at line 1466 of file _tmp_build/cycamore/reactor.cc.
References fuel_incommods, and res_indexes.
Referenced by GetMatlRequests(), and retired().
void cycamore::Reactor::index_res (cyclus::Resource::Ptr m, std::string incommod) private
Store fuel info index for the given resource received on incommod.
void cycamore::Reactor::InfileToDb (cyclus::InfileTree * tree, cyclus::DbInit di) virtual
Definition at line 421 of file _tmp_build/cycamore/reactor.cc.
References assem_size, cycle_step, cycle_time, cycpp_shape_assem_size, cycpp_shape_core, cycpp_shape_cycle_step, cycpp_shape_cycle_time, cycpp_shape_discharged, cycpp_shape_fresh, cycpp_shape_fuel_incommods, cycpp_shape_fuel_inrecipes, cycpp_shape_fuel_outcommods, cycpp_shape_fuel_outrecipes, cycpp_shape_fuel_prefs, cycpp_shape_n_assem_batch, cycpp_shape_n_assem_core, cycpp_shape_n_assem_fresh, cycpp_shape_n_assem_spent, cycpp_shape_power_cap, cycpp_shape_power_name, cycpp_shape_pref_change_commods, cycpp_shape_pref_change_times, cycpp_shape_pref_change_values, cycpp_shape_recipe_change_commods, cycpp_shape_recipe_change_in, cycpp_shape_recipe_change_out, cycpp_shape_recipe_change_times, cycpp_shape_refuel_time, cycpp_shape_res_indexes, cycpp_shape_spent, discharged, fuel_incommods, fuel_inrecipes, fuel_outcommods, fuel_outrecipes, fuel_prefs, n_assem_batch, n_assem_core, n_assem_fresh, n_assem_spent, power_cap, power_name, pref_change_commods, pref_change_times, pref_change_values, recipe_change_commods, recipe_change_in, recipe_change_out, recipe_change_times, refuel_time, res_indexes, and cycamore::string.
Referenced by version().
void cycamore::Reactor::InitFrom (cycamore::Reactor * m) virtual
Definition at line 886 of file _tmp_build/cycamore/reactor.cc.
References assem_size, core, cycle_step, cycle_time, cycpp_shape_assem_size, cycpp_shape_core, cycpp_shape_cycle_step, cycpp_shape_cycle_time, cycpp_shape_discharged, cycpp_shape_fresh, cycpp_shape_fuel_incommods, cycpp_shape_fuel_inrecipes, cycpp_shape_fuel_outcommods, cycpp_shape_fuel_outrecipes, cycpp_shape_fuel_prefs, cycpp_shape_n_assem_batch, cycpp_shape_n_assem_core, cycpp_shape_n_assem_fresh, cycpp_shape_n_assem_spent, cycpp_shape_power_cap, cycpp_shape_power_name, cycpp_shape_pref_change_commods, cycpp_shape_pref_change_times, cycpp_shape_pref_change_values, cycpp_shape_recipe_change_commods, cycpp_shape_recipe_change_in, cycpp_shape_recipe_change_out, cycpp_shape_recipe_change_times, cycpp_shape_refuel_time, cycpp_shape_res_indexes, cycpp_shape_spent, discharged, fresh, fuel_incommods, fuel_inrecipes, fuel_outcommods, fuel_outrecipes, fuel_prefs, n_assem_batch, n_assem_core, n_assem_fresh, n_assem_spent, power_cap, power_name, pref_change_commods, pref_change_times, pref_change_values, recipe_change_commods, recipe_change_in, recipe_change_out, recipe_change_times, refuel_time, res_indexes, and spent.
Referenced by Clone(), and version().
void cycamore::Reactor::InitFrom (cyclus::QueryableBackend * b) virtual
Definition at line 972 of file _tmp_build/cycamore/reactor.cc.
References assem_size, core, cycle_step, cycle_time, cycpp_shape_assem_size, cycpp_shape_core, cycpp_shape_cycle_step, cycpp_shape_cycle_time, cycpp_shape_discharged, cycpp_shape_fresh, cycpp_shape_fuel_incommods, cycpp_shape_fuel_inrecipes, cycpp_shape_fuel_outcommods, cycpp_shape_fuel_outrecipes, cycpp_shape_fuel_prefs, cycpp_shape_n_assem_batch, cycpp_shape_n_assem_core, cycpp_shape_n_assem_fresh, cycpp_shape_n_assem_spent, cycpp_shape_power_cap, cycpp_shape_power_name, cycpp_shape_pref_change_commods, cycpp_shape_pref_change_times, cycpp_shape_pref_change_values, cycpp_shape_recipe_change_commods, cycpp_shape_recipe_change_in, cycpp_shape_recipe_change_out, cycpp_shape_recipe_change_times, cycpp_shape_refuel_time, cycpp_shape_res_indexes, cycpp_shape_spent, discharged, fresh, fuel_incommods, fuel_inrecipes, fuel_outcommods, fuel_outrecipes, fuel_prefs, n_assem_batch, n_assem_core, n_assem_fresh, n_assem_spent, power_cap, power_name, pref_change_commods, pref_change_times, pref_change_values, recipe_change_commods, recipe_change_in, recipe_change_out, recipe_change_times, refuel_time, res_indexes, spent, and cycamore::string.
void cycamore::Reactor::InitInv (cyclus::Inventories & inv) virtual
Definition at line 878 of file _tmp_build/cycamore/reactor.cc.
References core, fresh, and spent.
Referenced by version().
void cycamore::Reactor::Load () private
Top up core inventory as much as possible.
Definition at line 1414 of file _tmp_build/cycamore/reactor.cc.
References core, fresh, fuel_incommod(), fuel_incommods, fuel_inrecipe(), fuel_inrecipes, fuel_outcommod(), fuel_outcommods, fuel_outrecipe(), fuel_outrecipes, fuel_pref(), fuel_prefs, m, n_assem_core, Record(), res_indexes, and cycamore::string.
Referenced by retired(), and Tick().
void cycamore::Reactor::Load () private
Top up core inventory as much as possible.
std::map< std::string, MatVec > cycamore::Reactor::PeekSpent () private
Returns all spent assemblies indexed by outcommod without removing them from the spent fuel buffer.
Definition at line 1388 of file _tmp_build/cycamore/reactor.cc.
References fuel_outcommod(), spent, and cycamore::string.
Referenced by GetMatlRequests(), and retired().
std::map<std::string, cyclus::toolkit::MatVec> cycamore::Reactor::PeekSpent () private
Returns all spent assemblies indexed by outcommod without removing them from the spent fuel buffer.
std::map< std::string, MatVec > cycamore::Reactor::PopSpent () private
Returns all spent assemblies indexed by outcommod - removing them from the spent fuel buffer.
Definition at line 1477 of file _tmp_build/cycamore/reactor.cc.
References fuel_outcommod(), PushSpent(), spent, and cycamore::string.
Referenced by GetMatlRequests(), and retired().
std::map<std::string, cyclus::toolkit::MatVec> cycamore::Reactor::PopSpent () private
Returns all spent assemblies indexed by outcommod - removing them from the spent fuel buffer.
void cycamore::Reactor::PushSpent (std::map< std::string, cyclus::toolkit::MatVec > leftover) private
Complement of PopSpent - must be called with all materials passed that were not traded away to other agents.
Referenced by GetMatlRequests(), PopSpent(), and retired().
void cycamore::Reactor::PushSpent (std::map< std::string, cyclus::toolkit::MatVec > leftover) private
Complement of PopSpent - must be called with all materials passed that were not traded away to other agents.
void cycamore::Reactor::Record (std::string name, std::string val) private
Records a reactor event to the output db with the given name and note val.
Definition at line 1503 of file _tmp_build/cycamore/reactor.cc.
Referenced by Discharge(), GetMatlRequests(), Load(), retired(), Tick(), Tock(), and Transmute().
void cycamore::Reactor::Record (std::string name, std::string val) private
Records a reactor event to the output db with the given name and note val.
bool cycamore::Reactor::retired () inline private
Definition at line 113 of file _tmp_build/cycamore/reactor.h.
References Discharge(), index_res(), Load(), PeekSpent(), PopSpent(), PushSpent(), Record(), cycamore::string, and Transmute().
Referenced by GetMatlRequests(), Tick(), and Tock().
bool cycamore::Reactor::retired () inline private
Definition at line 142 of file src/reactor.h.
References assem_size, core, cycle_step, cycle_time, Discharge(), discharged, fresh, fuel_incommods, fuel_inrecipes, fuel_outcommods, fuel_outrecipes, fuel_prefs, index_res(), Load(), n_assem_batch, n_assem_core, n_assem_fresh, n_assem_spent, PeekSpent(), PopSpent(), power_cap, power_name, pref_change_commods, pref_change_times, pref_change_values, PushSpent(), recipe_change_commods, recipe_change_in, recipe_change_out, recipe_change_times, Record(), refuel_time, res_indexes, spent, cycamore::string, Transmute(), and uniq_outcommods_.
std::string cycamore::Reactor::schema () virtual
Definition at line 35 of file _tmp_build/cycamore/reactor.cc.
Referenced by version().
void cycamore::Reactor::Snapshot (cyclus::DbInit di) virtual
Definition at line 836 of file _tmp_build/cycamore/reactor.cc.
References assem_size, cycle_step, cycle_time, cycpp_shape_assem_size, cycpp_shape_cycle_step, cycpp_shape_cycle_time, cycpp_shape_discharged, cycpp_shape_fuel_incommods, cycpp_shape_fuel_inrecipes, cycpp_shape_fuel_outcommods, cycpp_shape_fuel_outrecipes, cycpp_shape_fuel_prefs, cycpp_shape_n_assem_batch, cycpp_shape_n_assem_core, cycpp_shape_n_assem_fresh, cycpp_shape_n_assem_spent, cycpp_shape_power_cap, cycpp_shape_power_name, cycpp_shape_pref_change_commods, cycpp_shape_pref_change_times, cycpp_shape_pref_change_values, cycpp_shape_recipe_change_commods, cycpp_shape_recipe_change_in, cycpp_shape_recipe_change_out, cycpp_shape_recipe_change_times, cycpp_shape_refuel_time, cycpp_shape_res_indexes, discharged, fuel_incommods, fuel_inrecipes, fuel_outcommods, fuel_outrecipes, fuel_prefs, n_assem_batch, n_assem_core, n_assem_fresh, n_assem_spent, power_cap, power_name, pref_change_commods, pref_change_times, pref_change_values, recipe_change_commods, recipe_change_in, recipe_change_out, recipe_change_times, refuel_time, and res_indexes.
Referenced by version().
cyclus::Inventories cycamore::Reactor::SnapshotInv () virtual
Definition at line 866 of file _tmp_build/cycamore/reactor.cc.
References core, fresh, and spent.
Referenced by version().
void cycamore::Reactor::Tick () virtual
Definition at line 1109 of file _tmp_build/cycamore/reactor.cc.
References assem_size, core, cycle_step, cycle_time, Discharge(), discharged, fresh, fuel_incommods, fuel_inrecipes, fuel_outrecipes, fuel_prefs, Load(), n_assem_core, power_cap, pref_change_commods, pref_change_times, pref_change_values, recipe_change_commods, recipe_change_in, recipe_change_out, recipe_change_times, Record(), retired(), spent, cycamore::string, and Transmute().
Referenced by version().
virtual void cycamore::Reactor::Tick () virtual
void cycamore::Reactor::Tock () virtual
Definition at line 1341 of file _tmp_build/cycamore/reactor.cc.
References core, cycle_step, cycle_time, discharged, n_assem_core, power_cap, Record(), refuel_time, and retired().
Referenced by version().
virtual void cycamore::Reactor::Tock () virtual
void cycamore::Reactor::Transmute () private
Transmute the batch that is about to be discharged from the core to its fully burnt state as defined by its outrecipe.
Definition at line 1369 of file _tmp_build/cycamore/reactor.cc.
References n_assem_batch.
Referenced by retired(), and Tick().
void cycamore::Reactor::Transmute (int n_assem) private
Transmute the specified number of assemblies in the core to their fully burnt state as defined by their outrecipe.
Definition at line 1371 of file _tmp_build/cycamore/reactor.cc.
References core, fuel_outrecipe(), and Record().
void cycamore::Reactor::Transmute () private
Transmute the batch that is about to be discharged from the core to its fully burnt state as defined by its outrecipe.
void cycamore::Reactor::Transmute (int n_assem) private
Transmute the specified number of assemblies in the core to their fully burnt state as defined by their outrecipe.
virtual std::string cycamore::Reactor::version () inline virtual
Definition at line 66 of file _tmp_build/cycamore/reactor.h.
References AcceptMatlTrades(), annotations(), CheckDecommissionCondition(), Clone(), CYCAMORE_VERSION, EnterNotify(), fuel_incommod(), fuel_inrecipe(), fuel_outcommod(), fuel_outrecipe(), fuel_pref(), GetMatlBids(), GetMatlRequests(), GetMatlTrades(), InfileToDb(), InitFrom(), InitInv(), m, schema(), Snapshot(), SnapshotInv(), cycamore::string, Tick(), and Tock().
virtual std::string cycamore::Reactor::version () inline virtual
Definition at line 112 of file src/reactor.h.
References AcceptMatlTrades(), CheckDecommissionCondition(), CYCAMORE_VERSION, EnterNotify(), fuel_incommod(), fuel_inrecipe(), fuel_outcommod(), fuel_outrecipe(), fuel_pref(), GetMatlBids(), GetMatlRequests(), GetMatlTrades(), m, cycamore::string, Tick(), and Tock().
Member Data Documentation
double cycamore::Reactor::assem_size private
Definition at line 206 of file _tmp_build/cycamore/reactor.h.
Referenced by GetMatlRequests(), InfileToDb(), InitFrom(), retired(), Snapshot(), and Tick().
cyclus::toolkit::ResBuf< cyclus::Material > cycamore::Reactor::core private
Definition at line 292 of file _tmp_build/cycamore/reactor.h.
Referenced by CheckDecommissionCondition(), Discharge(), GetMatlRequests(), InitFrom(), InitInv(), Load(), retired(), SnapshotInv(), Tick(), Tock(), and Transmute().
int cycamore::Reactor::cycle_step private
Definition at line 246 of file _tmp_build/cycamore/reactor.h.
Referenced by GetMatlRequests(), InfileToDb(), InitFrom(), retired(), Snapshot(), Tick(), and Tock().
int cycamore::Reactor::cycle_time private
Definition at line 236 of file _tmp_build/cycamore/reactor.h.
Referenced by GetMatlRequests(), InfileToDb(), InitFrom(), retired(), Snapshot(), Tick(), and Tock().
std::vector<int> cycamore::Reactor::cycpp_shape_assem_size private
Definition at line 207 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_core private
Definition at line 293 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), and InitFrom().
std::vector<int> cycamore::Reactor::cycpp_shape_cycle_step private
Definition at line 247 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_cycle_time private
Definition at line 237 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_discharged private
Definition at line 308 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_fresh private
Definition at line 288 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), and InitFrom().
std::vector<int> cycamore::Reactor::cycpp_shape_fuel_incommods private
Definition at line 154 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_fuel_inrecipes private
Definition at line 159 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_fuel_outcommods private
Definition at line 171 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_fuel_outrecipes private
Definition at line 176 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_fuel_prefs private
Definition at line 166 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_n_assem_batch private
Definition at line 214 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_n_assem_core private
Definition at line 219 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_n_assem_fresh private
Definition at line 224 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_n_assem_spent private
Definition at line 229 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_power_cap private
Definition at line 255 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_power_name private
Definition at line 262 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_pref_change_commods private
Definition at line 275 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_pref_change_times private
Definition at line 270 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_pref_change_values private
Definition at line 280 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_recipe_change_commods private
Definition at line 189 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_recipe_change_in private
Definition at line 194 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_recipe_change_out private
Definition at line 199 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_recipe_change_times private
Definition at line 184 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_refuel_time private
Definition at line 242 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_res_indexes private
Definition at line 317 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), and Snapshot().
std::vector<int> cycamore::Reactor::cycpp_shape_spent private
Definition at line 298 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), and InitFrom().
bool cycamore::Reactor::discharged private
Definition at line 307 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), retired(), Snapshot(), Tick(), and Tock().
cyclus::toolkit::ResBuf< cyclus::Material > cycamore::Reactor::fresh private
Definition at line 287 of file _tmp_build/cycamore/reactor.h.
Referenced by GetMatlRequests(), InitFrom(), InitInv(), Load(), retired(), SnapshotInv(), and Tick().
std::vector< std::string > cycamore::Reactor::fuel_incommods private
Definition at line 153 of file _tmp_build/cycamore/reactor.h.
Referenced by GetMatlRequests(), index_res(), InfileToDb(), InitFrom(), Load(), retired(), Snapshot(), and Tick().
std::vector< std::string > cycamore::Reactor::fuel_inrecipes private
Definition at line 158 of file _tmp_build/cycamore/reactor.h.
Referenced by GetMatlRequests(), InfileToDb(), InitFrom(), Load(), retired(), Snapshot(), and Tick().
std::vector< std::string > cycamore::Reactor::fuel_outcommods private
Definition at line 170 of file _tmp_build/cycamore/reactor.h.
Referenced by EnterNotify(), GetMatlRequests(), InfileToDb(), InitFrom(), Load(), retired(), and Snapshot().
std::vector< std::string > cycamore::Reactor::fuel_outrecipes private
Definition at line 175 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), Load(), retired(), Snapshot(), and Tick().
std::vector< double > cycamore::Reactor::fuel_prefs private
Definition at line 165 of file _tmp_build/cycamore/reactor.h.
Referenced by EnterNotify(), GetMatlRequests(), InfileToDb(), InitFrom(), Load(), retired(), Snapshot(), and Tick().
int cycamore::Reactor::n_assem_batch private
Definition at line 213 of file _tmp_build/cycamore/reactor.h.
Referenced by Discharge(), GetMatlRequests(), InfileToDb(), InitFrom(), retired(), Snapshot(), and Transmute().
int cycamore::Reactor::n_assem_core private
Definition at line 218 of file _tmp_build/cycamore/reactor.h.
Referenced by GetMatlRequests(), InfileToDb(), InitFrom(), Load(), retired(), Snapshot(), Tick(), and Tock().
int cycamore::Reactor::n_assem_fresh private
Definition at line 223 of file _tmp_build/cycamore/reactor.h.
Referenced by GetMatlRequests(), InfileToDb(), InitFrom(), retired(), and Snapshot().
int cycamore::Reactor::n_assem_spent private
Definition at line 228 of file _tmp_build/cycamore/reactor.h.
Referenced by Discharge(), InfileToDb(), InitFrom(), retired(), and Snapshot().
double cycamore::Reactor::power_cap private
Definition at line 254 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), retired(), Snapshot(), Tick(), and Tock().
std::string cycamore::Reactor::power_name private
Definition at line 261 of file _tmp_build/cycamore/reactor.h.
Referenced by InfileToDb(), InitFrom(), retired(), and Snapshot().
std::vector< std::string > cycamore::Reactor::pref_change_commods private
Definition at line 274 of file _tmp_build/cycamore/reactor.h.
Referenced by EnterNotify(), InfileToDb(), InitFrom(), retired(), Snapshot(), and Tick().
std::vector< int > cycamore::Reactor::pref_change_times private
Definition at line 269 of file _tmp_build/cycamore/reactor.h.
Referenced by EnterNotify(), InfileToDb(), InitFrom(), retired(), Snapshot(), and Tick().
std::vector< double > cycamore::Reactor::pref_change_values private
Definition at line 279 of file _tmp_build/cycamore/reactor.h.
Referenced by EnterNotify(), InfileToDb(), InitFrom(), retired(), Snapshot(), and Tick().
std::vector< std::string > cycamore::Reactor::recipe_change_commods private
Definition at line 188 of file _tmp_build/cycamore/reactor.h.
Referenced by EnterNotify(), InfileToDb(), InitFrom(), retired(), Snapshot(), and Tick().
std::vector< std::string > cycamore::Reactor::recipe_change_in private
Definition at line 193 of file _tmp_build/cycamore/reactor.h.
Referenced by EnterNotify(), InfileToDb(), InitFrom(), retired(), Snapshot(), and Tick().
std::vector< std::string > cycamore::Reactor::recipe_change_out private
Definition at line 198 of file _tmp_build/cycamore/reactor.h.
Referenced by EnterNotify(), InfileToDb(), InitFrom(), retired(), Snapshot(), and Tick().
std::vector< int > cycamore::Reactor::recipe_change_times private
Definition at line 183 of file _tmp_build/cycamore/reactor.h.
Referenced by EnterNotify(), InfileToDb(), InitFrom(), retired(), Snapshot(), and Tick().
int cycamore::Reactor::refuel_time private
Definition at line 241 of file _tmp_build/cycamore/reactor.h.
Referenced by GetMatlRequests(), InfileToDb(), InitFrom(), retired(), Snapshot(), and Tock().
std::map< int, int > cycamore::Reactor::res_indexes private
Definition at line 316 of file _tmp_build/cycamore/reactor.h.
Referenced by GetMatlRequests(), index_res(), InfileToDb(), InitFrom(), Load(), retired(), and Snapshot().
cyclus::toolkit::ResBuf< cyclus::Material > cycamore::Reactor::spent private
Definition at line 297 of file _tmp_build/cycamore/reactor.h.
Referenced by CheckDecommissionCondition(), Discharge(), InitFrom(), InitInv(), PeekSpent(), PopSpent(), retired(), SnapshotInv(), and Tick().
std::set< std::string > cycamore::Reactor::uniq_outcommods_ private
Definition at line 322 of file _tmp_build/cycamore/reactor.h.
Referenced by GetMatlRequests(), and retired().
The documentation for this class was generated from the following files:
_tmp_build/cycamore/reactor.h
_tmp_build/cycamore/reactor.cc