CYCAMORE: cycamore::FillConverter Class Reference
cycamore::FillConverter Class Reference
Public Member Functions
virtual double convert (cyclus::Material::Ptr m, cyclus::Arc const *a=NULL, cyclus::ExchangeTranslationContext< cyclus::Material > const *ctx=NULL) const
virtual double convert (cyclus::Material::Ptr m, cyclus::Arc const *a=NULL, cyclus::ExchangeTranslationContext< cyclus::Material > const *ctx=NULL) const
virtual double convert (cyclus::Material::Ptr m, cyclus::Arc const *a=NULL, cyclus::ExchangeTranslationContext< cyclus::Material > const *ctx=NULL) const
FillConverter (Composition::Ptr c_fill, Composition::Ptr c_fiss, Composition::Ptr c_topup, std::string spectrum)
FillConverter (Composition::Ptr c_fill, Composition::Ptr c_fiss, Composition::Ptr c_topup, std::string spectrum)
FillConverter (Composition::Ptr c_fill, Composition::Ptr c_fiss, Composition::Ptr c_topup, std::string spectrum)
virtual ~FillConverter ()
virtual ~FillConverter ()
virtual ~FillConverter ()
Private Attributes
Composition::Ptr c_fill_
Composition::Ptr c_fiss_
Composition::Ptr c_topup_
std::string spec_
double w_fill_
double w_fiss_
double w_topup_
Detailed Description
Definition at line 54 of file _tmp_build/cycamore/fuel_fab.cc.
Constructor & Destructor Documentation
cycamore::FillConverter::FillConverter (Composition::Ptr c_fill, Composition::Ptr c_fiss, Composition::Ptr c_topup, std::string spectrum) inline
Definition at line 56 of file _tmp_build/cycamore/fuel_fab.cc.
References cycamore::CosiWeight(), w_fill_, w_fiss_, and w_topup_.
virtual cycamore::FillConverter::~FillConverter () inline virtual
Definition at line 64 of file _tmp_build/cycamore/fuel_fab.cc.
cycamore::FillConverter::FillConverter (Composition::Ptr c_fill, Composition::Ptr c_fiss, Composition::Ptr c_topup, std::string spectrum) inline
Definition at line 56 of file build/cycamore/fuel_fab.cc.
References cycamore::CosiWeight(), w_fill_, w_fiss_, and w_topup_.
virtual cycamore::FillConverter::~FillConverter () inline virtual
Definition at line 64 of file build/cycamore/fuel_fab.cc.
cycamore::FillConverter::FillConverter (Composition::Ptr c_fill, Composition::Ptr c_fiss, Composition::Ptr c_topup, std::string spectrum) inline
Definition at line 55 of file src/fuel_fab.cc.
References cycamore::CosiWeight(), w_fill_, w_fiss_, and w_topup_.
virtual cycamore::FillConverter::~FillConverter () inline virtual
Definition at line 63 of file src/fuel_fab.cc.
Member Function Documentation
virtual double cycamore::FillConverter::convert (cyclus::Material::Ptr m, cyclus::Arc const * a = NULL, cyclus::ExchangeTranslationContext< cyclus::Material > const * ctx = NULL) const inline virtual
Definition at line 65 of file src/fuel_fab.cc.
References cycamore::AtomToMassFrac(), c_fill_, c_fiss_, cycamore::CosiWeight(), cycamore::LowFrac(), spec_, cycamore::ValidWeights(), w_fill_, w_fiss_, and w_topup_.
virtual double cycamore::FillConverter::convert (cyclus::Material::Ptr m, cyclus::Arc const * a = NULL, cyclus::ExchangeTranslationContext< cyclus::Material > const * ctx = NULL) const inline virtual
Definition at line 66 of file _tmp_build/cycamore/fuel_fab.cc.
References cycamore::AtomToMassFrac(), c_fill_, c_fiss_, cycamore::CosiWeight(), cycamore::LowFrac(), spec_, cycamore::ValidWeights(), w_fill_, w_fiss_, and w_topup_.
virtual double cycamore::FillConverter::convert (cyclus::Material::Ptr m, cyclus::Arc const * a = NULL, cyclus::ExchangeTranslationContext< cyclus::Material > const * ctx = NULL) const inline virtual
Definition at line 66 of file build/cycamore/fuel_fab.cc.
References cycamore::AtomToMassFrac(), c_fill_, c_fiss_, cycamore::CosiWeight(), cycamore::LowFrac(), spec_, cycamore::ValidWeights(), w_fill_, w_fiss_, and w_topup_.
Member Data Documentation
Composition::Ptr cycamore::FillConverter::c_fill_ private
Definition at line 88 of file _tmp_build/cycamore/fuel_fab.cc.
Referenced by convert().
Composition::Ptr cycamore::FillConverter::c_fiss_ private
Definition at line 87 of file _tmp_build/cycamore/fuel_fab.cc.
Referenced by convert().
Composition::Ptr cycamore::FillConverter::c_topup_ private
Definition at line 89 of file _tmp_build/cycamore/fuel_fab.cc.
std::string cycamore::FillConverter::spec_ private
Definition at line 83 of file _tmp_build/cycamore/fuel_fab.cc.
Referenced by convert().
double cycamore::FillConverter::w_fill_ private
Definition at line 86 of file _tmp_build/cycamore/fuel_fab.cc.
Referenced by convert(), and FillConverter().
double cycamore::FillConverter::w_fiss_ private
Definition at line 84 of file _tmp_build/cycamore/fuel_fab.cc.
Referenced by convert(), and FillConverter().
double cycamore::FillConverter::w_topup_ private
Definition at line 85 of file _tmp_build/cycamore/fuel_fab.cc.
Referenced by convert(), and FillConverter().
The documentation for this class was generated from the following file:
_tmp_build/cycamore/fuel_fab.cc