CYCAMORE: run_inputs Namespace Reference
run_inputs Namespace Reference
Classes
class Summary
class TestFile
Functions
def check_inputs ()
def clean_catalogs (cyclus_path, catalogs)
def copy_catalogs (catalogs, cyclus_path)
def get_files (path)
def main ()
def main_body (flag)
def print_usage ()
Variables
string cyclus_path = "/home/stomps/.local/include/cyclus/../../bin/cyclus"
string input_path = "/home/stomps/dev-cyclus/cycamore/../input"
Function Documentation
check_inputs()
def run_inputs.check_inputs ()
This function checks the input arguments
Definition at line 28 of file _tmp_build/bin/run_inputs.py.
References print_usage().
Referenced by main().
clean_catalogs()
def run_inputs.clean_catalogs (cyclus_path, catalogs)
Removes previously copied catalogs from executable directory.
Definition at line 89 of file _tmp_build/bin/run_inputs.py.
Referenced by main_body().
copy_catalogs()
def run_inputs.copy_catalogs (catalogs, cyclus_path)
Copies files in the catalogs list to the cyclus executable directory
Definition at line 83 of file _tmp_build/bin/run_inputs.py.
Referenced by main_body().
get_files()
def run_inputs.get_files (path)
This function walks the 'path' tree and finds input files
Definition at line 59 of file _tmp_build/bin/run_inputs.py.
Referenced by main_body().
main()
def run_inputs.main ()
This function finds input files, runs them, and prints a summary
Definition at line 23 of file _tmp_build/bin/run_inputs.py.
References check_inputs(), and main_body().
Referenced by run_inputs.TestFile.no_errors().
main_body()
def run_inputs.main_body (flag)
Definition at line 12 of file _tmp_build/bin/run_inputs.py.
References clean_catalogs(), copy_catalogs(), and get_files().
Referenced by main().
print_usage()
def run_inputs.print_usage ()
This prints the proper way to treat the command line interface
Definition at line 43 of file _tmp_build/bin/run_inputs.py.
Referenced by check_inputs().
Variable Documentation
cyclus_path
string run_inputs.cyclus_path = "/home/stomps/.local/include/cyclus/../../bin/cyclus"
Definition at line 9 of file _tmp_build/bin/run_inputs.py.
input_path
string run_inputs.input_path = "/home/stomps/dev-cyclus/cycamore/../input"
Definition at line 10 of file _tmp_build/bin/run_inputs.py.