CYCAMORE: cycamore::fuelfabtests Namespace Reference
cycamore::fuelfabtests Namespace Reference
Functions
Composition::Ptr c_mox ()
Composition::Ptr c_natu ()
Composition::Ptr c_pustream ()
Composition::Ptr c_pustreambad ()
Composition::Ptr c_pustreamlow ()
Composition::Ptr c_uox ()
Composition::Ptr c_water ()
TEST (FuelFabTests, CosiWeight)
TEST (FuelFabTests, CosiWeight_Mixed)
TEST (FuelFabTests, HighFrac)
TEST (FuelFabTests, LowFrac)
TEST (FuelFabTests, ValidWeights)
TEST (FuelFabTests, FissRecipe)
TEST (FuelFabTests, MultipleFissStreams)
TEST (FuelFabTests, FissStreamPrefs)
TEST (FuelFabTests, ZeroThroughput)
TEST (FuelFabTests, FillAllInventories)
TEST (FuelFabTests, ProvideStraightFiss_WithZeroFill)
TEST (FuelFabTests, ProvideStraightFill_ZeroFiss)
TEST (FuelFabTests, ThroughputLimit)
TEST (FuelFabTests, CorrectMixing)
TEST (FuelFabTests, FillConstrained)
TEST (FuelFabTests, FissConstrained)
TEST (FuelFabTests, SwapTopup)
TEST (FuelFabTests, SwapTopup_ZeroFill)
TEST (FuelFabTests, SwapTopup_TopupConstrained)
TEST (FuelFabTests, SwapTopup_FissConstrained)
TEST (FuelFabTests, HomogenousBuffers)
TEST (FuelFabTests, PositionInitialize)
TEST (FuelFabTests, PositionInitialize2)
Function Documentation
c_mox()
Composition::Ptr cycamore::fuelfabtests::c_mox ()
Definition at line 25 of file _tmp_build/cycamore/fuel_fab_tests.cc.
c_natu()
Composition::Ptr cycamore::fuelfabtests::c_natu ()
Definition at line 33 of file _tmp_build/cycamore/fuel_fab_tests.cc.
Referenced by TEST().
c_pustream()
Composition::Ptr cycamore::fuelfabtests::c_pustream ()
Definition at line 40 of file _tmp_build/cycamore/fuel_fab_tests.cc.
Referenced by TEST().
c_pustreambad()
Composition::Ptr cycamore::fuelfabtests::c_pustreambad ()
Definition at line 58 of file _tmp_build/cycamore/fuel_fab_tests.cc.
Referenced by TEST().
c_pustreamlow()
Composition::Ptr cycamore::fuelfabtests::c_pustreamlow ()
Definition at line 49 of file _tmp_build/cycamore/fuel_fab_tests.cc.
c_uox()
Composition::Ptr cycamore::fuelfabtests::c_uox ()
Definition at line 18 of file _tmp_build/cycamore/fuel_fab_tests.cc.
Referenced by TEST().
c_water()
Composition::Ptr cycamore::fuelfabtests::c_water ()
Definition at line 67 of file _tmp_build/cycamore/fuel_fab_tests.cc.
TEST() [1/23]
cycamore::fuelfabtests::TEST (FuelFabTests , CosiWeight)
Definition at line 74 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References cycamore::CosiWeight().
TEST() [2/23]
cycamore::fuelfabtests::TEST (FuelFabTests , CosiWeight_Mixed)
Definition at line 124 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References cycamore::AtomToMassFrac(), c_natu(), c_pustream(), c_uox(), cycamore::CosiWeight(), cycamore::HighFrac(), and cycamore::LowFrac().
TEST() [3/23]
cycamore::fuelfabtests::TEST (FuelFabTests , HighFrac)
Definition at line 144 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References c_natu(), c_pustream(), c_uox(), cycamore::CosiWeight(), and cycamore::HighFrac().
TEST() [4/23]
cycamore::fuelfabtests::TEST (FuelFabTests , LowFrac)
Definition at line 158 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References c_natu(), c_pustream(), c_uox(), cycamore::CosiWeight(), and cycamore::LowFrac().
TEST() [5/23]
cycamore::fuelfabtests::TEST (FuelFabTests , ValidWeights)
Definition at line 172 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References c_natu(), c_pustream(), c_uox(), cycamore::CosiWeight(), and cycamore::ValidWeights().
TEST() [6/23]
cycamore::fuelfabtests::TEST (FuelFabTests , FissRecipe)
Definition at line 187 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References c_natu(), c_pustream(), and cycamore::string.
TEST() [7/23]
cycamore::fuelfabtests::TEST (FuelFabTests , MultipleFissStreams)
Definition at line 222 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References c_natu(), c_pustream(), and cycamore::string.
TEST() [8/23]
cycamore::fuelfabtests::TEST (FuelFabTests , FissStreamPrefs)
Definition at line 263 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References c_natu(), c_pustream(), and cycamore::string.
TEST() [9/23]
cycamore::fuelfabtests::TEST (FuelFabTests , ZeroThroughput)
Definition at line 304 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References c_natu(), c_pustream(), c_uox(), and cycamore::string.
TEST() [10/23]
cycamore::fuelfabtests::TEST (FuelFabTests , FillAllInventories)
Definition at line 337 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References c_natu(), c_pustream(), c_uox(), and cycamore::string.
TEST() [11/23]
cycamore::fuelfabtests::TEST (FuelFabTests , ProvideStraightFiss_WithZeroFill)
Definition at line 387 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References c_natu(), c_pustream(), c_uox(), and cycamore::string.
TEST() [12/23]
cycamore::fuelfabtests::TEST (FuelFabTests , ProvideStraightFill_ZeroFiss)
Definition at line 417 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References c_natu(), c_pustream(), c_uox(), and cycamore::string.
TEST() [13/23]
cycamore::fuelfabtests::TEST (FuelFabTests , ThroughputLimit)
Definition at line 449 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References c_natu(), c_pustream(), c_uox(), and cycamore::string.
TEST() [14/23]
cycamore::fuelfabtests::TEST (FuelFabTests , CorrectMixing)
Definition at line 495 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References c_natu(), c_pustream(), c_uox(), cycamore::CosiWeight(), and cycamore::string.
TEST() [15/23]
cycamore::fuelfabtests::TEST (FuelFabTests , FillConstrained)
Definition at line 545 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References cycamore::AtomToMassFrac(), c_natu(), c_pustream(), c_uox(), cycamore::CosiWeight(), cycamore::HighFrac(), cycamore::LowFrac(), and cycamore::string.
TEST() [16/23]
cycamore::fuelfabtests::TEST (FuelFabTests , FissConstrained)
Definition at line 591 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References cycamore::AtomToMassFrac(), c_natu(), c_pustream(), c_uox(), cycamore::CosiWeight(), cycamore::HighFrac(), cycamore::LowFrac(), and cycamore::string.
TEST() [17/23]
cycamore::fuelfabtests::TEST (FuelFabTests , SwapTopup)
Definition at line 636 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References c_natu(), c_pustream(), c_pustreambad(), c_uox(), and cycamore::string.
TEST() [18/23]
cycamore::fuelfabtests::TEST (FuelFabTests , SwapTopup_ZeroFill)
Definition at line 686 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References c_natu(), c_pustream(), c_pustreambad(), c_uox(), and cycamore::string.
TEST() [19/23]
cycamore::fuelfabtests::TEST (FuelFabTests , SwapTopup_TopupConstrained)
Definition at line 741 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References cycamore::AtomToMassFrac(), c_natu(), c_pustream(), c_pustreambad(), c_uox(), cycamore::CosiWeight(), cycamore::HighFrac(), cycamore::LowFrac(), and cycamore::string.
TEST() [20/23]
cycamore::fuelfabtests::TEST (FuelFabTests , SwapTopup_FissConstrained)
Definition at line 796 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References cycamore::AtomToMassFrac(), c_natu(), c_pustream(), c_pustreambad(), c_uox(), cycamore::CosiWeight(), cycamore::HighFrac(), cycamore::LowFrac(), and cycamore::string.
TEST() [21/23]
cycamore::fuelfabtests::TEST (FuelFabTests , HomogenousBuffers)
Definition at line 856 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References c_natu(), c_pustream(), c_uox(), and cycamore::string.
TEST() [22/23]
cycamore::fuelfabtests::TEST (FuelFabTests , PositionInitialize)
Definition at line 894 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References cycamore::AtomToMassFrac(), c_natu(), c_pustream(), c_pustreambad(), c_uox(), cycamore::CosiWeight(), cycamore::HighFrac(), cycamore::LowFrac(), and cycamore::string.
TEST() [23/23]
cycamore::fuelfabtests::TEST (FuelFabTests , PositionInitialize2)
Definition at line 940 of file _tmp_build/cycamore/fuel_fab_tests.cc.
References cycamore::AtomToMassFrac(), c_natu(), c_pustream(), c_pustreambad(), c_uox(), cycamore::CosiWeight(), cycamore::HighFrac(), cycamore::LowFrac(), and cycamore::string.