CYCAMORE: cycamore::reactortests Namespace Reference
cycamore::reactortests Namespace Reference
Functions
Composition::Ptr c_mox ()
Composition::Ptr c_spentmox ()
Composition::Ptr c_spentuox ()
Composition::Ptr c_uox ()
Composition::Ptr c_water ()
TEST (ReactorTests, JustInTimeOrdering)
TEST (ReactorTests, BatchSizes)
TEST (ReactorTests, RefuelTimes)
TEST (ReactorTests, DecomTimes)
TEST (ReactorTests, DecomZeroRefuel)
TEST (ReactorTests, OrderAtRefuelStart)
TEST (ReactorTests, MultiFuelMix)
TEST (ReactorTests, FullSpentInventory)
TEST (ReactorTests, FullSpentInventoryShutdown)
TEST (ReactorTests, FuelShortage)
TEST (ReactorTests, DischargedFuelTransmute)
TEST (ReactorTests, SpentFuelProperCommodTracking)
TEST (ReactorTests, PrefChange)
TEST (ReactorTests, RecipeChange)
TEST (ReactorTests, Retire)
TEST (ReactorTests, PositionInitialize)
TEST (ReactorTests, PositionInitialize2)
TEST (ReactorTests, ByProduct)
TEST (ReactorTests, MultipleByProduct)
Function Documentation
c_mox()
Composition::Ptr cycamore::reactortests::c_mox ()
Definition at line 24 of file _tmp_build/cycamore/reactor_tests.cc.
Referenced by TEST().
c_spentmox()
Composition::Ptr cycamore::reactortests::c_spentmox ()
Definition at line 40 of file _tmp_build/cycamore/reactor_tests.cc.
Referenced by TEST().
c_spentuox()
Composition::Ptr cycamore::reactortests::c_spentuox ()
Definition at line 32 of file _tmp_build/cycamore/reactor_tests.cc.
Referenced by TEST().
c_uox()
Composition::Ptr cycamore::reactortests::c_uox ()
Definition at line 17 of file _tmp_build/cycamore/reactor_tests.cc.
Referenced by TEST().
c_water()
Composition::Ptr cycamore::reactortests::c_water ()
Definition at line 48 of file _tmp_build/cycamore/reactor_tests.cc.
Referenced by TEST().
TEST() [1/19]
cycamore::reactortests::TEST (ReactorTests , JustInTimeOrdering)
Definition at line 58 of file _tmp_build/cycamore/reactor_tests.cc.
References c_spentuox(), c_uox(), and cycamore::string.
TEST() [2/19]
cycamore::reactortests::TEST (ReactorTests , BatchSizes)
Definition at line 85 of file _tmp_build/cycamore/reactor_tests.cc.
References c_spentuox(), c_uox(), and cycamore::string.
TEST() [3/19]
cycamore::reactortests::TEST (ReactorTests , RefuelTimes)
Definition at line 112 of file _tmp_build/cycamore/reactor_tests.cc.
References c_spentuox(), c_uox(), and cycamore::string.
TEST() [4/19]
cycamore::reactortests::TEST (ReactorTests , DecomTimes)
Definition at line 142 of file _tmp_build/cycamore/reactor_tests.cc.
References c_spentuox(), c_uox(), and cycamore::string.
TEST() [5/19]
cycamore::reactortests::TEST (ReactorTests , DecomZeroRefuel)
Definition at line 181 of file _tmp_build/cycamore/reactor_tests.cc.
References c_spentuox(), c_uox(), and cycamore::string.
TEST() [6/19]
cycamore::reactortests::TEST (ReactorTests , OrderAtRefuelStart)
Definition at line 214 of file _tmp_build/cycamore/reactor_tests.cc.
References c_spentuox(), c_uox(), and cycamore::string.
TEST() [7/19]
cycamore::reactortests::TEST (ReactorTests , MultiFuelMix)
Definition at line 243 of file _tmp_build/cycamore/reactor_tests.cc.
References c_spentuox(), c_uox(), and cycamore::string.
TEST() [8/19]
cycamore::reactortests::TEST (ReactorTests , FullSpentInventory)
Definition at line 279 of file _tmp_build/cycamore/reactor_tests.cc.
References c_spentuox(), c_uox(), and cycamore::string.
TEST() [9/19]
cycamore::reactortests::TEST (ReactorTests , FullSpentInventoryShutdown)
Definition at line 309 of file _tmp_build/cycamore/reactor_tests.cc.
References c_spentuox(), c_uox(), and cycamore::string.
TEST() [10/19]
cycamore::reactortests::TEST (ReactorTests , FuelShortage)
Definition at line 341 of file _tmp_build/cycamore/reactor_tests.cc.
References c_spentuox(), c_uox(), and cycamore::string.
TEST() [11/19]
cycamore::reactortests::TEST (ReactorTests , DischargedFuelTransmute)
Definition at line 390 of file _tmp_build/cycamore/reactor_tests.cc.
References c_spentuox(), c_uox(), and cycamore::string.
TEST() [12/19]
cycamore::reactortests::TEST (ReactorTests , SpentFuelProperCommodTracking)
Definition at line 424 of file _tmp_build/cycamore/reactor_tests.cc.
References c_mox(), c_spentmox(), c_spentuox(), c_uox(), and cycamore::string.
TEST() [13/19]
cycamore::reactortests::TEST (ReactorTests , PrefChange)
Definition at line 464 of file _tmp_build/cycamore/reactor_tests.cc.
References c_spentuox(), c_uox(), and cycamore::string.
TEST() [14/19]
cycamore::reactortests::TEST (ReactorTests , RecipeChange)
Definition at line 493 of file _tmp_build/cycamore/reactor_tests.cc.
References c_spentuox(), c_uox(), c_water(), and cycamore::string.
TEST() [15/19]
cycamore::reactortests::TEST (ReactorTests , Retire)
Definition at line 565 of file _tmp_build/cycamore/reactor_tests.cc.
References c_spentuox(), c_uox(), and cycamore::string.
TEST() [16/19]
cycamore::reactortests::TEST (ReactorTests , PositionInitialize)
Definition at line 623 of file _tmp_build/cycamore/reactor_tests.cc.
References c_spentuox(), c_uox(), and cycamore::string.
TEST() [17/19]
cycamore::reactortests::TEST (ReactorTests , PositionInitialize2)
Definition at line 649 of file _tmp_build/cycamore/reactor_tests.cc.
References c_spentuox(), c_uox(), and cycamore::string.
TEST() [18/19]
cycamore::reactortests::TEST (ReactorTests , ByProduct)
Definition at line 677 of file _tmp_build/cycamore/reactor_tests.cc.
References c_spentuox(), c_uox(), and cycamore::string.
TEST() [19/19]
cycamore::reactortests::TEST (ReactorTests , MultipleByProduct)
Definition at line 714 of file _tmp_build/cycamore/reactor_tests.cc.
References c_spentuox(), c_uox(), and cycamore::string.