CYCAMORE: install Namespace Reference
install Namespace Reference
Functions
def check_windows_cmake (cmake_cmd)
def install_cyclus (args)
def main ()
def uninstall_cyclus (args)
def update_describe ()
Variables
absexpanduser = lambda x: os.path.abspath(os.path.expanduser(x))
Function Documentation
check_windows_cmake()
def install.check_windows_cmake (cmake_cmd)
Definition at line 23 of file install.py.
Referenced by install_cyclus().
install_cyclus()
def install.install_cyclus (args)
Definition at line 43 of file install.py.
References absexpanduser, check_windows_cmake(), and update_describe().
Referenced by main().
main()
def install.main ()
Definition at line 125 of file install.py.
References absexpanduser, install_cyclus(), and uninstall_cyclus().
uninstall_cyclus()
def install.uninstall_cyclus (args)
Definition at line 117 of file install.py.
Referenced by main().
update_describe()
def install.update_describe ()
Definition at line 37 of file install.py.
Referenced by install_cyclus().
Variable Documentation
absexpanduser
install.absexpanduser = lambda x: os.path.abspath(os.path.expanduser(x))
Definition at line 20 of file install.py.
Referenced by install_cyclus(), and main().