CYCAMORE: cycamore Namespace Reference
cycamore Namespace Reference
Namespaces
fuelfabtests
reactortests
Classes
class DeployInst
class Enrichment
The Enrichment facility is a simple Agent that enriches natural uranium in a Cyclus simulation.
class EnrichmentTest
class FillConverter
class FissConverter
class FuelFab
FuelFab takes in 2 streams of material and mixes them in ratios in order to supply material that matches some neutronics properties of reqeusted material.
class GrowthRegion
This region determines if there is a need to meet a certain capacity (as defined via input) at each time step.
class ManagerInst
class Mixer
Mixer mixes N streams with fixed, static, user-specified ratios into a single output stream.
class MixerTest
class NatUConverter
The NatUConverter is a simple Converter class for material to determine the amount of natural uranium required for their proposed enrichment.
class Reactor
Reactor is a simple, general reactor based on static compositional transformations to model fuel burnup.
class Separations
Separations processes feed material into one or more streams containing specific elements and/or nuclides.
class Sink
This facility acts as a sink of materials and products with a fixed throughput (per time step) capacity and a lifetime capacity defined by a total inventory size.
class Source
This facility acts as a source of material with a fixed throughput (per time step) capacity and a lifetime capacity defined by a total inventory size.
class SourceTest
class SWUConverter
The SWUConverter is a simple Converter class for material to determine the amount of SWU required for their proposed enrichment.
class TopupConverter
Typedefs
typedef std::map< int, std::vector< std::string > > BuildSched
typedef std::vector< std::pair< int, std::pair< std::string, std::string > > > Demand
A container of (time, (demand type, demand parameters))
typedef std::pair< double, std::map< int, double > > Stream
typedef std::map< std::string, Stream > StreamSet
typedef std::vector< std::pair< std::pair< double, double >, std::map< std::string, double > > > t_instream
Functions
void AddCommodityDemand_ (std::string commod, Demand &demand)
add a demand for a commodity on which this region request that facilities be built
double AtomToMassFrac (double atomfrac, Composition::Ptr c1, Composition::Ptr c2)
double AtomToMassFrac (double atomfrac, cyclus::Composition::Ptr c1, cyclus::Composition::Ptr c2)
Composition::Ptr c_heu ()
Composition::Ptr c_leu ()
cyclus::Composition::Ptr c_natu ()
Composition::Ptr c_natu1 ()
Composition::Ptr c_natu2 ()
Composition::Ptr c_nou235 ()
cyclus::Composition::Ptr c_pustream ()
cyclus::Composition::Ptr c_uox ()
cyclus::Agent * ConstructDeployInst (cyclus::Context *ctx)
cyclus::Agent * ConstructEnrichment (cyclus::Context *ctx)
cyclus::Agent * ConstructFuelFab (cyclus::Context *ctx)
cyclus::Agent * ConstructGrowthRegion (cyclus::Context *ctx)
cyclus::Agent * ConstructManagerInst (cyclus::Context *ctx)
cyclus::Agent * ConstructMixer (cyclus::Context *ctx)
cyclus::Agent * ConstructReactor (cyclus::Context *ctx)
cyclus::Agent * ConstructSeparations (cyclus::Context *ctx)
cyclus::Agent * ConstructSink (cyclus::Context *ctx)
cyclus::Agent * ConstructSource (cyclus::Context *ctx)
bool Contains (std::vector< std::string > vec, std::string s)
double CosiWeight (cyclus::Composition::Ptr c, const std::string &spectrum)
double HighFrac (double w_low, double w_target, double w_high, double eps)
double LowFrac (double w_low, double w_target, double w_high, double eps)
void OrderBuilds (cyclus::toolkit::Commodity &commodity, double unmetdemand)
orders builds given a commodity and an unmet demand for production capacity of that commodity
void RecordPosition ()
Records an agent's latitude and longitude to the output db.
void Register_ (cyclus::Agent *agent)
register a child
cyclus::Material::Ptr SepMaterial (std::map< int, double > effs, cyclus::Material::Ptr mat)
SepMaterial returns a material object that represents the composition and quantity resulting from the separation of material from mat using the given mass-based efficiencies.
Material::Ptr SepMaterial (std::map< int, double > effs, Material::Ptr mat)
bool SortBids (cyclus::Bid< cyclus::Material > *i, cyclus::Bid< cyclus::Material > *j)
TEST (SeparationsTests, SepMaterial)
TEST (SeparationsTests, SeparationEfficiency)
TEST (SeparationsTests, SeparationEfficiencyThrowing)
TEST (SeparationsTests, SepMixElemAndNuclide)
TEST (SeparationsTests, Retire)
TEST (MixerTests, MultipleFissStreams)
TEST (SeparationsTests, PositionInitialize)
TEST (SeparationsTests, PositionInitialize2)
TEST (MixerTests, CompleteMixingProcess)
TEST (MixerTests, PositionInitialize)
TEST_F (SourceTest, Clone)
TEST_F (SourceTest, Print)
TEST_F (EnrichmentTest, RequestQty)
TEST_F (SourceTest, AddBids)
TEST_F (SourceTest, Response)
TEST_F (EnrichmentTest, CheckSWUConstraint)
TEST_F (SourceTest, PositionInitialize)
TEST_F (EnrichmentTest, CheckCapConstraint)
TEST_F (SourceTest, Longitude)
TEST_F (EnrichmentTest, RequestEnrich)
TEST_F (MixerTest, StreamDefaultRatio)
TEST_F (MixerTest, StreamRatio)
TEST_F (EnrichmentTest, TradeTails)
TEST_F (MixerTest, MixingComposition)
TEST_F (EnrichmentTest, TailsQty)
TEST_F (MixerTest, Throughput)
TEST_F (EnrichmentTest, BidPrefs)
TEST_F (EnrichmentTest, NoBidPrefs)
TEST_F (EnrichmentTest, ZeroU235)
TEST_F (EnrichmentTest, Request)
TEST_F (EnrichmentTest, ValidReq)
TEST_F (EnrichmentTest, ConstraintConverters)
TEST_F (EnrichmentTest, Enrich)
TEST_F (EnrichmentTest, Response)
TEST_F (EnrichmentTest, PositionInitialize)
TEST_F (EnrichmentTest, PositionInitialize2)
void Unregister_ (cyclus::Agent *agent)
unregister a child
bool ValidWeights (double w_low, double w_target, double w_high)
Variables
cycamore::GrowthRegion commodity_demand
cyclus::toolkit::Position coordinates
cycamore::GrowthRegion int
double latitude
double longitude
cyclus::toolkit::SupplyDemandManager sdmanager_
manager for Supply and demand
cycamore::GrowthRegion string
Typedef Documentation
BuildSched
typedef std::map< int, std::vector< std::string > > cycamore::BuildSched
Definition at line 15 of file _tmp_build/cycamore/deploy_inst.h.
Demand
typedef std::vector< std::pair< int, std::pair< std::string, std::string > > > cycamore::Demand
A container of (time, (demand type, demand parameters))
Definition at line 25 of file _tmp_build/cycamore/growth_region.h.
Stream
typedef std::pair< double, std::map< int, double > > cycamore::Stream
Definition at line 52 of file _tmp_build/cycamore/separations.cc.
StreamSet
typedef std::map< std::string, Stream > cycamore::StreamSet
Definition at line 53 of file _tmp_build/cycamore/separations.cc.
t_instream
typedef std::vector< std::pair< std::pair< double, double >, std::map< std::string, double > > > cycamore::t_instream
Definition at line 19 of file _tmp_build/cycamore/mixer_tests.cc.
Function Documentation
AddCommodityDemand_()
void cycamore::AddCommodityDemand_ (std::string commod, Demand & demand)
add a demand for a commodity on which this region request that facilities be built
AtomToMassFrac() [1/2]
double cycamore::AtomToMassFrac (double atomfrac, Composition::Ptr c1, Composition::Ptr c2)
Definition at line 699 of file _tmp_build/cycamore/fuel_fab.cc.
Referenced by Contains(), cycamore::FissConverter::convert(), cycamore::FillConverter::convert(), cycamore::TopupConverter::convert(), cycamore::fuelfabtests::TEST(), and cycamore::FuelFab::Tock().
AtomToMassFrac() [2/2]
double cycamore::AtomToMassFrac (double atomfrac, cyclus::Composition::Ptr c1, cyclus::Composition::Ptr c2)
c_heu()
Composition::Ptr cycamore::c_heu ()
Definition at line 46 of file _tmp_build/cycamore/enrichment_tests.cc.
Referenced by TEST_F().
c_leu()
Composition::Ptr cycamore::c_leu ()
Definition at line 40 of file _tmp_build/cycamore/enrichment_tests.cc.
Referenced by TEST_F().
c_natu()
cyclus::Composition::Ptr cycamore::c_natu ()
Definition at line 32 of file _tmp_build/cycamore/mixer_tests.cc.
Referenced by cycamore::MixerTest::GetStreamBuffer(), TEST(), and TEST_F().
c_natu1()
Composition::Ptr cycamore::c_natu1 ()
Definition at line 28 of file _tmp_build/cycamore/enrichment_tests.cc.
Referenced by TEST_F().
c_natu2()
Composition::Ptr cycamore::c_natu2 ()
Definition at line 34 of file _tmp_build/cycamore/enrichment_tests.cc.
Referenced by TEST_F().
c_nou235()
Composition::Ptr cycamore::c_nou235 ()
Definition at line 23 of file _tmp_build/cycamore/enrichment_tests.cc.
Referenced by TEST_F().
c_pustream()
cyclus::Composition::Ptr cycamore::c_pustream ()
Definition at line 21 of file _tmp_build/cycamore/mixer_tests.cc.
Referenced by cycamore::MixerTest::GetStreamBuffer(), TEST(), and TEST_F().
c_uox()
cyclus::Composition::Ptr cycamore::c_uox ()
Definition at line 41 of file _tmp_build/cycamore/mixer_tests.cc.
Referenced by cycamore::MixerTest::GetStreamBuffer(), TEST(), and TEST_F().
ConstructDeployInst()
cyclus::Agent * cycamore::ConstructDeployInst (cyclus::Context * ctx)
Definition at line 84 of file _tmp_build/cycamore/deploy_inst.cc.
References cycamore::DeployInst::DeployInst().
ConstructEnrichment()
cyclus::Agent * cycamore::ConstructEnrichment (cyclus::Context * ctx)
Definition at line 486 of file _tmp_build/cycamore/enrichment.cc.
References cycamore::Enrichment::Enrichment().
ConstructFuelFab()
cyclus::Agent * cycamore::ConstructFuelFab (cyclus::Context * ctx)
Definition at line 511 of file _tmp_build/cycamore/fuel_fab.cc.
References cycamore::FuelFab::FuelFab().
Referenced by cycamore::TopupConverter::convert().
ConstructGrowthRegion()
cyclus::Agent * cycamore::ConstructGrowthRegion (cyclus::Context * ctx)
Definition at line 190 of file _tmp_build/cycamore/growth_region.cc.
References cycamore::GrowthRegion::GrowthRegion().
ConstructManagerInst()
cyclus::Agent * cycamore::ConstructManagerInst (cyclus::Context * ctx)
Definition at line 106 of file _tmp_build/cycamore/manager_inst.cc.
References cycamore::ManagerInst::ManagerInst().
ConstructMixer()
cyclus::Agent * cycamore::ConstructMixer (cyclus::Context * ctx)
Definition at line 220 of file _tmp_build/cycamore/mixer.cc.
References cycamore::Mixer::Mixer().
ConstructReactor()
cyclus::Agent * cycamore::ConstructReactor (cyclus::Context * ctx)
Definition at line 1818 of file _tmp_build/cycamore/reactor.cc.
References cycamore::Reactor::Reactor().
ConstructSeparations()
cyclus::Agent * cycamore::ConstructSeparations (cyclus::Context * ctx)
Definition at line 396 of file _tmp_build/cycamore/separations.cc.
References cycamore::Separations::Separations().
ConstructSink()
cyclus::Agent * cycamore::ConstructSink (cyclus::Context * ctx)
Definition at line 519 of file _tmp_build/cycamore/sink.cc.
References cycamore::Sink::Sink().
ConstructSource()
cyclus::Agent * cycamore::ConstructSource (cyclus::Context * ctx)
Definition at line 171 of file _tmp_build/cycamore/source.cc.
References cycamore::Source::Source().
Contains()
bool cycamore::Contains (std::vector< std::string > vec, std::string s)
Definition at line 234 of file _tmp_build/cycamore/fuel_fab.cc.
References cycamore::FuelFab::AcceptMatlTrades(), AtomToMassFrac(), CosiWeight(), cycamore::FuelFab::fill, cycamore::FuelFab::fill_recipe, cycamore::FuelFab::fiss, cycamore::FuelFab::fiss_recipe, cycamore::FuelFab::GetMatlBids(), cycamore::FuelFab::GetMatlTrades(), HighFrac(), LowFrac(), cycamore::FuelFab::outcommod, cycamore::FuelFab::req_inventories_, cycamore::FuelFab::spectrum, string, cycamore::FuelFab::throughput, cycamore::FuelFab::topup, cycamore::FuelFab::topup_recipe, and ValidWeights().
Referenced by cycamore::TopupConverter::convert().
CosiWeight()
double cycamore::CosiWeight (cyclus::Composition::Ptr c, const std::string & spectrum)
Definition at line 528 of file _tmp_build/cycamore/fuel_fab.cc.
References cycamore::FuelFab::fiss.
Referenced by Contains(), cycamore::FissConverter::convert(), cycamore::FillConverter::convert(), cycamore::TopupConverter::convert(), cycamore::FillConverter::FillConverter(), cycamore::FissConverter::FissConverter(), cycamore::fuelfabtests::TEST(), cycamore::FuelFab::Tock(), and cycamore::TopupConverter::TopupConverter().
HighFrac()
double cycamore::HighFrac (double w_low, double w_target, double w_high, double eps)
Definition at line 721 of file _tmp_build/cycamore/fuel_fab.cc.
References ValidWeights().
Referenced by Contains(), cycamore::FissConverter::convert(), cycamore::TopupConverter::convert(), LowFrac(), cycamore::fuelfabtests::TEST(), and cycamore::FuelFab::Tock().
LowFrac()
double cycamore::LowFrac (double w_low, double w_target, double w_high, double eps)
Definition at line 736 of file _tmp_build/cycamore/fuel_fab.cc.
References HighFrac().
Referenced by Contains(), cycamore::FissConverter::convert(), cycamore::FillConverter::convert(), cycamore::TopupConverter::convert(), cycamore::fuelfabtests::TEST(), and cycamore::FuelFab::Tock().
OrderBuilds()
void cycamore::OrderBuilds (cyclus::toolkit::Commodity & commodity, double unmetdemand)
orders builds given a commodity and an unmet demand for production capacity of that commodity
Parameters
commodity the commodity being demanded
unmetdemand the unmet demand
RecordPosition()
void cycamore::RecordPosition () private
Records an agent's latitude and longitude to the output db.
Referenced by cycamore::TopupConverter::convert(), and cycamore::Enrichment::Tails().
Register_()
void cycamore::Register_ (cyclus::Agent * agent)
register a child
SepMaterial() [1/2]
cyclus::Material::Ptr cycamore::SepMaterial (std::map< int, double > effs, cyclus::Material::Ptr mat)
SepMaterial returns a material object that represents the composition and quantity resulting from the separation of material from mat using the given mass-based efficiencies.
Each key in effs represents a nuclide or element (canonical PyNE form), and each value is the corresponding mass-based separations efficiency for that nuclide or element. Note that this returns an untracked material that should only be used for its composition and qty
not in any real inventories, etc.
SepMaterial() [2/2]
Material::Ptr cycamore::SepMaterial (std::map< int, double > effs, Material::Ptr mat)
Definition at line 168 of file _tmp_build/cycamore/separations.cc.
Referenced by TEST(), and cycamore::Separations::Tick().
SortBids()
bool cycamore::SortBids (cyclus::Bid< cyclus::Material > * i, cyclus::Bid< cyclus::Material > * j)
Definition at line 101 of file _tmp_build/cycamore/enrichment.cc.
Referenced by cycamore::Enrichment::AdjustMatlPrefs().
TEST() [1/10]
cycamore::TEST (SeparationsTests , SepMaterial)
Definition at line 17 of file _tmp_build/cycamore/separations_tests.cc.
References SepMaterial().
TEST() [2/10]
cycamore::TEST (SeparationsTests , SeparationEfficiency)
Definition at line 48 of file _tmp_build/cycamore/separations_tests.cc.
References string.
TEST() [3/10]
cycamore::TEST (SeparationsTests , SeparationEfficiencyThrowing)
Definition at line 141 of file _tmp_build/cycamore/separations_tests.cc.
References string.
TEST() [4/10]
cycamore::TEST (SeparationsTests , SepMixElemAndNuclide)
Definition at line 239 of file _tmp_build/cycamore/separations_tests.cc.
References string.
TEST() [5/10]
cycamore::TEST (SeparationsTests , Retire)
Definition at line 284 of file _tmp_build/cycamore/separations_tests.cc.
References string.
TEST() [6/10]
cycamore::TEST (MixerTests , MultipleFissStreams)
Definition at line 325 of file _tmp_build/cycamore/mixer_tests.cc.
References c_natu(), c_pustream(), c_uox(), and string.
Referenced by cycamore::MixerTest::GetStreamBuffer().
TEST() [7/10]
cycamore::TEST (SeparationsTests , PositionInitialize)
Definition at line 344 of file _tmp_build/cycamore/separations_tests.cc.
References string.
TEST() [8/10]
cycamore::TEST (SeparationsTests , PositionInitialize2)
Definition at line 382 of file _tmp_build/cycamore/separations_tests.cc.
References string.
TEST() [9/10]
cycamore::TEST (MixerTests , CompleteMixingProcess)
Definition at line 399 of file _tmp_build/cycamore/mixer_tests.cc.
References c_natu(), c_pustream(), c_uox(), and string.
TEST() [10/10]
cycamore::TEST (MixerTests , PositionInitialize)
Definition at line 464 of file _tmp_build/cycamore/mixer_tests.cc.
References c_natu(), c_pustream(), c_uox(), and string.
TEST_F() [1/26]
cycamore::TEST_F (SourceTest , Clone)
Definition at line 39 of file _tmp_build/cycamore/source_tests.cc.
References cycamore::Source::Clone(), cycamore::SourceTest::outcommod(), cycamore::SourceTest::outrecipe(), cycamore::SourceTest::src_facility, cycamore::SourceTest::tc, and cycamore::SourceTest::throughput().
TEST_F() [2/26]
cycamore::TEST_F (SourceTest , Print)
Definition at line 51 of file _tmp_build/cycamore/source_tests.cc.
References cycamore::SourceTest::src_facility, cycamore::Source::str(), and string.
TEST_F() [3/26]
cycamore::TEST_F (EnrichmentTest , RequestQty)
Definition at line 54 of file _tmp_build/cycamore/enrichment_tests.cc.
References c_natu1(), and string.
Referenced by cycamore::MixerTest::GetStreamBuffer().
TEST_F() [4/26]
cycamore::TEST_F (SourceTest , AddBids)
Definition at line 55 of file _tmp_build/cycamore/source_tests.cc.
References cycamore::SourceTest::capacity, cycamore::SourceTest::commod, cycamore::SourceTest::GetContext(), cycamore::Source::GetMatlBids(), and cycamore::SourceTest::src_facility.
TEST_F() [5/26]
cycamore::TEST_F (SourceTest , Response)
Definition at line 83 of file _tmp_build/cycamore/source_tests.cc.
References cycamore::SourceTest::capacity, cycamore::SourceTest::commod, cycamore::Source::GetMatlTrades(), cycamore::SourceTest::recipe, cycamore::SourceTest::src_facility, cycamore::Source::Tick(), and cycamore::SourceTest::trader.
TEST_F() [6/26]
cycamore::TEST_F (EnrichmentTest , CheckSWUConstraint)
Definition at line 90 of file _tmp_build/cycamore/enrichment_tests.cc.
References c_heu(), c_natu1(), and string.
TEST_F() [7/26]
cycamore::TEST_F (SourceTest , PositionInitialize)
Definition at line 126 of file _tmp_build/cycamore/source_tests.cc.
References string.
TEST_F() [8/26]
cycamore::TEST_F (EnrichmentTest , CheckCapConstraint)
Definition at line 131 of file _tmp_build/cycamore/enrichment_tests.cc.
References c_heu(), c_natu1(), and string.
TEST_F() [9/26]
cycamore::TEST_F (SourceTest , Longitude)
Definition at line 140 of file _tmp_build/cycamore/source_tests.cc.
References string.
TEST_F() [10/26]
cycamore::TEST_F (EnrichmentTest , RequestEnrich)
Definition at line 170 of file _tmp_build/cycamore/enrichment_tests.cc.
References c_heu(), c_leu(), c_natu1(), and string.
TEST_F() [11/26]
cycamore::TEST_F (MixerTest , StreamDefaultRatio)
Definition at line 177 of file _tmp_build/cycamore/mixer_tests.cc.
References cycamore::Mixer::EnterNotify(), cycamore::MixerTest::GetStream_ratio(), cycamore::MixerTest::in_coms, cycamore::MixerTest::mf_facility_, cycamore::MixerTest::SetOutStream_capacity(), and cycamore::MixerTest::SetThroughput().
TEST_F() [12/26]
cycamore::TEST_F (MixerTest , StreamRatio)
Definition at line 192 of file _tmp_build/cycamore/mixer_tests.cc.
References cycamore::Mixer::EnterNotify(), cycamore::MixerTest::GetStream_ratio(), cycamore::MixerTest::mf_facility_, cycamore::MixerTest::SetOutStream_capacity(), cycamore::MixerTest::SetStream_capacity(), cycamore::MixerTest::SetStream_ratio(), and cycamore::MixerTest::SetThroughput().
TEST_F() [13/26]
cycamore::TEST_F (EnrichmentTest , TradeTails)
Definition at line 226 of file _tmp_build/cycamore/enrichment_tests.cc.
References c_leu(), c_natu1(), and string.
TEST_F() [14/26]
cycamore::TEST_F (MixerTest , MixingComposition)
Definition at line 232 of file _tmp_build/cycamore/mixer_tests.cc.
References c_natu(), c_pustream(), c_uox(), cycamore::MixerTest::GetOutPutBuffer(), cycamore::MixerTest::in_cap, cycamore::MixerTest::mf_facility_, cycamore::MixerTest::SetInputInv(), cycamore::MixerTest::SetOutStream_capacity(), cycamore::MixerTest::SetStream_ratio(), cycamore::MixerTest::SetThroughput(), and cycamore::Mixer::Tick().
TEST_F() [15/26]
cycamore::TEST_F (EnrichmentTest , TailsQty)
Definition at line 263 of file _tmp_build/cycamore/enrichment_tests.cc.
References c_leu(), c_natu1(), and string.
TEST_F() [16/26]
cycamore::TEST_F (MixerTest , Throughput)
Definition at line 278 of file _tmp_build/cycamore/mixer_tests.cc.
References c_natu(), c_pustream(), c_uox(), cycamore::MixerTest::GetOutPutBuffer(), cycamore::MixerTest::GetStreamBuffer(), cycamore::MixerTest::in_cap, cycamore::MixerTest::in_coms, cycamore::MixerTest::in_frac, cycamore::MixerTest::mf_facility_, cycamore::MixerTest::SetInputInv(), cycamore::MixerTest::SetOutStream_capacity(), cycamore::MixerTest::SetStream_ratio(), cycamore::MixerTest::SetThroughput(), string, cycamore::MixerTest::throughput, and cycamore::Mixer::Tick().
TEST_F() [17/26]
cycamore::TEST_F (EnrichmentTest , BidPrefs)
Definition at line 319 of file _tmp_build/cycamore/enrichment_tests.cc.
References c_natu1(), c_natu2(), and string.
TEST_F() [18/26]
cycamore::TEST_F (EnrichmentTest , NoBidPrefs)
Definition at line 370 of file _tmp_build/cycamore/enrichment_tests.cc.
References c_natu1(), c_natu2(), and string.
TEST_F() [19/26]
cycamore::TEST_F (EnrichmentTest , ZeroU235)
Definition at line 410 of file _tmp_build/cycamore/enrichment_tests.cc.
References c_natu1(), c_nou235(), and string.
TEST_F() [20/26]
cycamore::TEST_F (EnrichmentTest , Request)
Definition at line 522 of file _tmp_build/cycamore/enrichment_tests.cc.
References cycamore::EnrichmentTest::DoAddMat(), cycamore::EnrichmentTest::DoRequest(), cycamore::EnrichmentTest::feed_recipe, cycamore::EnrichmentTest::GetMat(), cycamore::EnrichmentTest::inv_size, and cycamore::EnrichmentTest::tc_.
TEST_F() [21/26]
cycamore::TEST_F (EnrichmentTest , ValidReq)
Definition at line 546 of file _tmp_build/cycamore/enrichment_tests.cc.
References cycamore::EnrichmentTest::src_facility, cycamore::EnrichmentTest::tails_assay, and cycamore::Enrichment::ValidReq().
TEST_F() [22/26]
cycamore::TEST_F (EnrichmentTest , ConstraintConverters)
Definition at line 575 of file _tmp_build/cycamore/enrichment_tests.cc.
References cycamore::SWUConverter::convert(), cycamore::NatUConverter::convert(), cycamore::EnrichmentTest::DoOffer(), cycamore::EnrichmentTest::feed_assay, and cycamore::EnrichmentTest::tails_assay.
TEST_F() [23/26]
cycamore::TEST_F (EnrichmentTest , Enrich)
Definition at line 615 of file _tmp_build/cycamore/enrichment_tests.cc.
References cycamore::EnrichmentTest::DoAddMat(), cycamore::EnrichmentTest::DoEnrich(), cycamore::EnrichmentTest::feed_assay, cycamore::EnrichmentTest::GetMat(), cycamore::Enrichment::SetMaxInventorySize(), cycamore::EnrichmentTest::src_facility, cycamore::Enrichment::SwuCapacity(), cycamore::Enrichment::Tails(), and cycamore::EnrichmentTest::tails_assay.
TEST_F() [24/26]
cycamore::TEST_F (EnrichmentTest , Response)
Definition at line 664 of file _tmp_build/cycamore/enrichment_tests.cc.
References cycamore::EnrichmentTest::DoAddMat(), cycamore::EnrichmentTest::feed_assay, cycamore::EnrichmentTest::GetMat(), cycamore::Enrichment::GetMatlTrades(), cycamore::EnrichmentTest::product_commod, cycamore::Enrichment::SetMaxInventorySize(), cycamore::EnrichmentTest::src_facility, cycamore::Enrichment::SwuCapacity(), cycamore::EnrichmentTest::tails_assay, and cycamore::EnrichmentTest::trader.
TEST_F() [25/26]
cycamore::TEST_F (EnrichmentTest , PositionInitialize)
Definition at line 728 of file _tmp_build/cycamore/enrichment_tests.cc.
References c_natu1(), and string.
TEST_F() [26/26]
cycamore::TEST_F (EnrichmentTest , PositionInitialize2)
Definition at line 755 of file _tmp_build/cycamore/enrichment_tests.cc.
References c_natu1(), and string.
Unregister_()
void cycamore::Unregister_ (cyclus::Agent * agent)
unregister a child
ValidWeights()
bool cycamore::ValidWeights (double w_low, double w_target, double w_high)
Definition at line 742 of file _tmp_build/cycamore/fuel_fab.cc.
Referenced by Contains(), cycamore::FissConverter::convert(), cycamore::FillConverter::convert(), cycamore::TopupConverter::convert(), HighFrac(), cycamore::fuelfabtests::TEST(), and cycamore::FuelFab::Tock().
Variable Documentation
commodity_demand
cycamore::GrowthRegion cycamore::commodity_demand
coordinates
cyclus::toolkit::Position cycamore::coordinates private
Definition at line 148 of file src/growth_region.h.
Referenced by cycamore::TopupConverter::convert(), and cycamore::Enrichment::Tails().
int
cycamore::GrowthRegion cycamore::int
Referenced by helper::hasher().
latitude
double cycamore::latitude private
Definition at line 138 of file src/growth_region.h.
Referenced by cycamore::TopupConverter::convert(), cycamore::Enrichment::InfileToDb(), cycamore::Enrichment::InitFrom(), cycamore::Enrichment::Snapshot(), and cycamore::Enrichment::Tails().
longitude
double cycamore::longitude private
Definition at line 146 of file src/growth_region.h.
Referenced by cycamore::TopupConverter::convert(), cycamore::Enrichment::InfileToDb(), cycamore::Enrichment::InitFrom(), cycamore::Enrichment::Snapshot(), and cycamore::Enrichment::Tails().
sdmanager_
cyclus::toolkit::SupplyDemandManager cycamore::sdmanager_
manager for Supply and demand
Definition at line 113 of file src/growth_region.h.
string
cycamore::GrowthRegion cycamore::string
Referenced by cycamore::Mixer::AcceptMatlTrades(), cycamore::GrowthRegion::AddCommodityDemand_(), cycamore::DeployInst::Build(), Contains(), cycamore::FissConverter::convert(), cycamore::FillConverter::convert(), cycamore::TopupConverter::convert(), cycamore::Mixer::EnterNotify(), cycamore::Separations::EnterNotify(), storage::Storage::EnterNotify(), cycamore::Sink::GetGenRsrcRequests(), cycamore::Mixer::GetMatlRequests(), cycamore::Separations::GetMatlRequests(), cycamore::Reactor::GetMatlRequests(), cycamore::FuelFab::GetMatlRequests(), cycamore::Enrichment::GetMatlTrades(), cycamore::MixerTest::GetStreamBuffer(), cycamore::Sink::InfileToDb(), cycamore::ManagerInst::InfileToDb(), cycamore::Mixer::InfileToDb(), cycamore::DeployInst::InfileToDb(), cycamore::GrowthRegion::InfileToDb(), storage::Storage::InfileToDb(), cycamore::Reactor::InfileToDb(), cycamore::Separations::InfileToDb(), cycamore::Source::InfileToDb(), cycamore::FuelFab::InfileToDb(), cycamore::Enrichment::InfileToDb(), cycamore::Sink::InitFrom(), storage::Storage::InitFrom(), cycamore::Reactor::InitFrom(), cycamore::FuelFab::InitFrom(), cycamore::Enrichment::InitFrom(), cycamore::Mixer::InitFrom(), cycamore::Source::InitFrom(), cycamore::Separations::InitFrom(), cycamore::Sink::input_commodity_preferences(), cycamore::Reactor::Load(), main(), cycamore::Reactor::PeekSpent(), cycamore::Reactor::PopSpent(), storage::Storage::ready_time(), cycamore::Sink::RecordPosition(), cycamore::ManagerInst::RecordPosition(), storage::Storage::RecordPosition(), cycamore::Source::RecordPosition(), cycamore::GrowthRegion::RecordPosition(), cycamore::Reactor::RecordPosition(), cycamore::DeployInst::RecordPosition(), cycamore::Mixer::RecordPosition(), cycamore::Separations::RecordPosition(), cycamore::Enrichment::RecordPosition(), cycamore::FuelFab::RecordPosition(), cycamore::Reactor::retired(), cycamore::MixerTest::SetInputInv(), cycamore::Enrichment::Snapshot(), cycamore::Sink::str(), storage::Storage::str(), cycamore::Source::str(), cycamore::Enrichment::Tails(), cycamore::MixerTest::TearDown(), TEST(), cycamore::reactortests::TEST(), cycamore::fuelfabtests::TEST(), TEST(), TEST_F(), TEST_F(), storage::TEST_F(), cycamore::SourceTest::throughput(), cycamore::Mixer::Tick(), cycamore::Separations::Tick(), cycamore::Sink::Tick(), cycamore::Reactor::Tick(), cycamore::Mixer::Tock(), cycamore::FuelFab::Tock(), cycamore::Source::Tock(), cycamore::Sink::version(), cycamore::Reactor::version(), cycamore::Separations::version(), and cycamore::Enrichment::version().