CYCAMORE: storage Namespace Reference
storage Namespace Reference
Classes
class Storage
This Facility is intended to hold materials for a user specified amount of time in order to model a storage facility with a certain residence time or holdup time.
class StorageTest
Functions
cyclus::Agent * ConstructStorage (cyclus::Context *ctx)
TEST_F (StorageTest, clone)
TEST_F (StorageTest, InitialState)
TEST_F (StorageTest, CurrentCapacity)
TEST_F (StorageTest, Print)
TEST_F (StorageTest, AddMats)
TEST_F (StorageTest, Tick)
TEST_F (StorageTest, Tock)
TEST_F (StorageTest, NoProcessTime)
TEST_F (StorageTest, NoConvert)
TEST_F (StorageTest, MultipleSmallBatches)
TEST_F (StorageTest, ChangeCapacity)
TEST_F (StorageTest, TwoBatchSameTime)
TEST_F (StorageTest, ChangeProcessTime)
TEST_F (StorageTest, DifferentRecipe)
TEST_F (StorageTest, BehaviorTest)
TEST_F (StorageTest, MultipleCommods)
TEST_F (StorageTest, PositionInitialize)
TEST_F (StorageTest, Longitude)
Function Documentation
ConstructStorage()
cyclus::Agent * storage::ConstructStorage (cyclus::Context * ctx)
Definition at line 719 of file _tmp_build/cycamore/storage.cc.
References storage::Storage::Storage().
TEST_F() [1/18]
storage::TEST_F (StorageTest , clone)
Definition at line 90 of file _tmp_build/cycamore/storage_tests.cc.
References storage::Storage::Clone(), storage::StorageTest::src_facility_, and storage::StorageTest::TestInitState().
TEST_F() [2/18]
storage::TEST_F (StorageTest , InitialState)
Definition at line 97 of file _tmp_build/cycamore/storage_tests.cc.
References storage::StorageTest::src_facility_, and storage::StorageTest::TestInitState().
TEST_F() [3/18]
storage::TEST_F (StorageTest , CurrentCapacity)
Definition at line 103 of file _tmp_build/cycamore/storage_tests.cc.
References storage::StorageTest::max_inv_size, storage::StorageTest::SetUpStorage(), storage::StorageTest::src_facility_, storage::StorageTest::TestCurrentCap(), and storage::StorageTest::TestInitState().
TEST_F() [4/18]
storage::TEST_F (StorageTest , Print)
Definition at line 111 of file _tmp_build/cycamore/storage_tests.cc.
References storage::StorageTest::src_facility_, storage::Storage::str(), and cycamore::string.
TEST_F() [5/18]
storage::TEST_F (StorageTest , AddMats)
Definition at line 117 of file _tmp_build/cycamore/storage_tests.cc.
References storage::StorageTest::in_r1, storage::StorageTest::max_inv_size, storage::StorageTest::src_facility_, storage::StorageTest::tc_, and storage::StorageTest::TestAddMat().
TEST_F() [6/18]
storage::TEST_F (StorageTest , Tick)
Definition at line 128 of file _tmp_build/cycamore/storage_tests.cc.
References storage::StorageTest::src_facility_, and storage::Storage::Tick().
TEST_F() [7/18]
storage::TEST_F (StorageTest , Tock)
Definition at line 134 of file _tmp_build/cycamore/storage_tests.cc.
References storage::StorageTest::in_r1, storage::StorageTest::residence_time, storage::StorageTest::src_facility_, storage::StorageTest::tc_, storage::StorageTest::TestAddMat(), storage::StorageTest::TestBuffers(), storage::StorageTest::TestReadyTime(), storage::StorageTest::throughput, and storage::Storage::Tock().
TEST_F() [8/18]
storage::TEST_F (StorageTest , NoProcessTime)
Definition at line 173 of file _tmp_build/cycamore/storage_tests.cc.
References storage::StorageTest::in_r1, storage::StorageTest::residence_time, storage::StorageTest::SetUpStorage(), storage::StorageTest::src_facility_, storage::StorageTest::tc_, storage::StorageTest::TestAddMat(), storage::StorageTest::TestBuffers(), storage::StorageTest::throughput, and storage::Storage::Tock().
TEST_F() [9/18]
storage::TEST_F (StorageTest , NoConvert)
Definition at line 193 of file _tmp_build/cycamore/storage_tests.cc.
References storage::StorageTest::in_r1, storage::StorageTest::residence_time, storage::StorageTest::src_facility_, storage::StorageTest::tc_, storage::StorageTest::TestAddMat(), storage::StorageTest::TestBuffers(), storage::StorageTest::TestReadyTime(), storage::StorageTest::TestStocks(), storage::StorageTest::throughput, and storage::Storage::Tock().
TEST_F() [10/18]
storage::TEST_F (StorageTest , MultipleSmallBatches)
Definition at line 212 of file _tmp_build/cycamore/storage_tests.cc.
References storage::StorageTest::in_r1, storage::StorageTest::residence_time, storage::StorageTest::src_facility_, storage::StorageTest::tc_, storage::StorageTest::TestAddMat(), storage::StorageTest::TestBuffers(), storage::StorageTest::TestReadyTime(), storage::StorageTest::throughput, and storage::Storage::Tock().
TEST_F() [11/18]
storage::TEST_F (StorageTest , ChangeCapacity)
Definition at line 249 of file _tmp_build/cycamore/storage_tests.cc.
References storage::StorageTest::in_r1, storage::StorageTest::max_inv_size, storage::StorageTest::residence_time, storage::StorageTest::SetUpStorage(), storage::StorageTest::src_facility_, storage::StorageTest::tc_, storage::StorageTest::TestAddMat(), storage::StorageTest::TestBuffers(), storage::StorageTest::throughput, and storage::Storage::Tock().
TEST_F() [12/18]
storage::TEST_F (StorageTest , TwoBatchSameTime)
Definition at line 302 of file _tmp_build/cycamore/storage_tests.cc.
References storage::StorageTest::in_r1, storage::StorageTest::residence_time, storage::StorageTest::src_facility_, storage::StorageTest::tc_, storage::StorageTest::TestAddMat(), storage::StorageTest::TestBuffers(), storage::StorageTest::throughput, and storage::Storage::Tock().
TEST_F() [13/18]
storage::TEST_F (StorageTest , ChangeProcessTime)
Definition at line 324 of file _tmp_build/cycamore/storage_tests.cc.
References storage::StorageTest::in_r1, storage::StorageTest::residence_time, storage::StorageTest::SetUpStorage(), storage::StorageTest::src_facility_, storage::StorageTest::tc_, storage::StorageTest::TestAddMat(), storage::StorageTest::TestBuffers(), storage::StorageTest::throughput, and storage::Storage::Tock().
TEST_F() [14/18]
storage::TEST_F (StorageTest , DifferentRecipe)
Definition at line 377 of file _tmp_build/cycamore/storage_tests.cc.
References storage::StorageTest::residence_time, storage::StorageTest::src_facility_, storage::StorageTest::tc_, storage::StorageTest::TestAddMat(), storage::StorageTest::TestBuffers(), storage::StorageTest::throughput, and storage::Storage::Tock().
TEST_F() [15/18]
storage::TEST_F (StorageTest , BehaviorTest)
Definition at line 396 of file _tmp_build/cycamore/storage_tests.cc.
References cycamore::string.
TEST_F() [16/18]
storage::TEST_F (StorageTest , MultipleCommods)
Definition at line 423 of file _tmp_build/cycamore/storage_tests.cc.
References cycamore::string.
TEST_F() [17/18]
storage::TEST_F (StorageTest , PositionInitialize)
Definition at line 458 of file _tmp_build/cycamore/storage_tests.cc.
References cycamore::string.
TEST_F() [18/18]
storage::TEST_F (StorageTest , Longitude)
Definition at line 481 of file _tmp_build/cycamore/storage_tests.cc.
References cycamore::string.