CYCAMORE: sink_tests.cc File Reference
src/sink_tests.cc File Reference
#include <gtest/gtest.h>
#include "facility_tests.h"
#include "agent_tests.h"
#include "resource_helpers.h"
#include "infile_tree.h"
#include "xml_parser.h"
#include "sink_tests.h"
Macros
#define CYCLUS_AGENT_TESTS_CONNECTED cyclus_agent_tests_connected
Functions
int ConnectAgentTests ()
INSTANTIATE_TEST_CASE_P (SinkFac, FacilityTests, Values(&SinkConstructor))
INSTANTIATE_TEST_CASE_P (SinkFac, AgentTests, Values(&SinkConstructor))
cyclus::Agent * SinkConstructor (cyclus::Context *ctx)
TEST_F (SinkTest, InitialState)
TEST_F (SinkTest, Clone)
TEST_F (SinkTest, DISABLED_XMLInit)
TEST_F (SinkTest, Requests)
TEST_F (SinkTest, EmptyRequests)
TEST_F (SinkTest, Accept)
TEST_F (SinkTest, InRecipe)
TEST_F (SinkTest, BidPrefs)
TEST_F (SinkTest, Print)
TEST_F (SinkTest, PositionInitialize)
TEST_F (SinkTest, PositionInitialize2)
Variables
static int cyclus_agent_tests_connected = ConnectAgentTests()
Macro Definition Documentation
CYCLUS_AGENT_TESTS_CONNECTED
#define CYCLUS_AGENT_TESTS_CONNECTED cyclus_agent_tests_connected
Definition at line 354 of file src/sink_tests.cc.
Function Documentation
ConnectAgentTests()
int ConnectAgentTests ()
Referenced by SinkConstructor().
INSTANTIATE_TEST_CASE_P() [1/2]
INSTANTIATE_TEST_CASE_P (SinkFac , FacilityTests , Values & SinkConstructor)
INSTANTIATE_TEST_CASE_P() [2/2]
INSTANTIATE_TEST_CASE_P (SinkFac , AgentTests , Values & SinkConstructor)
SinkConstructor()
cyclus::Agent* SinkConstructor (cyclus::Context * ctx)
Definition at line 346 of file src/sink_tests.cc.
References ConnectAgentTests().
TEST_F() [1/11]
TEST_F (SinkTest , InitialState)
Definition at line 44 of file src/sink_tests.cc.
References cycamore::Sink::Capacity(), SinkTest::capacity_, SinkTest::commod1_, SinkTest::commod2_, cycamore::Sink::EnterNotify(), cycamore::Sink::input_commodities(), cycamore::Sink::input_commodity_preferences(), SinkTest::inv_, cycamore::Sink::InventorySize(), cycamore::Sink::MaxInventorySize(), cycamore::Sink::RequestAmt(), SinkTest::src_facility, and cycamore::string.
TEST_F() [2/11]
TEST_F (SinkTest , Clone)
Definition at line 61 of file src/sink_tests.cc.
References SinkTest::capacity_, cycamore::Sink::Clone(), SinkTest::commod1_, SinkTest::commod2_, SinkTest::inv_, SinkTest::src_facility, and cycamore::string.
TEST_F() [3/11]
TEST_F (SinkTest , DISABLED_XMLInit)
Definition at line 78 of file src/sink_tests.cc.
References SinkTest::capacity_, SinkTest::commod1_, SinkTest::commod2_, SinkTest::inv_, cycamore::string, and SinkTest::tc_.
TEST_F() [4/11]
TEST_F (SinkTest , Requests)
Definition at line 112 of file src/sink_tests.cc.
References SinkTest::capacity_, SinkTest::commod1_, SinkTest::commod2_, cycamore::Sink::EnterNotify(), cycamore::Sink::GetMatlRequests(), SinkTest::ncommods_, SinkTest::src_facility, and cycamore::string.
TEST_F() [5/11]
TEST_F (SinkTest , EmptyRequests)
Definition at line 143 of file src/sink_tests.cc.
References cycamore::Sink::Capacity(), cycamore::Sink::GetMatlRequests(), and SinkTest::src_facility.
TEST_F() [6/11]
TEST_F (SinkTest , Accept)
Definition at line 154 of file src/sink_tests.cc.
References cycamore::Sink::AcceptMatlTrades(), SinkTest::commod1_, SinkTest::commod2_, cycamore::Sink::InventorySize(), SinkTest::qty_, and SinkTest::src_facility.
TEST_F() [7/11]
TEST_F (SinkTest , InRecipe)
Definition at line 186 of file src/sink_tests.cc.
References cycamore::Sink::AddCommodity(), cycamore::Sink::EnterNotify(), and cycamore::Sink::GetMatlRequests().
TEST_F() [8/11]
TEST_F (SinkTest , BidPrefs)
Definition at line 222 of file src/sink_tests.cc.
References cycamore::string.
TEST_F() [9/11]
TEST_F (SinkTest , Print)
Definition at line 268 of file src/sink_tests.cc.
References SinkTest::src_facility, cycamore::Sink::str(), and cycamore::string.
TEST_F() [10/11]
TEST_F (SinkTest , PositionInitialize)
Definition at line 272 of file src/sink_tests.cc.
References cycamore::string.
TEST_F() [11/11]
TEST_F (SinkTest , PositionInitialize2)
Definition at line 307 of file src/sink_tests.cc.
References cycamore::string.
Variable Documentation
cyclus_agent_tests_connected
int cyclus_agent_tests_connected = ConnectAgentTests() static
Definition at line 353 of file src/sink_tests.cc.