CYCAMORE: source_tests.cc File Reference
source_tests.cc File Reference
#include "source_tests.h"
#include <gtest/gtest.h>
#include <sstream>
#include "cyc_limits.h"
#include "resource_helpers.h"
#include "test_context.h"
Defines
#define CYCLUS_AGENT_TESTS_CONNECTED cyclus_agent_tests_connected
Functions
int ConnectAgentTests ()
INSTANTIATE_TEST_CASE_P (SourceFac, FacilityTests, Values(&SourceConstructor))
INSTANTIATE_TEST_CASE_P (SourceFac, AgentTests, Values(&SourceConstructor))
cyclus::Agent * SourceConstructor (cyclus::Context *ctx)
TEST_F (SourceTest, InitialState)
TEST_F (SourceTest, Clone)
TEST_F (SourceTest, Print)
TEST_F (SourceTest, GetOffer)
TEST_F (SourceTest, AddBids)
TEST_F (SourceTest, Response)
Variables
static int cyclus_agent_tests_connected = ConnectAgentTests()
Define Documentation
#define CYCLUS_AGENT_TESTS_CONNECTED cyclus_agent_tests_connected
Definition at line 199 of file src/source_tests.cc.
Function Documentation
int ConnectAgentTests ()
INSTANTIATE_TEST_CASE_P (SourceFac , FacilityTests , Values & SourceConstructor)
INSTANTIATE_TEST_CASE_P (SourceFac , AgentTests , Values & SourceConstructor)
cyclus::Agent* SourceConstructor (cyclus::Context * ctx)
Definition at line 191 of file src/source_tests.cc.
TEST_F (SourceTest , InitialState)
Definition at line 42 of file src/source_tests.cc.
TEST_F (SourceTest , Clone)
Definition at line 50 of file src/source_tests.cc.
References cycamore::Source::Capacity(), cycamore::Source::commodity(), cycamore::Source::CurrentCapacity(), and cycamore::Source::recipe().
TEST_F (SourceTest , Print)
Definition at line 64 of file src/source_tests.cc.
TEST_F (SourceTest , GetOffer)
Definition at line 69 of file src/source_tests.cc.
TEST_F (SourceTest , AddBids)
Definition at line 92 of file src/source_tests.cc.
TEST_F (SourceTest , Response)
Definition at line 121 of file src/source_tests.cc.
Variable Documentation
int cyclus_agent_tests_connected = ConnectAgentTests() [static]
Definition at line 198 of file src/source_tests.cc.