name: Build and Publish Cycamore Images

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/build_test_publish.yml'
      - 'docker/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build_test_publish.yml'
      - 'docker/**'

jobs:
  build-dependency-and-test-img:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ubuntu_versions : [
          20.04,
          22.04,
        ]
        pkg_mgr : [
          apt,
          conda,
        ]

    name: Installing Dependencies, Building Cycamore and Running Tests
    steps:
      - name: default environment
        run: |
          echo "tag-latest-on-default=false" >> "$GITHUB_ENV"

      - name: condition on trigger parameters
        if: ${{ github.repository_owner == 'cyclus' && github.ref == 'refs/heads/main' }}
        run: |
          echo "tag-latest-on-default=true" >> "$GITHUB_ENV"

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Multi-Stage Build Action
        uses: firehed/multistage-docker-build-action@v1
        with:
          repository: ghcr.io/${{ github.repository_owner }}/cycamore_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}
          stages: cycamore
          server-stage: cycamore-test
          quiet: false
          parallel: true
          tag-latest-on-default: ${{ env.tag-latest-on-default }}
          dockerfile: docker/Dockerfile
          build-args: pkg_mgr=${{ matrix.pkg_mgr }}, ubuntu_version=${{ matrix.ubuntu_versions }}