name: Changelog check

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  changelog_update:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14

    name: Is Changelog up-to-date ?
    steps:
      - name: Install latest git
        run: |
          apk add --no-cache bash git openssh
          git --version

      - name: Checkout repository
        uses: actions/checkout@v4

      - run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          cd $GITHUB_WORKSPACE
          git remote add cycamore https://github.com/cyclus/cycamore.git
          git fetch cycamore
          change=`git diff cycamore/main -- CHANGELOG.rst | wc -l`
          git remote remove cycamore
          if [ $change -eq 0 ]; then 
            echo "CHANGELOG.rst has not been updated"
            exit 1 
          fi

